$(PY_BUILD)/$(PARSERSRCDIR)/acceler.o: acceler.c \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 $(PARSERSRCDIR)/../Include/node.h \
 $(PARSERSRCDIR)/../Include/token.h \
 parser.h
$(PY_BUILD)/$(PARSERSRCDIR)/bitset.o: bitset.c \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/bitset.h
$(PY_BUILD)/$(PARSERSRCDIR)/firstsets.o: firstsets.c \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 $(PARSERSRCDIR)/../Include/token.h
$(PY_BUILD)/$(PARSERSRCDIR)/grammar1.o: grammar1.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 $(PARSERSRCDIR)/../Include/token.h
$(PY_BUILD)/$(PARSERSRCDIR)/grammar.o: grammar.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/token.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h
$(PY_BUILD)/$(PARSERSRCDIR)/intrcheck.o: intrcheck.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/pythread.h
$(PY_BUILD)/$(PARSERSRCDIR)/listnode.o: listnode.c \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/token.h \
 $(PARSERSRCDIR)/../Include/node.h
$(PY_BUILD)/$(PARSERSRCDIR)/metagrammar.o: metagrammar.c \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/metagrammar.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 $(PARSERSRCDIR)/../Include/pgen.h
$(PY_BUILD)/$(PARSERSRCDIR)/myreadline.o: myreadline.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h
$(PY_BUILD)/$(PARSERSRCDIR)/node.o: node.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/node.h \
 $(PARSERSRCDIR)/../Include/errcode.h
$(PY_BUILD)/$(PARSERSRCDIR)/parser.o: parser.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/token.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 $(PARSERSRCDIR)/../Include/node.h \
 parser.h \
 $(PARSERSRCDIR)/../Include/errcode.h
$(PY_BUILD)/$(PARSERSRCDIR)/parsetok.o: parsetok.c \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 tokenizer.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/token.h \
 $(PARSERSRCDIR)/../Include/node.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 parser.h \
 $(PARSERSRCDIR)/../Include/parsetok.h \
 $(PARSERSRCDIR)/../Include/errcode.h \
 $(PARSERSRCDIR)/../Include/graminit.h
$(PY_BUILD)/$(PARSERSRCDIR)/pgen.o: pgen.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/token.h \
 $(PARSERSRCDIR)/../Include/node.h \
 $(PARSERSRCDIR)/../Include/grammar.h \
 $(PARSERSRCDIR)/../Include/bitset.h \
 $(PARSERSRCDIR)/../Include/metagrammar.h \
 $(PARSERSRCDIR)/../Include/pgen.h
$(PY_BUILD)/$(PARSERSRCDIR)/tokenizer.o: tokenizer.c \
 $(PARSERSRCDIR)/../Include/Python.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/io.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(PARSERSRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(PARSERSRCDIR)/../Include/patchlevel.h \
 $(PARSERSRCDIR)/../Include/pyconfig.h \
 $(PARSERSRCDIR)/../Include/pymacconfig.h \
 $(PARSERSRCDIR)/../Include/pyport.h \
 $(PARSERSRCDIR)/../Include/pymath.h \
 $(PARSERSRCDIR)/../Include/pymem.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/objimpl.h \
 $(PARSERSRCDIR)/../Include/pydebug.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/intobject.h \
 $(PARSERSRCDIR)/../Include/boolobject.h \
 $(PARSERSRCDIR)/../Include/longobject.h \
 $(PARSERSRCDIR)/../Include/floatobject.h \
 $(PARSERSRCDIR)/../Include/complexobject.h \
 $(PARSERSRCDIR)/../Include/rangeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/memoryobject.h \
 $(PARSERSRCDIR)/../Include/bufferobject.h \
 $(PARSERSRCDIR)/../Include/bytesobject.h \
 $(PARSERSRCDIR)/../Include/bytearrayobject.h \
 $(PARSERSRCDIR)/../Include/tupleobject.h \
 $(PARSERSRCDIR)/../Include/listobject.h \
 $(PARSERSRCDIR)/../Include/dictobject.h \
 $(PARSERSRCDIR)/../Include/enumobject.h \
 $(PARSERSRCDIR)/../Include/setobject.h \
 $(PARSERSRCDIR)/../Include/methodobject.h \
 $(PARSERSRCDIR)/../Include/moduleobject.h \
 $(PARSERSRCDIR)/../Include/funcobject.h \
 $(PARSERSRCDIR)/../Include/classobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/cobject.h \
 $(PARSERSRCDIR)/../Include/pycapsule.h \
 $(PARSERSRCDIR)/../Include/traceback.h \
 $(PARSERSRCDIR)/../Include/sliceobject.h \
 $(PARSERSRCDIR)/../Include/cellobject.h \
 $(PARSERSRCDIR)/../Include/iterobject.h \
 $(PARSERSRCDIR)/../Include/genobject.h \
 $(PARSERSRCDIR)/../Include/descrobject.h \
 $(PARSERSRCDIR)/../Include/warnings.h \
 $(PARSERSRCDIR)/../Include/weakrefobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/pyerrors.h \
 $(PARSERSRCDIR)/../Include/pystate.h \
 $(PARSERSRCDIR)/../Include/pyarena.h \
 $(PARSERSRCDIR)/../Include/modsupport.h \
 $(PARSERSRCDIR)/../Include/pythonrun.h \
 $(PARSERSRCDIR)/../Include/ceval.h \
 $(PARSERSRCDIR)/../Include/sysmodule.h \
 $(PARSERSRCDIR)/../Include/intrcheck.h \
 $(PARSERSRCDIR)/../Include/import.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/compile.h \
 $(PARSERSRCDIR)/../Include/code.h \
 $(PARSERSRCDIR)/../Include/eval.h \
 $(PARSERSRCDIR)/../Include/pyctype.h \
 $(PARSERSRCDIR)/../Include/pystrtod.h \
 $(PARSERSRCDIR)/../Include/pystrcmp.h \
 $(PARSERSRCDIR)/../Include/dtoa.h \
 $(PARSERSRCDIR)/../Include/pyfpe.h \
 $(PARSERSRCDIR)/../Include/pgenheaders.h \
 $(PARSERSRCDIR)/../Include/Python.h \
 tokenizer.h \
 $(PARSERSRCDIR)/../Include/object.h \
 $(PARSERSRCDIR)/../Include/token.h \
 $(PARSERSRCDIR)/../Include/errcode.h \
 $(PARSERSRCDIR)/../Include/unicodeobject.h \
 $(PARSERSRCDIR)/../Include/stringobject.h \
 $(PARSERSRCDIR)/../Include/fileobject.h \
 $(PARSERSRCDIR)/../Include/codecs.h \
 $(PARSERSRCDIR)/../Include/abstract.h \
 $(PARSERSRCDIR)/../Include/pydebug.h
