SOURCES_PYTHON_C:=$(PYTHONSRCDIR)/asdl.c \
$(PYTHONSRCDIR)/ast.c \
$(PYTHONSRCDIR)/atof.c \
$(PYTHONSRCDIR)/bltinmodule.c \
$(PYTHONSRCDIR)/ceval.c \
$(PYTHONSRCDIR)/codecs.c \
$(PYTHONSRCDIR)/compile.c \
$(PYTHONSRCDIR)/dtoa.c \
$(PYTHONSRCDIR)/dup2.c \
$(PYTHONSRCDIR)/dynload_dl.c \
$(PYTHONSRCDIR)/errors.c \
$(PYTHONSRCDIR)/formatter_string.c \
$(PYTHONSRCDIR)/formatter_unicode.c \
$(PYTHONSRCDIR)/frozen.c \
$(PYTHONSRCDIR)/frozenmain.c \
$(PYTHONSRCDIR)/future.c \
$(PYTHONSRCDIR)/getargs.c \
$(PYTHONSRCDIR)/getcompiler.c \
$(PYTHONSRCDIR)/getcopyright.c \
$(PYTHONSRCDIR)/getcwd.c \
$(PYTHONSRCDIR)/getopt.c \
$(PYTHONSRCDIR)/getplatform.c \
$(PYTHONSRCDIR)/getversion.c \
$(PYTHONSRCDIR)/graminit.c \
$(PYTHONSRCDIR)/import.c \
$(PYTHONSRCDIR)/importdl.c \
$(PYTHONSRCDIR)/marshal.c \
$(PYTHONSRCDIR)/modsupport.c \
$(PYTHONSRCDIR)/mysnprintf.c \
$(PYTHONSRCDIR)/mystrtoul.c \
$(PYTHONSRCDIR)/peephole.c \
$(PYTHONSRCDIR)/pyarena.c \
$(PYTHONSRCDIR)/pyctype.c \
$(PYTHONSRCDIR)/pyfpe.c \
$(PYTHONSRCDIR)/pymath.c \
$(PYTHONSRCDIR)/pystate.c \
$(PYTHONSRCDIR)/pystrcmp.c \
$(PYTHONSRCDIR)/pystrtod.c \
$(PYTHONSRCDIR)/Python-ast.c \
$(PYTHONSRCDIR)/pythonrun.c \
$(PYTHONSRCDIR)/random.c \
$(PYTHONSRCDIR)/sigcheck.c \
$(PYTHONSRCDIR)/strdup.c \
$(PYTHONSRCDIR)/strtod.c \
$(PYTHONSRCDIR)/structmember.c \
$(PYTHONSRCDIR)/symtable.c \
$(PYTHONSRCDIR)/sysmodule.c \
$(PYTHONSRCDIR)/thread.c \
$(PYTHONSRCDIR)/traceback.c \
$(PYTHONSRCDIR)/_warnings.c \
$(PYTHONSRCDIR)/pymain.c