SOURCES_OBJECTS_C:=$(OBJECTSRCDIR)/abstract.c \
$(OBJECTSRCDIR)/boolobject.c \
$(OBJECTSRCDIR)/bufferobject.c \
$(OBJECTSRCDIR)/bytearrayobject.c \
$(OBJECTSRCDIR)/bytes_methods.c \
$(OBJECTSRCDIR)/capsule.c \
$(OBJECTSRCDIR)/cellobject.c \
$(OBJECTSRCDIR)/classobject.c \
$(OBJECTSRCDIR)/cobject.c \
$(OBJECTSRCDIR)/codeobject.c \
$(OBJECTSRCDIR)/complexobject.c \
$(OBJECTSRCDIR)/descrobject.c \
$(OBJECTSRCDIR)/dictobject.c \
$(OBJECTSRCDIR)/enumobject.c \
$(OBJECTSRCDIR)/exceptions.c \
$(OBJECTSRCDIR)/fileobject.c \
$(OBJECTSRCDIR)/floatobject.c \
$(OBJECTSRCDIR)/frameobject.c \
$(OBJECTSRCDIR)/funcobject.c \
$(OBJECTSRCDIR)/genobject.c \
$(OBJECTSRCDIR)/intobject.c \
$(OBJECTSRCDIR)/iterobject.c \
$(OBJECTSRCDIR)/listobject.c \
$(OBJECTSRCDIR)/longobject.c \
$(OBJECTSRCDIR)/memoryobject.c \
$(OBJECTSRCDIR)/methodobject.c \
$(OBJECTSRCDIR)/moduleobject.c \
$(OBJECTSRCDIR)/object.c \
$(OBJECTSRCDIR)/obmalloc.c \
$(OBJECTSRCDIR)/rangeobject.c \
$(OBJECTSRCDIR)/setobject.c \
$(OBJECTSRCDIR)/sliceobject.c \
$(OBJECTSRCDIR)/stringobject.c \
$(OBJECTSRCDIR)/structseq.c \
$(OBJECTSRCDIR)/tupleobject.c \
$(OBJECTSRCDIR)/typeobject.c \
$(OBJECTSRCDIR)/weakrefobject.c \
$(OBJECTSRCDIR)/unicodeobject.c \
$(OBJECTSRCDIR)/unicodectype.c
