$(MODULESRCDIR)/scipy/special/amos/dgamln.c \
$(MODULESRCDIR)/scipy/special/amos/zabs.c \
$(MODULESRCDIR)/scipy/special/amos/zacai.c \
$(MODULESRCDIR)/scipy/special/amos/zacon.c \
$(MODULESRCDIR)/scipy/special/amos/zairy.c \
$(MODULESRCDIR)/scipy/special/amos/zasyi.c \
$(MODULESRCDIR)/scipy/special/amos/zbesh.c \
$(MODULESRCDIR)/scipy/special/amos/zbesi.c \
$(MODULESRCDIR)/scipy/special/amos/zbesj.c \
$(MODULESRCDIR)/scipy/special/amos/zbesk.c \
$(MODULESRCDIR)/scipy/special/amos/zbesy.c \
$(MODULESRCDIR)/scipy/special/amos/zbinu.c \
$(MODULESRCDIR)/scipy/special/amos/zbiry.c \
$(MODULESRCDIR)/scipy/special/amos/zbknu.c \
$(MODULESRCDIR)/scipy/special/amos/zbuni.c \
$(MODULESRCDIR)/scipy/special/amos/zbunk.c \
$(MODULESRCDIR)/scipy/special/amos/zdiv.c \
$(MODULESRCDIR)/scipy/special/amos/zexp.c \
$(MODULESRCDIR)/scipy/special/amos/zkscl.c \
$(MODULESRCDIR)/scipy/special/amos/zlog.c \
$(MODULESRCDIR)/scipy/special/amos/zmlri.c \
$(MODULESRCDIR)/scipy/special/amos/zmlt.c \
$(MODULESRCDIR)/scipy/special/amos/zrati.c \
$(MODULESRCDIR)/scipy/special/amos/zs1s2.c \
$(MODULESRCDIR)/scipy/special/amos/zseri.c \
$(MODULESRCDIR)/scipy/special/amos/zshch.c \
$(MODULESRCDIR)/scipy/special/amos/zsqrt.c \
$(MODULESRCDIR)/scipy/special/amos/zuchk.c \
$(MODULESRCDIR)/scipy/special/amos/zunhj.c \
$(MODULESRCDIR)/scipy/special/amos/zuni1.c \
$(MODULESRCDIR)/scipy/special/amos/zuni2.c \
$(MODULESRCDIR)/scipy/special/amos/zunik.c \
$(MODULESRCDIR)/scipy/special/amos/zunk1.c \
$(MODULESRCDIR)/scipy/special/amos/zunk2.c \
$(MODULESRCDIR)/scipy/special/amos/zuoik.c \
$(MODULESRCDIR)/scipy/special/amos/zwrsk.c \
