SOURCES_MAIN_C:=$(MAINSRCDIR)/deparse.c \
$(MAINSRCDIR)/myconnections.c \
$(MAINSRCDIR)/mysysutils.c \
$(MAINSRCDIR)/RNG.c \
$(MAINSRCDIR)/apply.c \
$(MAINSRCDIR)/arithmetic.c \
$(MAINSRCDIR)/array.c \
$(MAINSRCDIR)/attrib.c \
$(MAINSRCDIR)/bind.c \
$(MAINSRCDIR)/builtin.c \
$(MAINSRCDIR)/character.c \
$(MAINSRCDIR)/coerce.c \
$(MAINSRCDIR)/context.c \
$(MAINSRCDIR)/cum.c \
$(MAINSRCDIR)/debug.c \
$(MAINSRCDIR)/dstruct.c \
$(MAINSRCDIR)/duplicate.c \
$(MAINSRCDIR)/envir.c \
$(MAINSRCDIR)/errors.c \
$(MAINSRCDIR)/eval.c \
$(MAINSRCDIR)/format.c \
$(MAINSRCDIR)/gram.c \
$(MAINSRCDIR)/identical.c \
$(MAINSRCDIR)/inlined.c \
$(MAINSRCDIR)/inspect.c \
$(MAINSRCDIR)/iosupport.c \
$(MAINSRCDIR)/lapack.c \
$(MAINSRCDIR)/list.c \
$(MAINSRCDIR)/localecharset.c \
$(MAINSRCDIR)/logic.c \
$(MAINSRCDIR)/gtmain.c \
$(MAINSRCDIR)/mapply.c \
$(MAINSRCDIR)/match.c \
$(MAINSRCDIR)/memory.c \
$(MAINSRCDIR)/Lapack.c \
$(MAINSRCDIR)/names.c \
$(MAINSRCDIR)/objects.c \
$(MAINSRCDIR)/options.c \
$(MAINSRCDIR)/paste.c \
$(MAINSRCDIR)/qsort.c \
$(MAINSRCDIR)/radixsort.c \
$(MAINSRCDIR)/random.c \
$(MAINSRCDIR)/raw.c \
$(MAINSRCDIR)/registration.c \
$(MAINSRCDIR)/relop.c \
$(MAINSRCDIR)/scan.c \
$(MAINSRCDIR)/seq.c \
$(MAINSRCDIR)/sort.c \
$(MAINSRCDIR)/source.c \
$(MAINSRCDIR)/split.c \
$(MAINSRCDIR)/sprintf.c \
$(MAINSRCDIR)/startup.c \
$(MAINSRCDIR)/subassign.c \
$(MAINSRCDIR)/subscript.c \
$(MAINSRCDIR)/subset.c \
$(MAINSRCDIR)/summary.c \
$(MAINSRCDIR)/times.c \
$(MAINSRCDIR)/unique.c \
$(MAINSRCDIR)/version.c \
$(MAINSRCDIR)/rlocale.c \
$(MAINSRCDIR)/printarray.c \
$(MAINSRCDIR)/printvector.c \
$(MAINSRCDIR)/Rmain.c \
$(MAINSRCDIR)/alloca.c \
$(MAINSRCDIR)/strdup.c \
$(MAINSRCDIR)/strncasecmp.c \
$(MAINSRCDIR)/util.c \
$(MAINSRCDIR)/print.c \
$(MAINSRCDIR)/printutils.c \
$(MAINSRCDIR)/platform.c \
$(MAINSRCDIR)/Rdynload.c \
$(MAINSRCDIR)/complex.c \
$(MAINSRCDIR)/complexfun.c \
$(MAINSRCDIR)/dotcode.c
	
