SOURCES_NMATH_C:=$(NMATHSRCDIR)/qbeta.c \
$(NMATHSRCDIR)/mlutils.c \
$(NMATHSRCDIR)/d1mach.c \
$(NMATHSRCDIR)/i1mach.c \
$(NMATHSRCDIR)/fmax2.c \
$(NMATHSRCDIR)/fmin2.c \
$(NMATHSRCDIR)/fprec.c \
$(NMATHSRCDIR)/fround.c \
$(NMATHSRCDIR)/ftrunc.c \
$(NMATHSRCDIR)/sign.c \
$(NMATHSRCDIR)/fsign.c \
$(NMATHSRCDIR)/imax2.c \
$(NMATHSRCDIR)/imin2.c \
$(NMATHSRCDIR)/chebyshev.c \
$(NMATHSRCDIR)/log1p.c \
$(NMATHSRCDIR)/expm1.c \
$(NMATHSRCDIR)/lgammacor.c \
$(NMATHSRCDIR)/gammalims.c \
$(NMATHSRCDIR)/stirlerr.c \
$(NMATHSRCDIR)/bd0.c \
$(NMATHSRCDIR)/gamma.c \
$(NMATHSRCDIR)/lgamma.c \
$(NMATHSRCDIR)/gamma_cody.c \
$(NMATHSRCDIR)/beta.c \
$(NMATHSRCDIR)/lbeta.c \
$(NMATHSRCDIR)/polygamma.c \
$(NMATHSRCDIR)/cospi.c \
$(NMATHSRCDIR)/bessel_i.c \
$(NMATHSRCDIR)/bessel_j.c \
$(NMATHSRCDIR)/bessel_k.c \
$(NMATHSRCDIR)/bessel_y.c \
$(NMATHSRCDIR)/choose.c \
$(NMATHSRCDIR)/snorm.c \
$(NMATHSRCDIR)/sexp.c \
$(NMATHSRCDIR)/dgamma.c \
$(NMATHSRCDIR)/pgamma.c \
$(NMATHSRCDIR)/qgamma.c \
$(NMATHSRCDIR)/rgamma.c \
$(NMATHSRCDIR)/dbeta.c \
$(NMATHSRCDIR)/pbeta.c \
$(NMATHSRCDIR)/rbeta.c \
$(NMATHSRCDIR)/dunif.c \
$(NMATHSRCDIR)/punif.c \
$(NMATHSRCDIR)/qunif.c \
$(NMATHSRCDIR)/runif.c \
$(NMATHSRCDIR)/dnorm.c \
$(NMATHSRCDIR)/pnorm.c \
$(NMATHSRCDIR)/qnorm.c \
$(NMATHSRCDIR)/rnorm.c \
$(NMATHSRCDIR)/dlnorm.c \
$(NMATHSRCDIR)/plnorm.c \
$(NMATHSRCDIR)/qlnorm.c \
$(NMATHSRCDIR)/rlnorm.c \
$(NMATHSRCDIR)/df.c \
$(NMATHSRCDIR)/pf.c \
$(NMATHSRCDIR)/qf.c \
$(NMATHSRCDIR)/rf.c \
$(NMATHSRCDIR)/dnf.c \
$(NMATHSRCDIR)/dt.c \
$(NMATHSRCDIR)/pt.c \
$(NMATHSRCDIR)/qt.c \
$(NMATHSRCDIR)/rt.c \
$(NMATHSRCDIR)/dnt.c \
$(NMATHSRCDIR)/dchisq.c \
$(NMATHSRCDIR)/pchisq.c \
$(NMATHSRCDIR)/qchisq.c \
$(NMATHSRCDIR)/rchisq.c \
$(NMATHSRCDIR)/rnchisq.c \
$(NMATHSRCDIR)/dbinom.c \
$(NMATHSRCDIR)/pbinom.c \
$(NMATHSRCDIR)/qbinom.c \
$(NMATHSRCDIR)/rbinom.c \
$(NMATHSRCDIR)/rmultinom.c \
$(NMATHSRCDIR)/dcauchy.c \
$(NMATHSRCDIR)/pcauchy.c \
$(NMATHSRCDIR)/qcauchy.c \
$(NMATHSRCDIR)/rcauchy.c \
$(NMATHSRCDIR)/dexp.c \
$(NMATHSRCDIR)/pexp.c \
$(NMATHSRCDIR)/qexp.c \
$(NMATHSRCDIR)/rexp.c \
$(NMATHSRCDIR)/dgeom.c \
$(NMATHSRCDIR)/pgeom.c \
$(NMATHSRCDIR)/qgeom.c \
$(NMATHSRCDIR)/rgeom.c \
$(NMATHSRCDIR)/dhyper.c \
$(NMATHSRCDIR)/phyper.c \
$(NMATHSRCDIR)/qhyper.c \
$(NMATHSRCDIR)/rhyper.c \
$(NMATHSRCDIR)/dnbinom.c \
$(NMATHSRCDIR)/pnbinom.c \
$(NMATHSRCDIR)/qnbinom.c \
$(NMATHSRCDIR)/rnbinom.c \
$(NMATHSRCDIR)/dpois.c \
$(NMATHSRCDIR)/ppois.c \
$(NMATHSRCDIR)/qpois.c \
$(NMATHSRCDIR)/rpois.c \
$(NMATHSRCDIR)/dweibull.c \
$(NMATHSRCDIR)/pweibull.c \
$(NMATHSRCDIR)/qweibull.c \
$(NMATHSRCDIR)/rweibull.c \
$(NMATHSRCDIR)/dlogis.c \
$(NMATHSRCDIR)/plogis.c \
$(NMATHSRCDIR)/qlogis.c \
$(NMATHSRCDIR)/rlogis.c \
$(NMATHSRCDIR)/dnchisq.c \
$(NMATHSRCDIR)/pnchisq.c \
$(NMATHSRCDIR)/qnchisq.c \
$(NMATHSRCDIR)/dnbeta.c \
$(NMATHSRCDIR)/pnbeta.c \
$(NMATHSRCDIR)/qnbeta.c \
$(NMATHSRCDIR)/pnf.c \
$(NMATHSRCDIR)/pnt.c \
$(NMATHSRCDIR)/qnf.c \
$(NMATHSRCDIR)/qnt.c \
$(NMATHSRCDIR)/ptukey.c \
$(NMATHSRCDIR)/qtukey.c \
$(NMATHSRCDIR)/wilcox.c \
$(NMATHSRCDIR)/signrank.c

