SOURCES_LAPACK_C:=$(LAPACKSRCDIR)/SRC/cgetrf2.c \
$(LAPACKSRCDIR)/SRC/ilaver.c \
$(LAPACKSRCDIR)/SRC/cgegv.c \
$(LAPACKSRCDIR)/SRC/dgegv.c \
$(LAPACKSRCDIR)/SRC/zgegv.c \
$(LAPACKSRCDIR)/SRC/sgegv.c \
$(LAPACKSRCDIR)/SRC/zpotrf2.c \
$(LAPACKSRCDIR)/SRC/spotrf2.c \
$(LAPACKSRCDIR)/SRC/ztrevc3.c \
$(LAPACKSRCDIR)/SRC/cbbcsd.c \
$(LAPACKSRCDIR)/SRC/cbdsqr.c \
$(LAPACKSRCDIR)/SRC/cgbbrd.c \
$(LAPACKSRCDIR)/SRC/cgbcon.c \
$(LAPACKSRCDIR)/SRC/cgbequb.c \
$(LAPACKSRCDIR)/SRC/cgbequ.c \
$(LAPACKSRCDIR)/SRC/cgbrfs.c \
$(LAPACKSRCDIR)/SRC/cgbsv.c \
$(LAPACKSRCDIR)/SRC/cgbsvx.c \
$(LAPACKSRCDIR)/SRC/cgbsvxx.c \
$(LAPACKSRCDIR)/SRC/cgbtf2.c \
$(LAPACKSRCDIR)/SRC/cgbtrf.c \
$(LAPACKSRCDIR)/SRC/cgbtrs.c \
$(LAPACKSRCDIR)/SRC/cgebak.c \
$(LAPACKSRCDIR)/SRC/cgebal.c \
$(LAPACKSRCDIR)/SRC/cgebd2.c \
$(LAPACKSRCDIR)/SRC/cgebrd.c \
$(LAPACKSRCDIR)/SRC/cgecon.c \
$(LAPACKSRCDIR)/SRC/cgeequb.c \
$(LAPACKSRCDIR)/SRC/cgeequ.c \
$(LAPACKSRCDIR)/SRC/cgees.c \
$(LAPACKSRCDIR)/SRC/cgeesx.c \
$(LAPACKSRCDIR)/SRC/cgeev.c \
$(LAPACKSRCDIR)/SRC/cgeevx.c \
$(LAPACKSRCDIR)/SRC/cgehd2.c \
$(LAPACKSRCDIR)/SRC/cgehrd.c \
$(LAPACKSRCDIR)/SRC/cgelq2.c \
$(LAPACKSRCDIR)/SRC/cgelq.c \
$(LAPACKSRCDIR)/SRC/cgelqf.c \
$(LAPACKSRCDIR)/SRC/cgelqt.c \
$(LAPACKSRCDIR)/SRC/cgels.c \
$(LAPACKSRCDIR)/SRC/cgelsd.c \
$(LAPACKSRCDIR)/SRC/cgelss.c \
$(LAPACKSRCDIR)/SRC/cgelsy.c \
$(LAPACKSRCDIR)/SRC/cgemlq.c \
$(LAPACKSRCDIR)/SRC/cgemlqt.c \
$(LAPACKSRCDIR)/SRC/cgemqr.c \
$(LAPACKSRCDIR)/SRC/cgemqrt.c \
$(LAPACKSRCDIR)/SRC/cgeql2.c \
$(LAPACKSRCDIR)/SRC/cgeqlf.c \
$(LAPACKSRCDIR)/SRC/cgeqp3.c \
$(LAPACKSRCDIR)/SRC/cgeqr2.c \
$(LAPACKSRCDIR)/SRC/cgeqr2p.c \
$(LAPACKSRCDIR)/SRC/cgeqr.c \
$(LAPACKSRCDIR)/SRC/cgeqrf.c \
$(LAPACKSRCDIR)/SRC/cgeqrfp.c \
$(LAPACKSRCDIR)/SRC/cgeqrt2.c \
$(LAPACKSRCDIR)/SRC/cgeqrt3.c \
$(LAPACKSRCDIR)/SRC/cgeqrt.c \
$(LAPACKSRCDIR)/SRC/cgerfs.c \
$(LAPACKSRCDIR)/SRC/cgerq2.c \
$(LAPACKSRCDIR)/SRC/cgerqf.c \
$(LAPACKSRCDIR)/SRC/cgesc2.c \
$(LAPACKSRCDIR)/SRC/cgesdd.c \
$(LAPACKSRCDIR)/SRC/cgesv.c \
$(LAPACKSRCDIR)/SRC/cgesvd.c \
$(LAPACKSRCDIR)/SRC/cgesvdx.c \
$(LAPACKSRCDIR)/SRC/cgesvj.c \
$(LAPACKSRCDIR)/SRC/cgesvx.c \
$(LAPACKSRCDIR)/SRC/cgesvxx.c \
$(LAPACKSRCDIR)/SRC/cgetc2.c \
$(LAPACKSRCDIR)/SRC/cgetf2.c \
$(LAPACKSRCDIR)/SRC/cgetrf.c \
$(LAPACKSRCDIR)/SRC/cgetri.c \
$(LAPACKSRCDIR)/SRC/cgetrs.c \
$(LAPACKSRCDIR)/SRC/cgetsls.c \
$(LAPACKSRCDIR)/SRC/cggbak.c \
$(LAPACKSRCDIR)/SRC/cggbal.c \
$(LAPACKSRCDIR)/SRC/cgges3.c \
$(LAPACKSRCDIR)/SRC/cgges.c \
$(LAPACKSRCDIR)/SRC/cggesx.c \
$(LAPACKSRCDIR)/SRC/cggev3.c \
$(LAPACKSRCDIR)/SRC/cggev.c \
$(LAPACKSRCDIR)/SRC/cggevx.c \
$(LAPACKSRCDIR)/SRC/cggglm.c \
$(LAPACKSRCDIR)/SRC/cgghd3.c \
$(LAPACKSRCDIR)/SRC/cgghrd.c \
$(LAPACKSRCDIR)/SRC/cgglse.c \
$(LAPACKSRCDIR)/SRC/cggqrf.c \
$(LAPACKSRCDIR)/SRC/cggrqf.c \
$(LAPACKSRCDIR)/SRC/cggsvd3.c \
$(LAPACKSRCDIR)/SRC/cggsvp3.c \
$(LAPACKSRCDIR)/SRC/cgsvj0.c \
$(LAPACKSRCDIR)/SRC/cgsvj1.c \
$(LAPACKSRCDIR)/SRC/cgtcon.c \
$(LAPACKSRCDIR)/SRC/cgtrfs.c \
$(LAPACKSRCDIR)/SRC/cgtsv.c \
$(LAPACKSRCDIR)/SRC/cgtsvx.c \
$(LAPACKSRCDIR)/SRC/cgttrf.c \
$(LAPACKSRCDIR)/SRC/cgttrs.c \
$(LAPACKSRCDIR)/SRC/cgtts2.c \
$(LAPACKSRCDIR)/SRC/chb2st_kernels.c \
$(LAPACKSRCDIR)/SRC/chbev_2stage.c \
$(LAPACKSRCDIR)/SRC/chbev.c \
$(LAPACKSRCDIR)/SRC/chbevd_2stage.c \
$(LAPACKSRCDIR)/SRC/chbevd.c \
$(LAPACKSRCDIR)/SRC/chbevx_2stage.c \
$(LAPACKSRCDIR)/SRC/chbevx.c \
$(LAPACKSRCDIR)/SRC/chbgst.c \
$(LAPACKSRCDIR)/SRC/chbgv.c \
$(LAPACKSRCDIR)/SRC/chbgvd.c \
$(LAPACKSRCDIR)/SRC/chbgvx.c \
$(LAPACKSRCDIR)/SRC/chbtrd.c \
$(LAPACKSRCDIR)/SRC/checon_3.c \
$(LAPACKSRCDIR)/SRC/checon.c \
$(LAPACKSRCDIR)/SRC/checon_rook.c \
$(LAPACKSRCDIR)/SRC/cheequb.c \
$(LAPACKSRCDIR)/SRC/cheev_2stage.c \
$(LAPACKSRCDIR)/SRC/cheev.c \
$(LAPACKSRCDIR)/SRC/cheevd_2stage.c \
$(LAPACKSRCDIR)/SRC/cheevd.c \
$(LAPACKSRCDIR)/SRC/cheevr_2stage.c \
$(LAPACKSRCDIR)/SRC/cheevr.c \
$(LAPACKSRCDIR)/SRC/cheevx_2stage.c \
$(LAPACKSRCDIR)/SRC/cheevx.c \
$(LAPACKSRCDIR)/SRC/chegs2.c \
$(LAPACKSRCDIR)/SRC/chegst.c \
$(LAPACKSRCDIR)/SRC/chegv_2stage.c \
$(LAPACKSRCDIR)/SRC/chegv.c \
$(LAPACKSRCDIR)/SRC/chegvd.c \
$(LAPACKSRCDIR)/SRC/chegvx.c \
$(LAPACKSRCDIR)/SRC/cherfs.c \
$(LAPACKSRCDIR)/SRC/chesv_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/chesv_aa.c \
$(LAPACKSRCDIR)/SRC/chesv.c \
$(LAPACKSRCDIR)/SRC/chesv_rk.c \
$(LAPACKSRCDIR)/SRC/chesv_rook.c \
$(LAPACKSRCDIR)/SRC/chesvx.c \
$(LAPACKSRCDIR)/SRC/chesvxx.c \
$(LAPACKSRCDIR)/SRC/cheswapr.c \
$(LAPACKSRCDIR)/SRC/chetd2.c \
$(LAPACKSRCDIR)/SRC/chetf2.c \
$(LAPACKSRCDIR)/SRC/chetf2_rk.c \
$(LAPACKSRCDIR)/SRC/chetf2_rook.c \
$(LAPACKSRCDIR)/SRC/chetrd_2stage.c \
$(LAPACKSRCDIR)/SRC/chetrd.c \
$(LAPACKSRCDIR)/SRC/chetrd_he2hb.c \
$(LAPACKSRCDIR)/SRC/chetrf_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/chetrf_aa.c \
$(LAPACKSRCDIR)/SRC/chetrf.c \
$(LAPACKSRCDIR)/SRC/chetrf_rk.c \
$(LAPACKSRCDIR)/SRC/chetrf_rook.c \
$(LAPACKSRCDIR)/SRC/chetri2.c \
$(LAPACKSRCDIR)/SRC/chetri2x.c \
$(LAPACKSRCDIR)/SRC/chetri_3.c \
$(LAPACKSRCDIR)/SRC/chetri_3x.c \
$(LAPACKSRCDIR)/SRC/chetri.c \
$(LAPACKSRCDIR)/SRC/chetri_rook.c \
$(LAPACKSRCDIR)/SRC/chetrs2.c \
$(LAPACKSRCDIR)/SRC/chetrs_3.c \
$(LAPACKSRCDIR)/SRC/chetrs_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/chetrs_aa.c \
$(LAPACKSRCDIR)/SRC/chetrs.c \
$(LAPACKSRCDIR)/SRC/chetrs_rook.c \
$(LAPACKSRCDIR)/SRC/chfrk.c \
$(LAPACKSRCDIR)/SRC/chgeqz.c \
$(LAPACKSRCDIR)/SRC/chla_transtype.c \
$(LAPACKSRCDIR)/SRC/chpcon.c \
$(LAPACKSRCDIR)/SRC/chpev.c \
$(LAPACKSRCDIR)/SRC/chpevd.c \
$(LAPACKSRCDIR)/SRC/chpevx.c \
$(LAPACKSRCDIR)/SRC/chpgst.c \
$(LAPACKSRCDIR)/SRC/chpgv.c \
$(LAPACKSRCDIR)/SRC/chpgvd.c \
$(LAPACKSRCDIR)/SRC/chpgvx.c \
$(LAPACKSRCDIR)/SRC/chprfs.c \
$(LAPACKSRCDIR)/SRC/chpsv.c \
$(LAPACKSRCDIR)/SRC/chpsvx.c \
$(LAPACKSRCDIR)/SRC/chptrd.c \
$(LAPACKSRCDIR)/SRC/chptrf.c \
$(LAPACKSRCDIR)/SRC/chptri.c \
$(LAPACKSRCDIR)/SRC/chptrs.c \
$(LAPACKSRCDIR)/SRC/chsein.c \
$(LAPACKSRCDIR)/SRC/chseqr.c \
$(LAPACKSRCDIR)/SRC/clabrd.c \
$(LAPACKSRCDIR)/SRC/clacgv.c \
$(LAPACKSRCDIR)/SRC/clacn2.c \
$(LAPACKSRCDIR)/SRC/clacon.c \
$(LAPACKSRCDIR)/SRC/clacp2.c \
$(LAPACKSRCDIR)/SRC/clacpy.c \
$(LAPACKSRCDIR)/SRC/clacrm.c \
$(LAPACKSRCDIR)/SRC/clacrt.c \
$(LAPACKSRCDIR)/SRC/cladiv.c \
$(LAPACKSRCDIR)/SRC/claed0.c \
$(LAPACKSRCDIR)/SRC/claed7.c \
$(LAPACKSRCDIR)/SRC/claed8.c \
$(LAPACKSRCDIR)/SRC/claein.c \
$(LAPACKSRCDIR)/SRC/claesy.c \
$(LAPACKSRCDIR)/SRC/claev2.c \
$(LAPACKSRCDIR)/SRC/clag2z.c \
$(LAPACKSRCDIR)/SRC/cla_gbamv.c \
$(LAPACKSRCDIR)/SRC/cla_gbrcond_c.c \
$(LAPACKSRCDIR)/SRC/cla_gbrcond_x.c \
$(LAPACKSRCDIR)/SRC/cla_gbrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/cla_gbrpvgrw.c \
$(LAPACKSRCDIR)/SRC/cla_geamv.c \
$(LAPACKSRCDIR)/SRC/cla_gercond_c.c \
$(LAPACKSRCDIR)/SRC/cla_gercond_x.c \
$(LAPACKSRCDIR)/SRC/cla_gerfsx_extended.c \
$(LAPACKSRCDIR)/SRC/cla_gerpvgrw.c \
$(LAPACKSRCDIR)/SRC/clags2.c \
$(LAPACKSRCDIR)/SRC/clagtm.c \
$(LAPACKSRCDIR)/SRC/cla_heamv.c \
$(LAPACKSRCDIR)/SRC/clahef_aa.c \
$(LAPACKSRCDIR)/SRC/clahef.c \
$(LAPACKSRCDIR)/SRC/clahef_rk.c \
$(LAPACKSRCDIR)/SRC/clahef_rook.c \
$(LAPACKSRCDIR)/SRC/cla_hercond_c.c \
$(LAPACKSRCDIR)/SRC/cla_hercond_x.c \
$(LAPACKSRCDIR)/SRC/cla_herfsx_extended.c \
$(LAPACKSRCDIR)/SRC/cla_herpvgrw.c \
$(LAPACKSRCDIR)/SRC/clahqr.c \
$(LAPACKSRCDIR)/SRC/clahr2.c \
$(LAPACKSRCDIR)/SRC/claic1.c \
$(LAPACKSRCDIR)/SRC/cla_lin_berr.c \
$(LAPACKSRCDIR)/SRC/clals0.c \
$(LAPACKSRCDIR)/SRC/clalsa.c \
$(LAPACKSRCDIR)/SRC/clalsd.c \
$(LAPACKSRCDIR)/SRC/clamswlq.c \
$(LAPACKSRCDIR)/SRC/clamtsqr.c \
$(LAPACKSRCDIR)/SRC/clangb.c \
$(LAPACKSRCDIR)/SRC/clange.c \
$(LAPACKSRCDIR)/SRC/clangt.c \
$(LAPACKSRCDIR)/SRC/clanhb.c \
$(LAPACKSRCDIR)/SRC/clanhe.c \
$(LAPACKSRCDIR)/SRC/clanhf.c \
$(LAPACKSRCDIR)/SRC/clanhp.c \
$(LAPACKSRCDIR)/SRC/clanhs.c \
$(LAPACKSRCDIR)/SRC/clanht.c \
$(LAPACKSRCDIR)/SRC/clansb.c \
$(LAPACKSRCDIR)/SRC/clansp.c \
$(LAPACKSRCDIR)/SRC/clansy.c \
$(LAPACKSRCDIR)/SRC/clantb.c \
$(LAPACKSRCDIR)/SRC/clantp.c \
$(LAPACKSRCDIR)/SRC/clantr.c \
$(LAPACKSRCDIR)/SRC/clapll.c \
$(LAPACKSRCDIR)/SRC/clapmr.c \
$(LAPACKSRCDIR)/SRC/clapmt.c \
$(LAPACKSRCDIR)/SRC/cla_porcond_c.c \
$(LAPACKSRCDIR)/SRC/cla_porcond_x.c \
$(LAPACKSRCDIR)/SRC/cla_porfsx_extended.c \
$(LAPACKSRCDIR)/SRC/cla_porpvgrw.c \
$(LAPACKSRCDIR)/SRC/claqgb.c \
$(LAPACKSRCDIR)/SRC/claqge.c \
$(LAPACKSRCDIR)/SRC/claqhb.c \
$(LAPACKSRCDIR)/SRC/claqhe.c \
$(LAPACKSRCDIR)/SRC/claqhp.c \
$(LAPACKSRCDIR)/SRC/claqp2.c \
$(LAPACKSRCDIR)/SRC/claqps.c \
$(LAPACKSRCDIR)/SRC/claqr0.c \
$(LAPACKSRCDIR)/SRC/claqr1.c \
$(LAPACKSRCDIR)/SRC/claqr2.c \
$(LAPACKSRCDIR)/SRC/claqr3.c \
$(LAPACKSRCDIR)/SRC/claqr4.c \
$(LAPACKSRCDIR)/SRC/claqr5.c \
$(LAPACKSRCDIR)/SRC/claqsb.c \
$(LAPACKSRCDIR)/SRC/claqsp.c \
$(LAPACKSRCDIR)/SRC/claqsy.c \
$(LAPACKSRCDIR)/SRC/clar1v.c \
$(LAPACKSRCDIR)/SRC/clar2v.c \
$(LAPACKSRCDIR)/SRC/clarcm.c \
$(LAPACKSRCDIR)/SRC/clarfb.c \
$(LAPACKSRCDIR)/SRC/clarf.c \
$(LAPACKSRCDIR)/SRC/clarfg.c \
$(LAPACKSRCDIR)/SRC/clarfgp.c \
$(LAPACKSRCDIR)/SRC/clarft.c \
$(LAPACKSRCDIR)/SRC/clarfx.c \
$(LAPACKSRCDIR)/SRC/clarfy.c \
$(LAPACKSRCDIR)/SRC/clargv.c \
$(LAPACKSRCDIR)/SRC/clarnv.c \
$(LAPACKSRCDIR)/SRC/clarrv.c \
$(LAPACKSRCDIR)/SRC/clarscl2.c \
$(LAPACKSRCDIR)/SRC/clartg.c \
$(LAPACKSRCDIR)/SRC/clartv.c \
$(LAPACKSRCDIR)/SRC/clarzb.c \
$(LAPACKSRCDIR)/SRC/clarz.c \
$(LAPACKSRCDIR)/SRC/clarzt.c \
$(LAPACKSRCDIR)/SRC/clascl2.c \
$(LAPACKSRCDIR)/SRC/clascl.c \
$(LAPACKSRCDIR)/SRC/claset.c \
$(LAPACKSRCDIR)/SRC/clasr.c \
$(LAPACKSRCDIR)/SRC/classq.c \
$(LAPACKSRCDIR)/SRC/claswlq.c \
$(LAPACKSRCDIR)/SRC/claswp.c \
$(LAPACKSRCDIR)/SRC/cla_syamv.c \
$(LAPACKSRCDIR)/SRC/clasyf_aa.c \
$(LAPACKSRCDIR)/SRC/clasyf.c \
$(LAPACKSRCDIR)/SRC/clasyf_rk.c \
$(LAPACKSRCDIR)/SRC/clasyf_rook.c \
$(LAPACKSRCDIR)/SRC/cla_syrcond_c.c \
$(LAPACKSRCDIR)/SRC/cla_syrcond_x.c \
$(LAPACKSRCDIR)/SRC/cla_syrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/cla_syrpvgrw.c \
$(LAPACKSRCDIR)/SRC/clatbs.c \
$(LAPACKSRCDIR)/SRC/clatdf.c \
$(LAPACKSRCDIR)/SRC/clatps.c \
$(LAPACKSRCDIR)/SRC/clatrd.c \
$(LAPACKSRCDIR)/SRC/clatrs.c \
$(LAPACKSRCDIR)/SRC/clatrz.c \
$(LAPACKSRCDIR)/SRC/clatsqr.c \
$(LAPACKSRCDIR)/SRC/clauu2.c \
$(LAPACKSRCDIR)/SRC/clauum.c \
$(LAPACKSRCDIR)/SRC/cla_wwaddw.c \
$(LAPACKSRCDIR)/SRC/cpbcon.c \
$(LAPACKSRCDIR)/SRC/cpbequ.c \
$(LAPACKSRCDIR)/SRC/cpbrfs.c \
$(LAPACKSRCDIR)/SRC/cpbstf.c \
$(LAPACKSRCDIR)/SRC/cpbsv.c \
$(LAPACKSRCDIR)/SRC/cpbsvx.c \
$(LAPACKSRCDIR)/SRC/cpbtf2.c \
$(LAPACKSRCDIR)/SRC/cpbtrf.c \
$(LAPACKSRCDIR)/SRC/cpbtrs.c \
$(LAPACKSRCDIR)/SRC/cpftrf.c \
$(LAPACKSRCDIR)/SRC/cpftri.c \
$(LAPACKSRCDIR)/SRC/cpftrs.c \
$(LAPACKSRCDIR)/SRC/cpocon.c \
$(LAPACKSRCDIR)/SRC/cpoequb.c \
$(LAPACKSRCDIR)/SRC/cpoequ.c \
$(LAPACKSRCDIR)/SRC/cporfs.c \
$(LAPACKSRCDIR)/SRC/cposv.c \
$(LAPACKSRCDIR)/SRC/cposvx.c \
$(LAPACKSRCDIR)/SRC/cposvxx.c \
$(LAPACKSRCDIR)/SRC/cpotf2.c \
$(LAPACKSRCDIR)/SRC/cpotrf2.c \
$(LAPACKSRCDIR)/SRC/cpotrf.c \
$(LAPACKSRCDIR)/SRC/cpotri.c \
$(LAPACKSRCDIR)/SRC/cpotrs.c \
$(LAPACKSRCDIR)/SRC/cppcon.c \
$(LAPACKSRCDIR)/SRC/cppequ.c \
$(LAPACKSRCDIR)/SRC/cpprfs.c \
$(LAPACKSRCDIR)/SRC/cppsv.c \
$(LAPACKSRCDIR)/SRC/cppsvx.c \
$(LAPACKSRCDIR)/SRC/cpptrf.c \
$(LAPACKSRCDIR)/SRC/cpptri.c \
$(LAPACKSRCDIR)/SRC/cpptrs.c \
$(LAPACKSRCDIR)/SRC/cpstf2.c \
$(LAPACKSRCDIR)/SRC/cpstrf.c \
$(LAPACKSRCDIR)/SRC/cptcon.c \
$(LAPACKSRCDIR)/SRC/cpteqr.c \
$(LAPACKSRCDIR)/SRC/cptrfs.c \
$(LAPACKSRCDIR)/SRC/cptsv.c \
$(LAPACKSRCDIR)/SRC/cptsvx.c \
$(LAPACKSRCDIR)/SRC/cpttrf.c \
$(LAPACKSRCDIR)/SRC/cpttrs.c \
$(LAPACKSRCDIR)/SRC/cptts2.c \
$(LAPACKSRCDIR)/SRC/crot.c \
$(LAPACKSRCDIR)/SRC/cspcon.c \
$(LAPACKSRCDIR)/SRC/cspmv.c \
$(LAPACKSRCDIR)/SRC/cspr.c \
$(LAPACKSRCDIR)/SRC/csprfs.c \
$(LAPACKSRCDIR)/SRC/cspsv.c \
$(LAPACKSRCDIR)/SRC/cspsvx.c \
$(LAPACKSRCDIR)/SRC/csptrf.c \
$(LAPACKSRCDIR)/SRC/csptri.c \
$(LAPACKSRCDIR)/SRC/csptrs.c \
$(LAPACKSRCDIR)/SRC/csrscl.c \
$(LAPACKSRCDIR)/SRC/cstedc.c \
$(LAPACKSRCDIR)/SRC/cstegr.c \
$(LAPACKSRCDIR)/SRC/cstein.c \
$(LAPACKSRCDIR)/SRC/cstemr.c \
$(LAPACKSRCDIR)/SRC/csteqr.c \
$(LAPACKSRCDIR)/SRC/csycon_3.c \
$(LAPACKSRCDIR)/SRC/csycon.c \
$(LAPACKSRCDIR)/SRC/csycon_rook.c \
$(LAPACKSRCDIR)/SRC/csyconv.c \
$(LAPACKSRCDIR)/SRC/csyconvf.c \
$(LAPACKSRCDIR)/SRC/csyconvf_rook.c \
$(LAPACKSRCDIR)/SRC/csyequb.c \
$(LAPACKSRCDIR)/SRC/csymv.c \
$(LAPACKSRCDIR)/SRC/csyr.c \
$(LAPACKSRCDIR)/SRC/csyrfs.c \
$(LAPACKSRCDIR)/SRC/csysv_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/csysv_aa.c \
$(LAPACKSRCDIR)/SRC/csysv.c \
$(LAPACKSRCDIR)/SRC/csysv_rk.c \
$(LAPACKSRCDIR)/SRC/csysv_rook.c \
$(LAPACKSRCDIR)/SRC/csysvx.c \
$(LAPACKSRCDIR)/SRC/csysvxx.c \
$(LAPACKSRCDIR)/SRC/csyswapr.c \
$(LAPACKSRCDIR)/SRC/csytf2.c \
$(LAPACKSRCDIR)/SRC/csytf2_rk.c \
$(LAPACKSRCDIR)/SRC/csytf2_rook.c \
$(LAPACKSRCDIR)/SRC/csytrf_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/csytrf_aa.c \
$(LAPACKSRCDIR)/SRC/csytrf.c \
$(LAPACKSRCDIR)/SRC/csytrf_rk.c \
$(LAPACKSRCDIR)/SRC/csytrf_rook.c \
$(LAPACKSRCDIR)/SRC/csytri2.c \
$(LAPACKSRCDIR)/SRC/csytri2x.c \
$(LAPACKSRCDIR)/SRC/csytri_3.c \
$(LAPACKSRCDIR)/SRC/csytri_3x.c \
$(LAPACKSRCDIR)/SRC/csytri.c \
$(LAPACKSRCDIR)/SRC/csytri_rook.c \
$(LAPACKSRCDIR)/SRC/csytrs2.c \
$(LAPACKSRCDIR)/SRC/csytrs_3.c \
$(LAPACKSRCDIR)/SRC/csytrs_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/csytrs_aa.c \
$(LAPACKSRCDIR)/SRC/csytrs.c \
$(LAPACKSRCDIR)/SRC/csytrs_rook.c \
$(LAPACKSRCDIR)/SRC/ctbcon.c \
$(LAPACKSRCDIR)/SRC/ctbrfs.c \
$(LAPACKSRCDIR)/SRC/ctbtrs.c \
$(LAPACKSRCDIR)/SRC/ctfsm.c \
$(LAPACKSRCDIR)/SRC/ctftri.c \
$(LAPACKSRCDIR)/SRC/ctfttp.c \
$(LAPACKSRCDIR)/SRC/ctfttr.c \
$(LAPACKSRCDIR)/SRC/ctgevc.c \
$(LAPACKSRCDIR)/SRC/ctgex2.c \
$(LAPACKSRCDIR)/SRC/ctgexc.c \
$(LAPACKSRCDIR)/SRC/ctgsen.c \
$(LAPACKSRCDIR)/SRC/ctgsja.c \
$(LAPACKSRCDIR)/SRC/ctgsna.c \
$(LAPACKSRCDIR)/SRC/ctgsy2.c \
$(LAPACKSRCDIR)/SRC/ctgsyl.c \
$(LAPACKSRCDIR)/SRC/ctpcon.c \
$(LAPACKSRCDIR)/SRC/ctplqt2.c \
$(LAPACKSRCDIR)/SRC/ctplqt.c \
$(LAPACKSRCDIR)/SRC/ctpmlqt.c \
$(LAPACKSRCDIR)/SRC/ctpmqrt.c \
$(LAPACKSRCDIR)/SRC/ctpqrt2.c \
$(LAPACKSRCDIR)/SRC/ctpqrt.c \
$(LAPACKSRCDIR)/SRC/ctprfb.c \
$(LAPACKSRCDIR)/SRC/ctprfs.c \
$(LAPACKSRCDIR)/SRC/ctptri.c \
$(LAPACKSRCDIR)/SRC/ctptrs.c \
$(LAPACKSRCDIR)/SRC/ctpttf.c \
$(LAPACKSRCDIR)/SRC/ctpttr.c \
$(LAPACKSRCDIR)/SRC/ctrcon.c \
$(LAPACKSRCDIR)/SRC/ctrevc3.c \
$(LAPACKSRCDIR)/SRC/ctrevc.c \
$(LAPACKSRCDIR)/SRC/ctrexc.c \
$(LAPACKSRCDIR)/SRC/ctrrfs.c \
$(LAPACKSRCDIR)/SRC/ctrsen.c \
$(LAPACKSRCDIR)/SRC/ctrsna.c \
$(LAPACKSRCDIR)/SRC/ctrsyl.c \
$(LAPACKSRCDIR)/SRC/ctrti2.c \
$(LAPACKSRCDIR)/SRC/ctrtri.c \
$(LAPACKSRCDIR)/SRC/ctrtrs.c \
$(LAPACKSRCDIR)/SRC/ctrttf.c \
$(LAPACKSRCDIR)/SRC/ctrttp.c \
$(LAPACKSRCDIR)/SRC/ctzrzf.c \
$(LAPACKSRCDIR)/SRC/cunbdb1.c \
$(LAPACKSRCDIR)/SRC/cunbdb2.c \
$(LAPACKSRCDIR)/SRC/cunbdb3.c \
$(LAPACKSRCDIR)/SRC/cunbdb4.c \
$(LAPACKSRCDIR)/SRC/cunbdb5.c \
$(LAPACKSRCDIR)/SRC/cunbdb6.c \
$(LAPACKSRCDIR)/SRC/cunbdb.c \
$(LAPACKSRCDIR)/SRC/cuncsd2by1.c \
$(LAPACKSRCDIR)/SRC/cuncsd.c \
$(LAPACKSRCDIR)/SRC/cung2l.c \
$(LAPACKSRCDIR)/SRC/cung2r.c \
$(LAPACKSRCDIR)/SRC/cungbr.c \
$(LAPACKSRCDIR)/SRC/cunghr.c \
$(LAPACKSRCDIR)/SRC/cungl2.c \
$(LAPACKSRCDIR)/SRC/cunglq.c \
$(LAPACKSRCDIR)/SRC/cungql.c \
$(LAPACKSRCDIR)/SRC/cungqr.c \
$(LAPACKSRCDIR)/SRC/cungr2.c \
$(LAPACKSRCDIR)/SRC/cungrq.c \
$(LAPACKSRCDIR)/SRC/cungtr.c \
$(LAPACKSRCDIR)/SRC/cunm22.c \
$(LAPACKSRCDIR)/SRC/cunm2l.c \
$(LAPACKSRCDIR)/SRC/cunm2r.c \
$(LAPACKSRCDIR)/SRC/cunmbr.c \
$(LAPACKSRCDIR)/SRC/cunmhr.c \
$(LAPACKSRCDIR)/SRC/cunml2.c \
$(LAPACKSRCDIR)/SRC/cunmlq.c \
$(LAPACKSRCDIR)/SRC/cunmql.c \
$(LAPACKSRCDIR)/SRC/cunmqr.c \
$(LAPACKSRCDIR)/SRC/cunmr2.c \
$(LAPACKSRCDIR)/SRC/cunmr3.c \
$(LAPACKSRCDIR)/SRC/cunmrq.c \
$(LAPACKSRCDIR)/SRC/cunmrz.c \
$(LAPACKSRCDIR)/SRC/cunmtr.c \
$(LAPACKSRCDIR)/SRC/cupgtr.c \
$(LAPACKSRCDIR)/SRC/cupmtr.c \
$(LAPACKSRCDIR)/SRC/dbbcsd.c \
$(LAPACKSRCDIR)/SRC/dbdsdc.c \
$(LAPACKSRCDIR)/SRC/dbdsqr.c \
$(LAPACKSRCDIR)/SRC/ddisna.c \
$(LAPACKSRCDIR)/SRC/dgbbrd.c \
$(LAPACKSRCDIR)/SRC/dgbcon.c \
$(LAPACKSRCDIR)/SRC/dgbequb.c \
$(LAPACKSRCDIR)/SRC/dgbequ.c \
$(LAPACKSRCDIR)/SRC/dgbrfs.c \
$(LAPACKSRCDIR)/SRC/dgbsv.c \
$(LAPACKSRCDIR)/SRC/dgbsvx.c \
$(LAPACKSRCDIR)/SRC/dgbsvxx.c \
$(LAPACKSRCDIR)/SRC/dgbtf2.c \
$(LAPACKSRCDIR)/SRC/dgbtrf.c \
$(LAPACKSRCDIR)/SRC/dgbtrs.c \
$(LAPACKSRCDIR)/SRC/dgebak.c \
$(LAPACKSRCDIR)/SRC/dgebal.c \
$(LAPACKSRCDIR)/SRC/dgebd2.c \
$(LAPACKSRCDIR)/SRC/dgebrd.c \
$(LAPACKSRCDIR)/SRC/dgecon.c \
$(LAPACKSRCDIR)/SRC/dgeequb.c \
$(LAPACKSRCDIR)/SRC/dgeequ.c \
$(LAPACKSRCDIR)/SRC/dgees.c \
$(LAPACKSRCDIR)/SRC/dgeesx.c \
$(LAPACKSRCDIR)/SRC/dgeev.c \
$(LAPACKSRCDIR)/SRC/dgeevx.c \
$(LAPACKSRCDIR)/SRC/dgehd2.c \
$(LAPACKSRCDIR)/SRC/dgehrd.c \
$(LAPACKSRCDIR)/SRC/dgejsv.c \
$(LAPACKSRCDIR)/SRC/dgelq2.c \
$(LAPACKSRCDIR)/SRC/dgelq.c \
$(LAPACKSRCDIR)/SRC/dgelqf.c \
$(LAPACKSRCDIR)/SRC/dgelqt.c \
$(LAPACKSRCDIR)/SRC/dgels.c \
$(LAPACKSRCDIR)/SRC/dgelsd.c \
$(LAPACKSRCDIR)/SRC/dgelss.c \
$(LAPACKSRCDIR)/SRC/dgelsy.c \
$(LAPACKSRCDIR)/SRC/dgemlq.c \
$(LAPACKSRCDIR)/SRC/dgemlqt.c \
$(LAPACKSRCDIR)/SRC/dgemqr.c \
$(LAPACKSRCDIR)/SRC/dgemqrt.c \
$(LAPACKSRCDIR)/SRC/dgeql2.c \
$(LAPACKSRCDIR)/SRC/dgeqlf.c \
$(LAPACKSRCDIR)/SRC/dgeqp3.c \
$(LAPACKSRCDIR)/SRC/dgeqr2.c \
$(LAPACKSRCDIR)/SRC/dgeqr2p.c \
$(LAPACKSRCDIR)/SRC/dgeqr.c \
$(LAPACKSRCDIR)/SRC/dgeqrf.c \
$(LAPACKSRCDIR)/SRC/dgeqrfp.c \
$(LAPACKSRCDIR)/SRC/dgeqrt2.c \
$(LAPACKSRCDIR)/SRC/dgeqrt3.c \
$(LAPACKSRCDIR)/SRC/dgeqrt.c \
$(LAPACKSRCDIR)/SRC/dgerfs.c \
$(LAPACKSRCDIR)/SRC/dgerq2.c \
$(LAPACKSRCDIR)/SRC/dgerqf.c \
$(LAPACKSRCDIR)/SRC/dgesc2.c \
$(LAPACKSRCDIR)/SRC/dgesdd.c \
$(LAPACKSRCDIR)/SRC/dgesv.c \
$(LAPACKSRCDIR)/SRC/dgesvd.c \
$(LAPACKSRCDIR)/SRC/dgesvdx.c \
$(LAPACKSRCDIR)/SRC/dgesvj.c \
$(LAPACKSRCDIR)/SRC/dgesvx.c \
$(LAPACKSRCDIR)/SRC/dgesvxx.c \
$(LAPACKSRCDIR)/SRC/dgetc2.c \
$(LAPACKSRCDIR)/SRC/dgetf2.c \
$(LAPACKSRCDIR)/SRC/dgetrf2.c \
$(LAPACKSRCDIR)/SRC/dgetrf.c \
$(LAPACKSRCDIR)/SRC/dgetri.c \
$(LAPACKSRCDIR)/SRC/dgetrs.c \
$(LAPACKSRCDIR)/SRC/dgetsls.c \
$(LAPACKSRCDIR)/SRC/dggbak.c \
$(LAPACKSRCDIR)/SRC/dggbal.c \
$(LAPACKSRCDIR)/SRC/dgges3.c \
$(LAPACKSRCDIR)/SRC/dgges.c \
$(LAPACKSRCDIR)/SRC/dggesx.c \
$(LAPACKSRCDIR)/SRC/dggev3.c \
$(LAPACKSRCDIR)/SRC/dggev.c \
$(LAPACKSRCDIR)/SRC/dggevx.c \
$(LAPACKSRCDIR)/SRC/dggglm.c \
$(LAPACKSRCDIR)/SRC/dgghd3.c \
$(LAPACKSRCDIR)/SRC/dgghrd.c \
$(LAPACKSRCDIR)/SRC/dgglse.c \
$(LAPACKSRCDIR)/SRC/dggqrf.c \
$(LAPACKSRCDIR)/SRC/dggrqf.c \
$(LAPACKSRCDIR)/SRC/dggsvd3.c \
$(LAPACKSRCDIR)/SRC/dggsvp3.c \
$(LAPACKSRCDIR)/SRC/dgsvj0.c \
$(LAPACKSRCDIR)/SRC/dgsvj1.c \
$(LAPACKSRCDIR)/SRC/dgtcon.c \
$(LAPACKSRCDIR)/SRC/dgtrfs.c \
$(LAPACKSRCDIR)/SRC/dgtsv.c \
$(LAPACKSRCDIR)/SRC/dgtsvx.c \
$(LAPACKSRCDIR)/SRC/dgttrf.c \
$(LAPACKSRCDIR)/SRC/dgttrs.c \
$(LAPACKSRCDIR)/SRC/dgtts2.c \
$(LAPACKSRCDIR)/SRC/dhgeqz.c \
$(LAPACKSRCDIR)/SRC/dhsein.c \
$(LAPACKSRCDIR)/SRC/dhseqr.c \
$(LAPACKSRCDIR)/SRC/disnan.c \
$(LAPACKSRCDIR)/SRC/dlabad.c \
$(LAPACKSRCDIR)/SRC/dlabrd.c \
$(LAPACKSRCDIR)/SRC/dlacn2.c \
$(LAPACKSRCDIR)/SRC/dlacon.c \
$(LAPACKSRCDIR)/SRC/dlacpy.c \
$(LAPACKSRCDIR)/SRC/dladiv.c \
$(LAPACKSRCDIR)/SRC/dlae2.c \
$(LAPACKSRCDIR)/SRC/dlaebz.c \
$(LAPACKSRCDIR)/SRC/dlaed0.c \
$(LAPACKSRCDIR)/SRC/dlaed1.c \
$(LAPACKSRCDIR)/SRC/dlaed2.c \
$(LAPACKSRCDIR)/SRC/dlaed3.c \
$(LAPACKSRCDIR)/SRC/dlaed4.c \
$(LAPACKSRCDIR)/SRC/dlaed5.c \
$(LAPACKSRCDIR)/SRC/dlaed6.c \
$(LAPACKSRCDIR)/SRC/dlaed7.c \
$(LAPACKSRCDIR)/SRC/dlaed8.c \
$(LAPACKSRCDIR)/SRC/dlaed9.c \
$(LAPACKSRCDIR)/SRC/dlaeda.c \
$(LAPACKSRCDIR)/SRC/dlaein.c \
$(LAPACKSRCDIR)/SRC/dlaev2.c \
$(LAPACKSRCDIR)/SRC/dlaexc.c \
$(LAPACKSRCDIR)/SRC/dlag2.c \
$(LAPACKSRCDIR)/SRC/dlag2s.c \
$(LAPACKSRCDIR)/SRC/dla_gbamv.c \
$(LAPACKSRCDIR)/SRC/dla_gbrcond.c \
$(LAPACKSRCDIR)/SRC/dla_gbrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/dla_gbrpvgrw.c \
$(LAPACKSRCDIR)/SRC/dla_geamv.c \
$(LAPACKSRCDIR)/SRC/dla_gercond.c \
$(LAPACKSRCDIR)/SRC/dla_gerfsx_extended.c \
$(LAPACKSRCDIR)/SRC/dla_gerpvgrw.c \
$(LAPACKSRCDIR)/SRC/dlags2.c \
$(LAPACKSRCDIR)/SRC/dlagtf.c \
$(LAPACKSRCDIR)/SRC/dlagtm.c \
$(LAPACKSRCDIR)/SRC/dlagts.c \
$(LAPACKSRCDIR)/SRC/dlagv2.c \
$(LAPACKSRCDIR)/SRC/dlahqr.c \
$(LAPACKSRCDIR)/SRC/dlahr2.c \
$(LAPACKSRCDIR)/SRC/dlaic1.c \
$(LAPACKSRCDIR)/SRC/dlaisnan.c \
$(LAPACKSRCDIR)/SRC/dla_lin_berr.c \
$(LAPACKSRCDIR)/SRC/dlaln2.c \
$(LAPACKSRCDIR)/SRC/dlals0.c \
$(LAPACKSRCDIR)/SRC/dlalsa.c \
$(LAPACKSRCDIR)/SRC/dlalsd.c \
$(LAPACKSRCDIR)/SRC/dlamrg.c \
$(LAPACKSRCDIR)/SRC/dlamswlq.c \
$(LAPACKSRCDIR)/SRC/dlamtsqr.c \
$(LAPACKSRCDIR)/SRC/dlaneg.c \
$(LAPACKSRCDIR)/SRC/dlangb.c \
$(LAPACKSRCDIR)/SRC/dlange.c \
$(LAPACKSRCDIR)/SRC/dlangt.c \
$(LAPACKSRCDIR)/SRC/dlanhs.c \
$(LAPACKSRCDIR)/SRC/dlansb.c \
$(LAPACKSRCDIR)/SRC/dlansf.c \
$(LAPACKSRCDIR)/SRC/dlansp.c \
$(LAPACKSRCDIR)/SRC/dlanst.c \
$(LAPACKSRCDIR)/SRC/dlansy.c \
$(LAPACKSRCDIR)/SRC/dlantb.c \
$(LAPACKSRCDIR)/SRC/dlantp.c \
$(LAPACKSRCDIR)/SRC/dlantr.c \
$(LAPACKSRCDIR)/SRC/dlanv2.c \
$(LAPACKSRCDIR)/SRC/dlapll.c \
$(LAPACKSRCDIR)/SRC/dlapmr.c \
$(LAPACKSRCDIR)/SRC/dlapmt.c \
$(LAPACKSRCDIR)/SRC/dla_porcond.c \
$(LAPACKSRCDIR)/SRC/dla_porfsx_extended.c \
$(LAPACKSRCDIR)/SRC/dla_porpvgrw.c \
$(LAPACKSRCDIR)/SRC/dlapy2.c \
$(LAPACKSRCDIR)/SRC/dlapy3.c \
$(LAPACKSRCDIR)/SRC/dlaqgb.c \
$(LAPACKSRCDIR)/SRC/dlaqge.c \
$(LAPACKSRCDIR)/SRC/dlaqp2.c \
$(LAPACKSRCDIR)/SRC/dlaqps.c \
$(LAPACKSRCDIR)/SRC/dlaqr0.c \
$(LAPACKSRCDIR)/SRC/dlaqr1.c \
$(LAPACKSRCDIR)/SRC/dlaqr2.c \
$(LAPACKSRCDIR)/SRC/dlaqr3.c \
$(LAPACKSRCDIR)/SRC/dlaqr4.c \
$(LAPACKSRCDIR)/SRC/dlaqr5.c \
$(LAPACKSRCDIR)/SRC/dlaqsb.c \
$(LAPACKSRCDIR)/SRC/dlaqsp.c \
$(LAPACKSRCDIR)/SRC/dlaqsy.c \
$(LAPACKSRCDIR)/SRC/dlaqtr.c \
$(LAPACKSRCDIR)/SRC/dlar1v.c \
$(LAPACKSRCDIR)/SRC/dlar2v.c \
$(LAPACKSRCDIR)/SRC/dlarfb.c \
$(LAPACKSRCDIR)/SRC/dlarf.c \
$(LAPACKSRCDIR)/SRC/dlarfg.c \
$(LAPACKSRCDIR)/SRC/dlarfgp.c \
$(LAPACKSRCDIR)/SRC/dlarft.c \
$(LAPACKSRCDIR)/SRC/dlarfx.c \
$(LAPACKSRCDIR)/SRC/dlarfy.c \
$(LAPACKSRCDIR)/SRC/dlargv.c \
$(LAPACKSRCDIR)/SRC/dlarnv.c \
$(LAPACKSRCDIR)/SRC/dlarra.c \
$(LAPACKSRCDIR)/SRC/dlarrb.c \
$(LAPACKSRCDIR)/SRC/dlarrc.c \
$(LAPACKSRCDIR)/SRC/dlarrd.c \
$(LAPACKSRCDIR)/SRC/dlarre.c \
$(LAPACKSRCDIR)/SRC/dlarrf.c \
$(LAPACKSRCDIR)/SRC/dlarrj.c \
$(LAPACKSRCDIR)/SRC/dlarrk.c \
$(LAPACKSRCDIR)/SRC/dlarrr.c \
$(LAPACKSRCDIR)/SRC/dlarrv.c \
$(LAPACKSRCDIR)/SRC/dlarscl2.c \
$(LAPACKSRCDIR)/SRC/dlartg.c \
$(LAPACKSRCDIR)/SRC/dlartgp.c \
$(LAPACKSRCDIR)/SRC/dlartgs.c \
$(LAPACKSRCDIR)/SRC/dlartv.c \
$(LAPACKSRCDIR)/SRC/dlaruv.c \
$(LAPACKSRCDIR)/SRC/dlarzb.c \
$(LAPACKSRCDIR)/SRC/dlarz.c \
$(LAPACKSRCDIR)/SRC/dlarzt.c \
$(LAPACKSRCDIR)/SRC/dlas2.c \
$(LAPACKSRCDIR)/SRC/dlascl2.c \
$(LAPACKSRCDIR)/SRC/dlascl.c \
$(LAPACKSRCDIR)/SRC/dlasd0.c \
$(LAPACKSRCDIR)/SRC/dlasd1.c \
$(LAPACKSRCDIR)/SRC/dlasd2.c \
$(LAPACKSRCDIR)/SRC/dlasd3.c \
$(LAPACKSRCDIR)/SRC/dlasd4.c \
$(LAPACKSRCDIR)/SRC/dlasd5.c \
$(LAPACKSRCDIR)/SRC/dlasd6.c \
$(LAPACKSRCDIR)/SRC/dlasd7.c \
$(LAPACKSRCDIR)/SRC/dlasd8.c \
$(LAPACKSRCDIR)/SRC/dlasda.c \
$(LAPACKSRCDIR)/SRC/dlasdq.c \
$(LAPACKSRCDIR)/SRC/dlasdt.c \
$(LAPACKSRCDIR)/SRC/dlaset.c \
$(LAPACKSRCDIR)/SRC/dlasq1.c \
$(LAPACKSRCDIR)/SRC/dlasq2.c \
$(LAPACKSRCDIR)/SRC/dlasq3.c \
$(LAPACKSRCDIR)/SRC/dlasq4.c \
$(LAPACKSRCDIR)/SRC/dlasq5.c \
$(LAPACKSRCDIR)/SRC/dlasq6.c \
$(LAPACKSRCDIR)/SRC/dlasr.c \
$(LAPACKSRCDIR)/SRC/dlasrt.c \
$(LAPACKSRCDIR)/SRC/dlassq.c \
$(LAPACKSRCDIR)/SRC/dlasv2.c \
$(LAPACKSRCDIR)/SRC/dlaswlq.c \
$(LAPACKSRCDIR)/SRC/dlaswp.c \
$(LAPACKSRCDIR)/SRC/dlasy2.c \
$(LAPACKSRCDIR)/SRC/dla_syamv.c \
$(LAPACKSRCDIR)/SRC/dlasyf_aa.c \
$(LAPACKSRCDIR)/SRC/dlasyf.c \
$(LAPACKSRCDIR)/SRC/dlasyf_rk.c \
$(LAPACKSRCDIR)/SRC/dlasyf_rook.c \
$(LAPACKSRCDIR)/SRC/dla_syrcond.c \
$(LAPACKSRCDIR)/SRC/dla_syrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/dla_syrpvgrw.c \
$(LAPACKSRCDIR)/SRC/dlat2s.c \
$(LAPACKSRCDIR)/SRC/dlatbs.c \
$(LAPACKSRCDIR)/SRC/dlatdf.c \
$(LAPACKSRCDIR)/SRC/dlatps.c \
$(LAPACKSRCDIR)/SRC/dlatrd.c \
$(LAPACKSRCDIR)/SRC/dlatrs.c \
$(LAPACKSRCDIR)/SRC/dlatrz.c \
$(LAPACKSRCDIR)/SRC/dlatsqr.c \
$(LAPACKSRCDIR)/SRC/dlauu2.c \
$(LAPACKSRCDIR)/SRC/dlauum.c \
$(LAPACKSRCDIR)/SRC/dla_wwaddw.c \
$(LAPACKSRCDIR)/SRC/dopgtr.c \
$(LAPACKSRCDIR)/SRC/dopmtr.c \
$(LAPACKSRCDIR)/SRC/dorbdb1.c \
$(LAPACKSRCDIR)/SRC/dorbdb2.c \
$(LAPACKSRCDIR)/SRC/dorbdb3.c \
$(LAPACKSRCDIR)/SRC/dorbdb4.c \
$(LAPACKSRCDIR)/SRC/dorbdb5.c \
$(LAPACKSRCDIR)/SRC/dorbdb6.c \
$(LAPACKSRCDIR)/SRC/dorbdb.c \
$(LAPACKSRCDIR)/SRC/dorcsd2by1.c \
$(LAPACKSRCDIR)/SRC/dorcsd.c \
$(LAPACKSRCDIR)/SRC/dorg2l.c \
$(LAPACKSRCDIR)/SRC/dorg2r.c \
$(LAPACKSRCDIR)/SRC/dorgbr.c \
$(LAPACKSRCDIR)/SRC/dorghr.c \
$(LAPACKSRCDIR)/SRC/dorgl2.c \
$(LAPACKSRCDIR)/SRC/dorglq.c \
$(LAPACKSRCDIR)/SRC/dorgql.c \
$(LAPACKSRCDIR)/SRC/dorgqr.c \
$(LAPACKSRCDIR)/SRC/dorgr2.c \
$(LAPACKSRCDIR)/SRC/dorgrq.c \
$(LAPACKSRCDIR)/SRC/dorgtr.c \
$(LAPACKSRCDIR)/SRC/dorm22.c \
$(LAPACKSRCDIR)/SRC/dorm2l.c \
$(LAPACKSRCDIR)/SRC/dorm2r.c \
$(LAPACKSRCDIR)/SRC/dormbr.c \
$(LAPACKSRCDIR)/SRC/dormhr.c \
$(LAPACKSRCDIR)/SRC/dorml2.c \
$(LAPACKSRCDIR)/SRC/dormlq.c \
$(LAPACKSRCDIR)/SRC/dormql.c \
$(LAPACKSRCDIR)/SRC/dormqr.c \
$(LAPACKSRCDIR)/SRC/dormr2.c \
$(LAPACKSRCDIR)/SRC/dormr3.c \
$(LAPACKSRCDIR)/SRC/dormrq.c \
$(LAPACKSRCDIR)/SRC/dormrz.c \
$(LAPACKSRCDIR)/SRC/dormtr.c \
$(LAPACKSRCDIR)/SRC/dpbcon.c \
$(LAPACKSRCDIR)/SRC/dpbequ.c \
$(LAPACKSRCDIR)/SRC/dpbrfs.c \
$(LAPACKSRCDIR)/SRC/dpbstf.c \
$(LAPACKSRCDIR)/SRC/dpbsv.c \
$(LAPACKSRCDIR)/SRC/dpbsvx.c \
$(LAPACKSRCDIR)/SRC/dpbtf2.c \
$(LAPACKSRCDIR)/SRC/dpbtrf.c \
$(LAPACKSRCDIR)/SRC/dpbtrs.c \
$(LAPACKSRCDIR)/SRC/dpftrf.c \
$(LAPACKSRCDIR)/SRC/dpftri.c \
$(LAPACKSRCDIR)/SRC/dpftrs.c \
$(LAPACKSRCDIR)/SRC/dpocon.c \
$(LAPACKSRCDIR)/SRC/dpoequb.c \
$(LAPACKSRCDIR)/SRC/dpoequ.c \
$(LAPACKSRCDIR)/SRC/dporfs.c \
$(LAPACKSRCDIR)/SRC/dposv.c \
$(LAPACKSRCDIR)/SRC/dposvx.c \
$(LAPACKSRCDIR)/SRC/dposvxx.c \
$(LAPACKSRCDIR)/SRC/dpotf2.c \
$(LAPACKSRCDIR)/SRC/dpotrf2.c \
$(LAPACKSRCDIR)/SRC/dpotrf.c \
$(LAPACKSRCDIR)/SRC/dpotri.c \
$(LAPACKSRCDIR)/SRC/dpotrs.c \
$(LAPACKSRCDIR)/SRC/dppcon.c \
$(LAPACKSRCDIR)/SRC/dppequ.c \
$(LAPACKSRCDIR)/SRC/dpprfs.c \
$(LAPACKSRCDIR)/SRC/dppsv.c \
$(LAPACKSRCDIR)/SRC/dppsvx.c \
$(LAPACKSRCDIR)/SRC/dpptrf.c \
$(LAPACKSRCDIR)/SRC/dpptri.c \
$(LAPACKSRCDIR)/SRC/dpptrs.c \
$(LAPACKSRCDIR)/SRC/dpstf2.c \
$(LAPACKSRCDIR)/SRC/dpstrf.c \
$(LAPACKSRCDIR)/SRC/dptcon.c \
$(LAPACKSRCDIR)/SRC/dpteqr.c \
$(LAPACKSRCDIR)/SRC/dptrfs.c \
$(LAPACKSRCDIR)/SRC/dptsv.c \
$(LAPACKSRCDIR)/SRC/dptsvx.c \
$(LAPACKSRCDIR)/SRC/dpttrf.c \
$(LAPACKSRCDIR)/SRC/dpttrs.c \
$(LAPACKSRCDIR)/SRC/dptts2.c \
$(LAPACKSRCDIR)/SRC/drscl.c \
$(LAPACKSRCDIR)/SRC/dsb2st_kernels.c \
$(LAPACKSRCDIR)/SRC/dsbev_2stage.c \
$(LAPACKSRCDIR)/SRC/dsbev.c \
$(LAPACKSRCDIR)/SRC/dsbevd_2stage.c \
$(LAPACKSRCDIR)/SRC/dsbevd.c \
$(LAPACKSRCDIR)/SRC/dsbevx_2stage.c \
$(LAPACKSRCDIR)/SRC/dsbevx.c \
$(LAPACKSRCDIR)/SRC/dsbgst.c \
$(LAPACKSRCDIR)/SRC/dsbgv.c \
$(LAPACKSRCDIR)/SRC/dsbgvd.c \
$(LAPACKSRCDIR)/SRC/dsbgvx.c \
$(LAPACKSRCDIR)/SRC/dsbtrd.c \
$(LAPACKSRCDIR)/SRC/dsfrk.c \
$(LAPACKSRCDIR)/SRC/dsgesv.c \
$(LAPACKSRCDIR)/SRC/dspcon.c \
$(LAPACKSRCDIR)/SRC/dspev.c \
$(LAPACKSRCDIR)/SRC/dspevd.c \
$(LAPACKSRCDIR)/SRC/dspevx.c \
$(LAPACKSRCDIR)/SRC/dspgst.c \
$(LAPACKSRCDIR)/SRC/dspgv.c \
$(LAPACKSRCDIR)/SRC/dspgvd.c \
$(LAPACKSRCDIR)/SRC/dspgvx.c \
$(LAPACKSRCDIR)/SRC/dsposv.c \
$(LAPACKSRCDIR)/SRC/dsprfs.c \
$(LAPACKSRCDIR)/SRC/dspsv.c \
$(LAPACKSRCDIR)/SRC/dspsvx.c \
$(LAPACKSRCDIR)/SRC/dsptrd.c \
$(LAPACKSRCDIR)/SRC/dsptrf.c \
$(LAPACKSRCDIR)/SRC/dsptri.c \
$(LAPACKSRCDIR)/SRC/dsptrs.c \
$(LAPACKSRCDIR)/SRC/dstebz.c \
$(LAPACKSRCDIR)/SRC/dstedc.c \
$(LAPACKSRCDIR)/SRC/dstegr.c \
$(LAPACKSRCDIR)/SRC/dstein.c \
$(LAPACKSRCDIR)/SRC/dstemr.c \
$(LAPACKSRCDIR)/SRC/dsteqr.c \
$(LAPACKSRCDIR)/SRC/dsterf.c \
$(LAPACKSRCDIR)/SRC/dstev.c \
$(LAPACKSRCDIR)/SRC/dstevd.c \
$(LAPACKSRCDIR)/SRC/dstevr.c \
$(LAPACKSRCDIR)/SRC/dstevx.c \
$(LAPACKSRCDIR)/SRC/dsycon_3.c \
$(LAPACKSRCDIR)/SRC/dsycon.c \
$(LAPACKSRCDIR)/SRC/dsycon_rook.c \
$(LAPACKSRCDIR)/SRC/dsyconv.c \
$(LAPACKSRCDIR)/SRC/dsyconvf.c \
$(LAPACKSRCDIR)/SRC/dsyconvf_rook.c \
$(LAPACKSRCDIR)/SRC/dsyequb.c \
$(LAPACKSRCDIR)/SRC/dsyev_2stage.c \
$(LAPACKSRCDIR)/SRC/dsyev.c \
$(LAPACKSRCDIR)/SRC/dsyevd_2stage.c \
$(LAPACKSRCDIR)/SRC/dsyevd.c \
$(LAPACKSRCDIR)/SRC/dsyevr_2stage.c \
$(LAPACKSRCDIR)/SRC/dsyevr.c \
$(LAPACKSRCDIR)/SRC/dsyevx_2stage.c \
$(LAPACKSRCDIR)/SRC/dsyevx.c \
$(LAPACKSRCDIR)/SRC/dsygs2.c \
$(LAPACKSRCDIR)/SRC/dsygst.c \
$(LAPACKSRCDIR)/SRC/dsygv_2stage.c \
$(LAPACKSRCDIR)/SRC/dsygv.c \
$(LAPACKSRCDIR)/SRC/dsygvd.c \
$(LAPACKSRCDIR)/SRC/dsygvx.c \
$(LAPACKSRCDIR)/SRC/dsyrfs.c \
$(LAPACKSRCDIR)/SRC/dsysv_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/dsysv_aa.c \
$(LAPACKSRCDIR)/SRC/dsysv.c \
$(LAPACKSRCDIR)/SRC/dsysv_rk.c \
$(LAPACKSRCDIR)/SRC/dsysv_rook.c \
$(LAPACKSRCDIR)/SRC/dsysvx.c \
$(LAPACKSRCDIR)/SRC/dsysvxx.c \
$(LAPACKSRCDIR)/SRC/dsyswapr.c \
$(LAPACKSRCDIR)/SRC/dsytd2.c \
$(LAPACKSRCDIR)/SRC/dsytf2.c \
$(LAPACKSRCDIR)/SRC/dsytf2_rk.c \
$(LAPACKSRCDIR)/SRC/dsytf2_rook.c \
$(LAPACKSRCDIR)/SRC/dsytrd_2stage.c \
$(LAPACKSRCDIR)/SRC/dsytrd.c \
$(LAPACKSRCDIR)/SRC/dsytrd_sy2sb.c \
$(LAPACKSRCDIR)/SRC/dsytrf_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/dsytrf_aa.c \
$(LAPACKSRCDIR)/SRC/dsytrf.c \
$(LAPACKSRCDIR)/SRC/dsytrf_rk.c \
$(LAPACKSRCDIR)/SRC/dsytrf_rook.c \
$(LAPACKSRCDIR)/SRC/dsytri2.c \
$(LAPACKSRCDIR)/SRC/dsytri2x.c \
$(LAPACKSRCDIR)/SRC/dsytri_3.c \
$(LAPACKSRCDIR)/SRC/dsytri_3x.c \
$(LAPACKSRCDIR)/SRC/dsytri.c \
$(LAPACKSRCDIR)/SRC/dsytri_rook.c \
$(LAPACKSRCDIR)/SRC/dsytrs2.c \
$(LAPACKSRCDIR)/SRC/dsytrs_3.c \
$(LAPACKSRCDIR)/SRC/dsytrs_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/dsytrs_aa.c \
$(LAPACKSRCDIR)/SRC/dsytrs.c \
$(LAPACKSRCDIR)/SRC/dsytrs_rook.c \
$(LAPACKSRCDIR)/SRC/dtbcon.c \
$(LAPACKSRCDIR)/SRC/dtbrfs.c \
$(LAPACKSRCDIR)/SRC/dtbtrs.c \
$(LAPACKSRCDIR)/SRC/dtfsm.c \
$(LAPACKSRCDIR)/SRC/dtftri.c \
$(LAPACKSRCDIR)/SRC/dtfttp.c \
$(LAPACKSRCDIR)/SRC/dtfttr.c \
$(LAPACKSRCDIR)/SRC/dtgevc.c \
$(LAPACKSRCDIR)/SRC/dtgex2.c \
$(LAPACKSRCDIR)/SRC/dtgexc.c \
$(LAPACKSRCDIR)/SRC/dtgsen.c \
$(LAPACKSRCDIR)/SRC/dtgsja.c \
$(LAPACKSRCDIR)/SRC/dtgsna.c \
$(LAPACKSRCDIR)/SRC/dtgsy2.c \
$(LAPACKSRCDIR)/SRC/dtgsyl.c \
$(LAPACKSRCDIR)/SRC/dtpcon.c \
$(LAPACKSRCDIR)/SRC/dtplqt2.c \
$(LAPACKSRCDIR)/SRC/dtplqt.c \
$(LAPACKSRCDIR)/SRC/dtpmlqt.c \
$(LAPACKSRCDIR)/SRC/dtpmqrt.c \
$(LAPACKSRCDIR)/SRC/dtpqrt2.c \
$(LAPACKSRCDIR)/SRC/dtpqrt.c \
$(LAPACKSRCDIR)/SRC/dtprfb.c \
$(LAPACKSRCDIR)/SRC/dtprfs.c \
$(LAPACKSRCDIR)/SRC/dtptri.c \
$(LAPACKSRCDIR)/SRC/dtptrs.c \
$(LAPACKSRCDIR)/SRC/dtpttf.c \
$(LAPACKSRCDIR)/SRC/dtpttr.c \
$(LAPACKSRCDIR)/SRC/dtrcon.c \
$(LAPACKSRCDIR)/SRC/dtrevc3.c \
$(LAPACKSRCDIR)/SRC/dtrevc.c \
$(LAPACKSRCDIR)/SRC/dtrexc.c \
$(LAPACKSRCDIR)/SRC/dtrrfs.c \
$(LAPACKSRCDIR)/SRC/dtrsen.c \
$(LAPACKSRCDIR)/SRC/dtrsna.c \
$(LAPACKSRCDIR)/SRC/dtrsyl.c \
$(LAPACKSRCDIR)/SRC/dtrti2.c \
$(LAPACKSRCDIR)/SRC/dtrtri.c \
$(LAPACKSRCDIR)/SRC/dtrtrs.c \
$(LAPACKSRCDIR)/SRC/dtrttf.c \
$(LAPACKSRCDIR)/SRC/dtrttp.c \
$(LAPACKSRCDIR)/SRC/dtzrzf.c \
$(LAPACKSRCDIR)/SRC/dzsum1.c \
$(LAPACKSRCDIR)/SRC/icmax1.c \
$(LAPACKSRCDIR)/SRC/ieeeck.c \
$(LAPACKSRCDIR)/SRC/ilaclc.c \
$(LAPACKSRCDIR)/SRC/ilaclr.c \
$(LAPACKSRCDIR)/SRC/iladiag.c \
$(LAPACKSRCDIR)/SRC/iladlc.c \
$(LAPACKSRCDIR)/SRC/iladlr.c \
$(LAPACKSRCDIR)/SRC/ilaenv2stage.c \
$(LAPACKSRCDIR)/SRC/ilaenv.c \
$(LAPACKSRCDIR)/SRC/ilaprec.c \
$(LAPACKSRCDIR)/SRC/ilaslc.c \
$(LAPACKSRCDIR)/SRC/ilaslr.c \
$(LAPACKSRCDIR)/SRC/ilatrans.c \
$(LAPACKSRCDIR)/SRC/ilauplo.c \
$(LAPACKSRCDIR)/SRC/ilazlc.c \
$(LAPACKSRCDIR)/SRC/ilazlr.c \
$(LAPACKSRCDIR)/SRC/iparmq.c \
$(LAPACKSRCDIR)/SRC/izmax1.c \
$(LAPACKSRCDIR)/SRC/lsamen.c \
$(LAPACKSRCDIR)/SRC/sbbcsd.c \
$(LAPACKSRCDIR)/SRC/sbdsdc.c \
$(LAPACKSRCDIR)/SRC/sbdsqr.c \
$(LAPACKSRCDIR)/SRC/scsum1.c \
$(LAPACKSRCDIR)/SRC/sdisna.c \
$(LAPACKSRCDIR)/SRC/sgbbrd.c \
$(LAPACKSRCDIR)/SRC/sgbcon.c \
$(LAPACKSRCDIR)/SRC/sgbequb.c \
$(LAPACKSRCDIR)/SRC/sgbequ.c \
$(LAPACKSRCDIR)/SRC/sgbrfs.c \
$(LAPACKSRCDIR)/SRC/sgbsv.c \
$(LAPACKSRCDIR)/SRC/sgbsvx.c \
$(LAPACKSRCDIR)/SRC/sgbsvxx.c \
$(LAPACKSRCDIR)/SRC/sgbtf2.c \
$(LAPACKSRCDIR)/SRC/sgbtrf.c \
$(LAPACKSRCDIR)/SRC/sgbtrs.c \
$(LAPACKSRCDIR)/SRC/sgebak.c \
$(LAPACKSRCDIR)/SRC/sgebal.c \
$(LAPACKSRCDIR)/SRC/sgebd2.c \
$(LAPACKSRCDIR)/SRC/sgebrd.c \
$(LAPACKSRCDIR)/SRC/sgecon.c \
$(LAPACKSRCDIR)/SRC/sgeequb.c \
$(LAPACKSRCDIR)/SRC/sgeequ.c \
$(LAPACKSRCDIR)/SRC/sgees.c \
$(LAPACKSRCDIR)/SRC/sgeesx.c \
$(LAPACKSRCDIR)/SRC/sgeev.c \
$(LAPACKSRCDIR)/SRC/sgeevx.c \
$(LAPACKSRCDIR)/SRC/sgehd2.c \
$(LAPACKSRCDIR)/SRC/sgehrd.c \
$(LAPACKSRCDIR)/SRC/sgejsv.c \
$(LAPACKSRCDIR)/SRC/sgelq2.c \
$(LAPACKSRCDIR)/SRC/sgelq.c \
$(LAPACKSRCDIR)/SRC/sgelqf.c \
$(LAPACKSRCDIR)/SRC/sgelqt.c \
$(LAPACKSRCDIR)/SRC/sgels.c \
$(LAPACKSRCDIR)/SRC/sgelsd.c \
$(LAPACKSRCDIR)/SRC/sgelss.c \
$(LAPACKSRCDIR)/SRC/sgelsy.c \
$(LAPACKSRCDIR)/SRC/sgemlq.c \
$(LAPACKSRCDIR)/SRC/sgemlqt.c \
$(LAPACKSRCDIR)/SRC/sgemqr.c \
$(LAPACKSRCDIR)/SRC/sgemqrt.c \
$(LAPACKSRCDIR)/SRC/sgeql2.c \
$(LAPACKSRCDIR)/SRC/sgeqlf.c \
$(LAPACKSRCDIR)/SRC/sgeqp3.c \
$(LAPACKSRCDIR)/SRC/sgeqr2.c \
$(LAPACKSRCDIR)/SRC/sgeqr2p.c \
$(LAPACKSRCDIR)/SRC/sgeqr.c \
$(LAPACKSRCDIR)/SRC/sgeqrf.c \
$(LAPACKSRCDIR)/SRC/sgeqrfp.c \
$(LAPACKSRCDIR)/SRC/sgeqrt2.c \
$(LAPACKSRCDIR)/SRC/sgeqrt3.c \
$(LAPACKSRCDIR)/SRC/sgeqrt.c \
$(LAPACKSRCDIR)/SRC/sgerfs.c \
$(LAPACKSRCDIR)/SRC/sgerq2.c \
$(LAPACKSRCDIR)/SRC/sgerqf.c \
$(LAPACKSRCDIR)/SRC/sgesc2.c \
$(LAPACKSRCDIR)/SRC/sgesdd.c \
$(LAPACKSRCDIR)/SRC/sgesv.c \
$(LAPACKSRCDIR)/SRC/sgesvd.c \
$(LAPACKSRCDIR)/SRC/sgesvdx.c \
$(LAPACKSRCDIR)/SRC/sgesvj.c \
$(LAPACKSRCDIR)/SRC/sgesvx.c \
$(LAPACKSRCDIR)/SRC/sgesvxx.c \
$(LAPACKSRCDIR)/SRC/sgetc2.c \
$(LAPACKSRCDIR)/SRC/sgetf2.c \
$(LAPACKSRCDIR)/SRC/sgetrf2.c \
$(LAPACKSRCDIR)/SRC/sgetrf.c \
$(LAPACKSRCDIR)/SRC/sgetri.c \
$(LAPACKSRCDIR)/SRC/sgetrs.c \
$(LAPACKSRCDIR)/SRC/sgetsls.c \
$(LAPACKSRCDIR)/SRC/sggbak.c \
$(LAPACKSRCDIR)/SRC/sggbal.c \
$(LAPACKSRCDIR)/SRC/sgges3.c \
$(LAPACKSRCDIR)/SRC/sgges.c \
$(LAPACKSRCDIR)/SRC/sggesx.c \
$(LAPACKSRCDIR)/SRC/sggev3.c \
$(LAPACKSRCDIR)/SRC/sggev.c \
$(LAPACKSRCDIR)/SRC/sggevx.c \
$(LAPACKSRCDIR)/SRC/sggglm.c \
$(LAPACKSRCDIR)/SRC/sgghd3.c \
$(LAPACKSRCDIR)/SRC/sgghrd.c \
$(LAPACKSRCDIR)/SRC/sgglse.c \
$(LAPACKSRCDIR)/SRC/sggqrf.c \
$(LAPACKSRCDIR)/SRC/sggrqf.c \
$(LAPACKSRCDIR)/SRC/sggsvd3.c \
$(LAPACKSRCDIR)/SRC/sggsvp3.c \
$(LAPACKSRCDIR)/SRC/sgsvj0.c \
$(LAPACKSRCDIR)/SRC/sgsvj1.c \
$(LAPACKSRCDIR)/SRC/sgtcon.c \
$(LAPACKSRCDIR)/SRC/sgtrfs.c \
$(LAPACKSRCDIR)/SRC/sgtsv.c \
$(LAPACKSRCDIR)/SRC/sgtsvx.c \
$(LAPACKSRCDIR)/SRC/sgttrf.c \
$(LAPACKSRCDIR)/SRC/sgttrs.c \
$(LAPACKSRCDIR)/SRC/sgtts2.c \
$(LAPACKSRCDIR)/SRC/shgeqz.c \
$(LAPACKSRCDIR)/SRC/shsein.c \
$(LAPACKSRCDIR)/SRC/shseqr.c \
$(LAPACKSRCDIR)/SRC/sisnan.c \
$(LAPACKSRCDIR)/SRC/slabad.c \
$(LAPACKSRCDIR)/SRC/slabrd.c \
$(LAPACKSRCDIR)/SRC/slacn2.c \
$(LAPACKSRCDIR)/SRC/slacon.c \
$(LAPACKSRCDIR)/SRC/slacpy.c \
$(LAPACKSRCDIR)/SRC/sladiv.c \
$(LAPACKSRCDIR)/SRC/slae2.c \
$(LAPACKSRCDIR)/SRC/slaebz.c \
$(LAPACKSRCDIR)/SRC/slaed0.c \
$(LAPACKSRCDIR)/SRC/slaed1.c \
$(LAPACKSRCDIR)/SRC/slaed2.c \
$(LAPACKSRCDIR)/SRC/slaed3.c \
$(LAPACKSRCDIR)/SRC/slaed4.c \
$(LAPACKSRCDIR)/SRC/slaed5.c \
$(LAPACKSRCDIR)/SRC/slaed6.c \
$(LAPACKSRCDIR)/SRC/slaed7.c \
$(LAPACKSRCDIR)/SRC/slaed8.c \
$(LAPACKSRCDIR)/SRC/slaed9.c \
$(LAPACKSRCDIR)/SRC/slaeda.c \
$(LAPACKSRCDIR)/SRC/slaein.c \
$(LAPACKSRCDIR)/SRC/slaev2.c \
$(LAPACKSRCDIR)/SRC/slaexc.c \
$(LAPACKSRCDIR)/SRC/slag2.c \
$(LAPACKSRCDIR)/SRC/slag2d.c \
$(LAPACKSRCDIR)/SRC/sla_gbamv.c \
$(LAPACKSRCDIR)/SRC/sla_gbrcond.c \
$(LAPACKSRCDIR)/SRC/sla_gbrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/sla_gbrpvgrw.c \
$(LAPACKSRCDIR)/SRC/sla_geamv.c \
$(LAPACKSRCDIR)/SRC/sla_gercond.c \
$(LAPACKSRCDIR)/SRC/sla_gerfsx_extended.c \
$(LAPACKSRCDIR)/SRC/sla_gerpvgrw.c \
$(LAPACKSRCDIR)/SRC/slags2.c \
$(LAPACKSRCDIR)/SRC/slagtf.c \
$(LAPACKSRCDIR)/SRC/slagtm.c \
$(LAPACKSRCDIR)/SRC/slagts.c \
$(LAPACKSRCDIR)/SRC/slagv2.c \
$(LAPACKSRCDIR)/SRC/slahqr.c \
$(LAPACKSRCDIR)/SRC/slahr2.c \
$(LAPACKSRCDIR)/SRC/slaic1.c \
$(LAPACKSRCDIR)/SRC/slaisnan.c \
$(LAPACKSRCDIR)/SRC/sla_lin_berr.c \
$(LAPACKSRCDIR)/SRC/slaln2.c \
$(LAPACKSRCDIR)/SRC/slals0.c \
$(LAPACKSRCDIR)/SRC/slalsa.c \
$(LAPACKSRCDIR)/SRC/slalsd.c \
$(LAPACKSRCDIR)/SRC/slamrg.c \
$(LAPACKSRCDIR)/SRC/slamswlq.c \
$(LAPACKSRCDIR)/SRC/slamtsqr.c \
$(LAPACKSRCDIR)/SRC/slaneg.c \
$(LAPACKSRCDIR)/SRC/slangb.c \
$(LAPACKSRCDIR)/SRC/slange.c \
$(LAPACKSRCDIR)/SRC/slangt.c \
$(LAPACKSRCDIR)/SRC/slanhs.c \
$(LAPACKSRCDIR)/SRC/slansb.c \
$(LAPACKSRCDIR)/SRC/slansf.c \
$(LAPACKSRCDIR)/SRC/slansp.c \
$(LAPACKSRCDIR)/SRC/slanst.c \
$(LAPACKSRCDIR)/SRC/slansy.c \
$(LAPACKSRCDIR)/SRC/slantb.c \
$(LAPACKSRCDIR)/SRC/slantp.c \
$(LAPACKSRCDIR)/SRC/slantr.c \
$(LAPACKSRCDIR)/SRC/slanv2.c \
$(LAPACKSRCDIR)/SRC/slapll.c \
$(LAPACKSRCDIR)/SRC/slapmr.c \
$(LAPACKSRCDIR)/SRC/slapmt.c \
$(LAPACKSRCDIR)/SRC/sla_porcond.c \
$(LAPACKSRCDIR)/SRC/sla_porfsx_extended.c \
$(LAPACKSRCDIR)/SRC/sla_porpvgrw.c \
$(LAPACKSRCDIR)/SRC/slapy2.c \
$(LAPACKSRCDIR)/SRC/slapy3.c \
$(LAPACKSRCDIR)/SRC/slaqgb.c \
$(LAPACKSRCDIR)/SRC/slaqge.c \
$(LAPACKSRCDIR)/SRC/slaqp2.c \
$(LAPACKSRCDIR)/SRC/slaqps.c \
$(LAPACKSRCDIR)/SRC/slaqr0.c \
$(LAPACKSRCDIR)/SRC/slaqr1.c \
$(LAPACKSRCDIR)/SRC/slaqr2.c \
$(LAPACKSRCDIR)/SRC/slaqr3.c \
$(LAPACKSRCDIR)/SRC/slaqr4.c \
$(LAPACKSRCDIR)/SRC/slaqr5.c \
$(LAPACKSRCDIR)/SRC/slaqsb.c \
$(LAPACKSRCDIR)/SRC/slaqsp.c \
$(LAPACKSRCDIR)/SRC/slaqsy.c \
$(LAPACKSRCDIR)/SRC/slaqtr.c \
$(LAPACKSRCDIR)/SRC/slar1v.c \
$(LAPACKSRCDIR)/SRC/slar2v.c \
$(LAPACKSRCDIR)/SRC/slarfb.c \
$(LAPACKSRCDIR)/SRC/slarf.c \
$(LAPACKSRCDIR)/SRC/slarfg.c \
$(LAPACKSRCDIR)/SRC/slarfgp.c \
$(LAPACKSRCDIR)/SRC/slarft.c \
$(LAPACKSRCDIR)/SRC/slarfx.c \
$(LAPACKSRCDIR)/SRC/slarfy.c \
$(LAPACKSRCDIR)/SRC/slargv.c \
$(LAPACKSRCDIR)/SRC/slarnv.c \
$(LAPACKSRCDIR)/SRC/slarra.c \
$(LAPACKSRCDIR)/SRC/slarrb.c \
$(LAPACKSRCDIR)/SRC/slarrc.c \
$(LAPACKSRCDIR)/SRC/slarrd.c \
$(LAPACKSRCDIR)/SRC/slarre.c \
$(LAPACKSRCDIR)/SRC/slarrf.c \
$(LAPACKSRCDIR)/SRC/slarrj.c \
$(LAPACKSRCDIR)/SRC/slarrk.c \
$(LAPACKSRCDIR)/SRC/slarrr.c \
$(LAPACKSRCDIR)/SRC/slarrv.c \
$(LAPACKSRCDIR)/SRC/slarscl2.c \
$(LAPACKSRCDIR)/SRC/slartg.c \
$(LAPACKSRCDIR)/SRC/slartgp.c \
$(LAPACKSRCDIR)/SRC/slartgs.c \
$(LAPACKSRCDIR)/SRC/slartv.c \
$(LAPACKSRCDIR)/SRC/slaruv.c \
$(LAPACKSRCDIR)/SRC/slarzb.c \
$(LAPACKSRCDIR)/SRC/slarz.c \
$(LAPACKSRCDIR)/SRC/slarzt.c \
$(LAPACKSRCDIR)/SRC/slas2.c \
$(LAPACKSRCDIR)/SRC/slascl2.c \
$(LAPACKSRCDIR)/SRC/slascl.c \
$(LAPACKSRCDIR)/SRC/slasd0.c \
$(LAPACKSRCDIR)/SRC/slasd1.c \
$(LAPACKSRCDIR)/SRC/slasd2.c \
$(LAPACKSRCDIR)/SRC/slasd3.c \
$(LAPACKSRCDIR)/SRC/slasd4.c \
$(LAPACKSRCDIR)/SRC/slasd5.c \
$(LAPACKSRCDIR)/SRC/slasd6.c \
$(LAPACKSRCDIR)/SRC/slasd7.c \
$(LAPACKSRCDIR)/SRC/slasd8.c \
$(LAPACKSRCDIR)/SRC/slasda.c \
$(LAPACKSRCDIR)/SRC/slasdq.c \
$(LAPACKSRCDIR)/SRC/slasdt.c \
$(LAPACKSRCDIR)/SRC/slaset.c \
$(LAPACKSRCDIR)/SRC/slasq1.c \
$(LAPACKSRCDIR)/SRC/slasq2.c \
$(LAPACKSRCDIR)/SRC/slasq3.c \
$(LAPACKSRCDIR)/SRC/slasq4.c \
$(LAPACKSRCDIR)/SRC/slasq5.c \
$(LAPACKSRCDIR)/SRC/slasq6.c \
$(LAPACKSRCDIR)/SRC/slasr.c \
$(LAPACKSRCDIR)/SRC/slasrt.c \
$(LAPACKSRCDIR)/SRC/slassq.c \
$(LAPACKSRCDIR)/SRC/slasv2.c \
$(LAPACKSRCDIR)/SRC/slaswlq.c \
$(LAPACKSRCDIR)/SRC/slaswp.c \
$(LAPACKSRCDIR)/SRC/slasy2.c \
$(LAPACKSRCDIR)/SRC/sla_syamv.c \
$(LAPACKSRCDIR)/SRC/slasyf_aa.c \
$(LAPACKSRCDIR)/SRC/slasyf.c \
$(LAPACKSRCDIR)/SRC/slasyf_rk.c \
$(LAPACKSRCDIR)/SRC/slasyf_rook.c \
$(LAPACKSRCDIR)/SRC/sla_syrcond.c \
$(LAPACKSRCDIR)/SRC/sla_syrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/sla_syrpvgrw.c \
$(LAPACKSRCDIR)/SRC/slatbs.c \
$(LAPACKSRCDIR)/SRC/slatdf.c \
$(LAPACKSRCDIR)/SRC/slatps.c \
$(LAPACKSRCDIR)/SRC/slatrd.c \
$(LAPACKSRCDIR)/SRC/slatrs.c \
$(LAPACKSRCDIR)/SRC/slatrz.c \
$(LAPACKSRCDIR)/SRC/slatsqr.c \
$(LAPACKSRCDIR)/SRC/slauu2.c \
$(LAPACKSRCDIR)/SRC/slauum.c \
$(LAPACKSRCDIR)/SRC/sla_wwaddw.c \
$(LAPACKSRCDIR)/SRC/sopgtr.c \
$(LAPACKSRCDIR)/SRC/sopmtr.c \
$(LAPACKSRCDIR)/SRC/sorbdb1.c \
$(LAPACKSRCDIR)/SRC/sorbdb2.c \
$(LAPACKSRCDIR)/SRC/sorbdb3.c \
$(LAPACKSRCDIR)/SRC/sorbdb4.c \
$(LAPACKSRCDIR)/SRC/sorbdb5.c \
$(LAPACKSRCDIR)/SRC/sorbdb6.c \
$(LAPACKSRCDIR)/SRC/sorbdb.c \
$(LAPACKSRCDIR)/SRC/sorcsd2by1.c \
$(LAPACKSRCDIR)/SRC/sorcsd.c \
$(LAPACKSRCDIR)/SRC/sorg2l.c \
$(LAPACKSRCDIR)/SRC/sorg2r.c \
$(LAPACKSRCDIR)/SRC/sorgbr.c \
$(LAPACKSRCDIR)/SRC/sorghr.c \
$(LAPACKSRCDIR)/SRC/sorgl2.c \
$(LAPACKSRCDIR)/SRC/sorglq.c \
$(LAPACKSRCDIR)/SRC/sorgql.c \
$(LAPACKSRCDIR)/SRC/sorgqr.c \
$(LAPACKSRCDIR)/SRC/sorgr2.c \
$(LAPACKSRCDIR)/SRC/sorgrq.c \
$(LAPACKSRCDIR)/SRC/sorgtr.c \
$(LAPACKSRCDIR)/SRC/sorm22.c \
$(LAPACKSRCDIR)/SRC/sorm2l.c \
$(LAPACKSRCDIR)/SRC/sorm2r.c \
$(LAPACKSRCDIR)/SRC/sormbr.c \
$(LAPACKSRCDIR)/SRC/sormhr.c \
$(LAPACKSRCDIR)/SRC/sorml2.c \
$(LAPACKSRCDIR)/SRC/sormlq.c \
$(LAPACKSRCDIR)/SRC/sormql.c \
$(LAPACKSRCDIR)/SRC/sormqr.c \
$(LAPACKSRCDIR)/SRC/sormr2.c \
$(LAPACKSRCDIR)/SRC/sormr3.c \
$(LAPACKSRCDIR)/SRC/sormrq.c \
$(LAPACKSRCDIR)/SRC/sormrz.c \
$(LAPACKSRCDIR)/SRC/sormtr.c \
$(LAPACKSRCDIR)/SRC/spbcon.c \
$(LAPACKSRCDIR)/SRC/spbequ.c \
$(LAPACKSRCDIR)/SRC/spbrfs.c \
$(LAPACKSRCDIR)/SRC/spbstf.c \
$(LAPACKSRCDIR)/SRC/spbsv.c \
$(LAPACKSRCDIR)/SRC/spbsvx.c \
$(LAPACKSRCDIR)/SRC/spbtf2.c \
$(LAPACKSRCDIR)/SRC/spbtrf.c \
$(LAPACKSRCDIR)/SRC/spbtrs.c \
$(LAPACKSRCDIR)/SRC/spftrf.c \
$(LAPACKSRCDIR)/SRC/spftri.c \
$(LAPACKSRCDIR)/SRC/spftrs.c \
$(LAPACKSRCDIR)/SRC/spocon.c \
$(LAPACKSRCDIR)/SRC/spoequb.c \
$(LAPACKSRCDIR)/SRC/spoequ.c \
$(LAPACKSRCDIR)/SRC/sporfs.c \
$(LAPACKSRCDIR)/SRC/sposv.c \
$(LAPACKSRCDIR)/SRC/sposvx.c \
$(LAPACKSRCDIR)/SRC/sposvxx.c \
$(LAPACKSRCDIR)/SRC/spotf2.c \
$(LAPACKSRCDIR)/SRC/spotrf.c \
$(LAPACKSRCDIR)/SRC/spotri.c \
$(LAPACKSRCDIR)/SRC/spotrs.c \
$(LAPACKSRCDIR)/SRC/sppcon.c \
$(LAPACKSRCDIR)/SRC/sppequ.c \
$(LAPACKSRCDIR)/SRC/spprfs.c \
$(LAPACKSRCDIR)/SRC/sppsv.c \
$(LAPACKSRCDIR)/SRC/sppsvx.c \
$(LAPACKSRCDIR)/SRC/spptrf.c \
$(LAPACKSRCDIR)/SRC/spptri.c \
$(LAPACKSRCDIR)/SRC/spptrs.c \
$(LAPACKSRCDIR)/SRC/spstf2.c \
$(LAPACKSRCDIR)/SRC/spstrf.c \
$(LAPACKSRCDIR)/SRC/sptcon.c \
$(LAPACKSRCDIR)/SRC/spteqr.c \
$(LAPACKSRCDIR)/SRC/sptrfs.c \
$(LAPACKSRCDIR)/SRC/sptsv.c \
$(LAPACKSRCDIR)/SRC/sptsvx.c \
$(LAPACKSRCDIR)/SRC/spttrf.c \
$(LAPACKSRCDIR)/SRC/spttrs.c \
$(LAPACKSRCDIR)/SRC/sptts2.c \
$(LAPACKSRCDIR)/SRC/srscl.c \
$(LAPACKSRCDIR)/SRC/ssb2st_kernels.c \
$(LAPACKSRCDIR)/SRC/ssbev_2stage.c \
$(LAPACKSRCDIR)/SRC/ssbev.c \
$(LAPACKSRCDIR)/SRC/ssbevd_2stage.c \
$(LAPACKSRCDIR)/SRC/ssbevd.c \
$(LAPACKSRCDIR)/SRC/ssbevx_2stage.c \
$(LAPACKSRCDIR)/SRC/ssbevx.c \
$(LAPACKSRCDIR)/SRC/ssbgst.c \
$(LAPACKSRCDIR)/SRC/ssbgv.c \
$(LAPACKSRCDIR)/SRC/ssbgvd.c \
$(LAPACKSRCDIR)/SRC/ssbgvx.c \
$(LAPACKSRCDIR)/SRC/ssbtrd.c \
$(LAPACKSRCDIR)/SRC/ssfrk.c \
$(LAPACKSRCDIR)/SRC/sspcon.c \
$(LAPACKSRCDIR)/SRC/sspev.c \
$(LAPACKSRCDIR)/SRC/sspevd.c \
$(LAPACKSRCDIR)/SRC/sspevx.c \
$(LAPACKSRCDIR)/SRC/sspgst.c \
$(LAPACKSRCDIR)/SRC/sspgv.c \
$(LAPACKSRCDIR)/SRC/sspgvd.c \
$(LAPACKSRCDIR)/SRC/sspgvx.c \
$(LAPACKSRCDIR)/SRC/ssprfs.c \
$(LAPACKSRCDIR)/SRC/sspsv.c \
$(LAPACKSRCDIR)/SRC/sspsvx.c \
$(LAPACKSRCDIR)/SRC/ssptrd.c \
$(LAPACKSRCDIR)/SRC/ssptrf.c \
$(LAPACKSRCDIR)/SRC/ssptri.c \
$(LAPACKSRCDIR)/SRC/ssptrs.c \
$(LAPACKSRCDIR)/SRC/sstebz.c \
$(LAPACKSRCDIR)/SRC/sstedc.c \
$(LAPACKSRCDIR)/SRC/sstegr.c \
$(LAPACKSRCDIR)/SRC/sstein.c \
$(LAPACKSRCDIR)/SRC/sstemr.c \
$(LAPACKSRCDIR)/SRC/ssteqr.c \
$(LAPACKSRCDIR)/SRC/ssterf.c \
$(LAPACKSRCDIR)/SRC/sstev.c \
$(LAPACKSRCDIR)/SRC/sstevd.c \
$(LAPACKSRCDIR)/SRC/sstevr.c \
$(LAPACKSRCDIR)/SRC/sstevx.c \
$(LAPACKSRCDIR)/SRC/ssycon_3.c \
$(LAPACKSRCDIR)/SRC/ssycon.c \
$(LAPACKSRCDIR)/SRC/ssycon_rook.c \
$(LAPACKSRCDIR)/SRC/ssyconv.c \
$(LAPACKSRCDIR)/SRC/ssyconvf.c \
$(LAPACKSRCDIR)/SRC/ssyconvf_rook.c \
$(LAPACKSRCDIR)/SRC/ssyequb.c \
$(LAPACKSRCDIR)/SRC/ssyev_2stage.c \
$(LAPACKSRCDIR)/SRC/ssyev.c \
$(LAPACKSRCDIR)/SRC/ssyevd_2stage.c \
$(LAPACKSRCDIR)/SRC/ssyevd.c \
$(LAPACKSRCDIR)/SRC/ssyevr_2stage.c \
$(LAPACKSRCDIR)/SRC/ssyevr.c \
$(LAPACKSRCDIR)/SRC/ssyevx_2stage.c \
$(LAPACKSRCDIR)/SRC/ssyevx.c \
$(LAPACKSRCDIR)/SRC/ssygs2.c \
$(LAPACKSRCDIR)/SRC/ssygst.c \
$(LAPACKSRCDIR)/SRC/ssygv_2stage.c \
$(LAPACKSRCDIR)/SRC/ssygv.c \
$(LAPACKSRCDIR)/SRC/ssygvd.c \
$(LAPACKSRCDIR)/SRC/ssygvx.c \
$(LAPACKSRCDIR)/SRC/ssyrfs.c \
$(LAPACKSRCDIR)/SRC/ssysv_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/ssysv_aa.c \
$(LAPACKSRCDIR)/SRC/ssysv.c \
$(LAPACKSRCDIR)/SRC/ssysv_rk.c \
$(LAPACKSRCDIR)/SRC/ssysv_rook.c \
$(LAPACKSRCDIR)/SRC/ssysvx.c \
$(LAPACKSRCDIR)/SRC/ssysvxx.c \
$(LAPACKSRCDIR)/SRC/ssyswapr.c \
$(LAPACKSRCDIR)/SRC/ssytd2.c \
$(LAPACKSRCDIR)/SRC/ssytf2.c \
$(LAPACKSRCDIR)/SRC/ssytf2_rk.c \
$(LAPACKSRCDIR)/SRC/ssytf2_rook.c \
$(LAPACKSRCDIR)/SRC/ssytrd_2stage.c \
$(LAPACKSRCDIR)/SRC/ssytrd.c \
$(LAPACKSRCDIR)/SRC/ssytrd_sy2sb.c \
$(LAPACKSRCDIR)/SRC/ssytrf_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/ssytrf_aa.c \
$(LAPACKSRCDIR)/SRC/ssytrf.c \
$(LAPACKSRCDIR)/SRC/ssytrf_rk.c \
$(LAPACKSRCDIR)/SRC/ssytrf_rook.c \
$(LAPACKSRCDIR)/SRC/ssytri2.c \
$(LAPACKSRCDIR)/SRC/ssytri2x.c \
$(LAPACKSRCDIR)/SRC/ssytri_3.c \
$(LAPACKSRCDIR)/SRC/ssytri_3x.c \
$(LAPACKSRCDIR)/SRC/ssytri.c \
$(LAPACKSRCDIR)/SRC/ssytri_rook.c \
$(LAPACKSRCDIR)/SRC/ssytrs2.c \
$(LAPACKSRCDIR)/SRC/ssytrs_3.c \
$(LAPACKSRCDIR)/SRC/ssytrs_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/ssytrs_aa.c \
$(LAPACKSRCDIR)/SRC/ssytrs.c \
$(LAPACKSRCDIR)/SRC/ssytrs_rook.c \
$(LAPACKSRCDIR)/SRC/stbcon.c \
$(LAPACKSRCDIR)/SRC/stbrfs.c \
$(LAPACKSRCDIR)/SRC/stbtrs.c \
$(LAPACKSRCDIR)/SRC/stfsm.c \
$(LAPACKSRCDIR)/SRC/stftri.c \
$(LAPACKSRCDIR)/SRC/stfttp.c \
$(LAPACKSRCDIR)/SRC/stfttr.c \
$(LAPACKSRCDIR)/SRC/stgevc.c \
$(LAPACKSRCDIR)/SRC/stgex2.c \
$(LAPACKSRCDIR)/SRC/stgexc.c \
$(LAPACKSRCDIR)/SRC/stgsen.c \
$(LAPACKSRCDIR)/SRC/stgsja.c \
$(LAPACKSRCDIR)/SRC/stgsna.c \
$(LAPACKSRCDIR)/SRC/stgsy2.c \
$(LAPACKSRCDIR)/SRC/stgsyl.c \
$(LAPACKSRCDIR)/SRC/stpcon.c \
$(LAPACKSRCDIR)/SRC/stplqt2.c \
$(LAPACKSRCDIR)/SRC/stplqt.c \
$(LAPACKSRCDIR)/SRC/stpmlqt.c \
$(LAPACKSRCDIR)/SRC/stpmqrt.c \
$(LAPACKSRCDIR)/SRC/stpqrt2.c \
$(LAPACKSRCDIR)/SRC/stpqrt.c \
$(LAPACKSRCDIR)/SRC/stprfb.c \
$(LAPACKSRCDIR)/SRC/stprfs.c \
$(LAPACKSRCDIR)/SRC/stptri.c \
$(LAPACKSRCDIR)/SRC/stptrs.c \
$(LAPACKSRCDIR)/SRC/stpttf.c \
$(LAPACKSRCDIR)/SRC/stpttr.c \
$(LAPACKSRCDIR)/SRC/strcon.c \
$(LAPACKSRCDIR)/SRC/strevc3.c \
$(LAPACKSRCDIR)/SRC/strevc.c \
$(LAPACKSRCDIR)/SRC/strexc.c \
$(LAPACKSRCDIR)/SRC/strrfs.c \
$(LAPACKSRCDIR)/SRC/strsen.c \
$(LAPACKSRCDIR)/SRC/strsna.c \
$(LAPACKSRCDIR)/SRC/strsyl.c \
$(LAPACKSRCDIR)/SRC/strti2.c \
$(LAPACKSRCDIR)/SRC/strtri.c \
$(LAPACKSRCDIR)/SRC/strtrs.c \
$(LAPACKSRCDIR)/SRC/strttf.c \
$(LAPACKSRCDIR)/SRC/strttp.c \
$(LAPACKSRCDIR)/SRC/stzrzf.c \
$(LAPACKSRCDIR)/SRC/zbbcsd.c \
$(LAPACKSRCDIR)/SRC/zbdsqr.c \
$(LAPACKSRCDIR)/SRC/zcgesv.c \
$(LAPACKSRCDIR)/SRC/zcposv.c \
$(LAPACKSRCDIR)/SRC/zdrscl.c \
$(LAPACKSRCDIR)/SRC/zgbbrd.c \
$(LAPACKSRCDIR)/SRC/zgbcon.c \
$(LAPACKSRCDIR)/SRC/zgbequb.c \
$(LAPACKSRCDIR)/SRC/zgbequ.c \
$(LAPACKSRCDIR)/SRC/zgbrfs.c \
$(LAPACKSRCDIR)/SRC/zgbsv.c \
$(LAPACKSRCDIR)/SRC/zgbsvx.c \
$(LAPACKSRCDIR)/SRC/zgbsvxx.c \
$(LAPACKSRCDIR)/SRC/zgbtf2.c \
$(LAPACKSRCDIR)/SRC/zgbtrf.c \
$(LAPACKSRCDIR)/SRC/zgbtrs.c \
$(LAPACKSRCDIR)/SRC/zgebak.c \
$(LAPACKSRCDIR)/SRC/zgebal.c \
$(LAPACKSRCDIR)/SRC/zgebd2.c \
$(LAPACKSRCDIR)/SRC/zgebrd.c \
$(LAPACKSRCDIR)/SRC/zgecon.c \
$(LAPACKSRCDIR)/SRC/zgeequb.c \
$(LAPACKSRCDIR)/SRC/zgeequ.c \
$(LAPACKSRCDIR)/SRC/zgees.c \
$(LAPACKSRCDIR)/SRC/zgeesx.c \
$(LAPACKSRCDIR)/SRC/zgeev.c \
$(LAPACKSRCDIR)/SRC/zgeevx.c \
$(LAPACKSRCDIR)/SRC/zgehd2.c \
$(LAPACKSRCDIR)/SRC/zgehrd.c \
$(LAPACKSRCDIR)/SRC/zgelq2.c \
$(LAPACKSRCDIR)/SRC/zgelq.c \
$(LAPACKSRCDIR)/SRC/zgelqf.c \
$(LAPACKSRCDIR)/SRC/zgelqt.c \
$(LAPACKSRCDIR)/SRC/zgels.c \
$(LAPACKSRCDIR)/SRC/zgelsd.c \
$(LAPACKSRCDIR)/SRC/zgelss.c \
$(LAPACKSRCDIR)/SRC/zgelsy.c \
$(LAPACKSRCDIR)/SRC/zgemlq.c \
$(LAPACKSRCDIR)/SRC/zgemlqt.c \
$(LAPACKSRCDIR)/SRC/zgemqr.c \
$(LAPACKSRCDIR)/SRC/zgemqrt.c \
$(LAPACKSRCDIR)/SRC/zgeql2.c \
$(LAPACKSRCDIR)/SRC/zgeqlf.c \
$(LAPACKSRCDIR)/SRC/zgeqp3.c \
$(LAPACKSRCDIR)/SRC/zgeqr2.c \
$(LAPACKSRCDIR)/SRC/zgeqr2p.c \
$(LAPACKSRCDIR)/SRC/zgeqr.c \
$(LAPACKSRCDIR)/SRC/zgeqrf.c \
$(LAPACKSRCDIR)/SRC/zgeqrfp.c \
$(LAPACKSRCDIR)/SRC/zgeqrt2.c \
$(LAPACKSRCDIR)/SRC/zgeqrt3.c \
$(LAPACKSRCDIR)/SRC/zgeqrt.c \
$(LAPACKSRCDIR)/SRC/zgerfs.c \
$(LAPACKSRCDIR)/SRC/zgerq2.c \
$(LAPACKSRCDIR)/SRC/zgerqf.c \
$(LAPACKSRCDIR)/SRC/zgesc2.c \
$(LAPACKSRCDIR)/SRC/zgesdd.c \
$(LAPACKSRCDIR)/SRC/zgesv.c \
$(LAPACKSRCDIR)/SRC/zgesvd.c \
$(LAPACKSRCDIR)/SRC/zgesvdx.c \
$(LAPACKSRCDIR)/SRC/zgesvj.c \
$(LAPACKSRCDIR)/SRC/zgesvx.c \
$(LAPACKSRCDIR)/SRC/zgesvxx.c \
$(LAPACKSRCDIR)/SRC/zgetc2.c \
$(LAPACKSRCDIR)/SRC/zgetf2.c \
$(LAPACKSRCDIR)/SRC/zgetrf2.c \
$(LAPACKSRCDIR)/SRC/zgetrf.c \
$(LAPACKSRCDIR)/SRC/zgetri.c \
$(LAPACKSRCDIR)/SRC/zgetrs.c \
$(LAPACKSRCDIR)/SRC/zgetsls.c \
$(LAPACKSRCDIR)/SRC/zggbak.c \
$(LAPACKSRCDIR)/SRC/zggbal.c \
$(LAPACKSRCDIR)/SRC/zgges3.c \
$(LAPACKSRCDIR)/SRC/zgges.c \
$(LAPACKSRCDIR)/SRC/zggesx.c \
$(LAPACKSRCDIR)/SRC/zggev3.c \
$(LAPACKSRCDIR)/SRC/zggev.c \
$(LAPACKSRCDIR)/SRC/zggevx.c \
$(LAPACKSRCDIR)/SRC/zggglm.c \
$(LAPACKSRCDIR)/SRC/zgghd3.c \
$(LAPACKSRCDIR)/SRC/zgghrd.c \
$(LAPACKSRCDIR)/SRC/zgglse.c \
$(LAPACKSRCDIR)/SRC/zggqrf.c \
$(LAPACKSRCDIR)/SRC/zggrqf.c \
$(LAPACKSRCDIR)/SRC/zggsvd3.c \
$(LAPACKSRCDIR)/SRC/zggsvp3.c \
$(LAPACKSRCDIR)/SRC/zgsvj0.c \
$(LAPACKSRCDIR)/SRC/zgsvj1.c \
$(LAPACKSRCDIR)/SRC/zgtcon.c \
$(LAPACKSRCDIR)/SRC/zgtrfs.c \
$(LAPACKSRCDIR)/SRC/zgtsv.c \
$(LAPACKSRCDIR)/SRC/zgtsvx.c \
$(LAPACKSRCDIR)/SRC/zgttrf.c \
$(LAPACKSRCDIR)/SRC/zgttrs.c \
$(LAPACKSRCDIR)/SRC/zgtts2.c \
$(LAPACKSRCDIR)/SRC/zhb2st_kernels.c \
$(LAPACKSRCDIR)/SRC/zhbev_2stage.c \
$(LAPACKSRCDIR)/SRC/zhbev.c \
$(LAPACKSRCDIR)/SRC/zhbevd_2stage.c \
$(LAPACKSRCDIR)/SRC/zhbevd.c \
$(LAPACKSRCDIR)/SRC/zhbevx_2stage.c \
$(LAPACKSRCDIR)/SRC/zhbevx.c \
$(LAPACKSRCDIR)/SRC/zhbgst.c \
$(LAPACKSRCDIR)/SRC/zhbgv.c \
$(LAPACKSRCDIR)/SRC/zhbgvd.c \
$(LAPACKSRCDIR)/SRC/zhbgvx.c \
$(LAPACKSRCDIR)/SRC/zhbtrd.c \
$(LAPACKSRCDIR)/SRC/zhecon_3.c \
$(LAPACKSRCDIR)/SRC/zhecon.c \
$(LAPACKSRCDIR)/SRC/zhecon_rook.c \
$(LAPACKSRCDIR)/SRC/zheequb.c \
$(LAPACKSRCDIR)/SRC/zheev_2stage.c \
$(LAPACKSRCDIR)/SRC/zheev.c \
$(LAPACKSRCDIR)/SRC/zheevd_2stage.c \
$(LAPACKSRCDIR)/SRC/zheevd.c \
$(LAPACKSRCDIR)/SRC/zheevr_2stage.c \
$(LAPACKSRCDIR)/SRC/zheevr.c \
$(LAPACKSRCDIR)/SRC/zheevx_2stage.c \
$(LAPACKSRCDIR)/SRC/zheevx.c \
$(LAPACKSRCDIR)/SRC/zhegs2.c \
$(LAPACKSRCDIR)/SRC/zhegst.c \
$(LAPACKSRCDIR)/SRC/zhegv_2stage.c \
$(LAPACKSRCDIR)/SRC/zhegv.c \
$(LAPACKSRCDIR)/SRC/zhegvd.c \
$(LAPACKSRCDIR)/SRC/zhegvx.c \
$(LAPACKSRCDIR)/SRC/zherfs.c \
$(LAPACKSRCDIR)/SRC/zhesv_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/zhesv_aa.c \
$(LAPACKSRCDIR)/SRC/zhesv.c \
$(LAPACKSRCDIR)/SRC/zhesv_rk.c \
$(LAPACKSRCDIR)/SRC/zhesv_rook.c \
$(LAPACKSRCDIR)/SRC/zhesvx.c \
$(LAPACKSRCDIR)/SRC/zhesvxx.c \
$(LAPACKSRCDIR)/SRC/zheswapr.c \
$(LAPACKSRCDIR)/SRC/zhetd2.c \
$(LAPACKSRCDIR)/SRC/zhetf2.c \
$(LAPACKSRCDIR)/SRC/zhetf2_rk.c \
$(LAPACKSRCDIR)/SRC/zhetf2_rook.c \
$(LAPACKSRCDIR)/SRC/zhetrd_2stage.c \
$(LAPACKSRCDIR)/SRC/zhetrd.c \
$(LAPACKSRCDIR)/SRC/zhetrd_he2hb.c \
$(LAPACKSRCDIR)/SRC/zhetrf_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/zhetrf_aa.c \
$(LAPACKSRCDIR)/SRC/zhetrf.c \
$(LAPACKSRCDIR)/SRC/zhetrf_rk.c \
$(LAPACKSRCDIR)/SRC/zhetrf_rook.c \
$(LAPACKSRCDIR)/SRC/zhetri2.c \
$(LAPACKSRCDIR)/SRC/zhetri2x.c \
$(LAPACKSRCDIR)/SRC/zhetri_3.c \
$(LAPACKSRCDIR)/SRC/zhetri_3x.c \
$(LAPACKSRCDIR)/SRC/zhetri.c \
$(LAPACKSRCDIR)/SRC/zhetri_rook.c \
$(LAPACKSRCDIR)/SRC/zhetrs2.c \
$(LAPACKSRCDIR)/SRC/zhetrs_3.c \
$(LAPACKSRCDIR)/SRC/zhetrs_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/zhetrs_aa.c \
$(LAPACKSRCDIR)/SRC/zhetrs.c \
$(LAPACKSRCDIR)/SRC/zhetrs_rook.c \
$(LAPACKSRCDIR)/SRC/zhfrk.c \
$(LAPACKSRCDIR)/SRC/zhgeqz.c \
$(LAPACKSRCDIR)/SRC/zhpcon.c \
$(LAPACKSRCDIR)/SRC/zhpev.c \
$(LAPACKSRCDIR)/SRC/zhpevd.c \
$(LAPACKSRCDIR)/SRC/zhpevx.c \
$(LAPACKSRCDIR)/SRC/zhpgst.c \
$(LAPACKSRCDIR)/SRC/zhpgv.c \
$(LAPACKSRCDIR)/SRC/zhpgvd.c \
$(LAPACKSRCDIR)/SRC/zhpgvx.c \
$(LAPACKSRCDIR)/SRC/zhprfs.c \
$(LAPACKSRCDIR)/SRC/zhpsv.c \
$(LAPACKSRCDIR)/SRC/zhpsvx.c \
$(LAPACKSRCDIR)/SRC/zhptrd.c \
$(LAPACKSRCDIR)/SRC/zhptrf.c \
$(LAPACKSRCDIR)/SRC/zhptri.c \
$(LAPACKSRCDIR)/SRC/zhptrs.c \
$(LAPACKSRCDIR)/SRC/zhsein.c \
$(LAPACKSRCDIR)/SRC/zhseqr.c \
$(LAPACKSRCDIR)/SRC/zlabrd.c \
$(LAPACKSRCDIR)/SRC/zlacgv.c \
$(LAPACKSRCDIR)/SRC/zlacn2.c \
$(LAPACKSRCDIR)/SRC/zlacon.c \
$(LAPACKSRCDIR)/SRC/zlacp2.c \
$(LAPACKSRCDIR)/SRC/zlacpy.c \
$(LAPACKSRCDIR)/SRC/zlacrm.c \
$(LAPACKSRCDIR)/SRC/zlacrt.c \
$(LAPACKSRCDIR)/SRC/zladiv.c \
$(LAPACKSRCDIR)/SRC/zlaed0.c \
$(LAPACKSRCDIR)/SRC/zlaed7.c \
$(LAPACKSRCDIR)/SRC/zlaed8.c \
$(LAPACKSRCDIR)/SRC/zlaein.c \
$(LAPACKSRCDIR)/SRC/zlaesy.c \
$(LAPACKSRCDIR)/SRC/zlaev2.c \
$(LAPACKSRCDIR)/SRC/zlag2c.c \
$(LAPACKSRCDIR)/SRC/zla_gbamv.c \
$(LAPACKSRCDIR)/SRC/zla_gbrcond_c.c \
$(LAPACKSRCDIR)/SRC/zla_gbrcond_x.c \
$(LAPACKSRCDIR)/SRC/zla_gbrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/zla_gbrpvgrw.c \
$(LAPACKSRCDIR)/SRC/zla_geamv.c \
$(LAPACKSRCDIR)/SRC/zla_gercond_c.c \
$(LAPACKSRCDIR)/SRC/zla_gercond_x.c \
$(LAPACKSRCDIR)/SRC/zla_gerfsx_extended.c \
$(LAPACKSRCDIR)/SRC/zla_gerpvgrw.c \
$(LAPACKSRCDIR)/SRC/zlags2.c \
$(LAPACKSRCDIR)/SRC/zlagtm.c \
$(LAPACKSRCDIR)/SRC/zla_heamv.c \
$(LAPACKSRCDIR)/SRC/zlahef_aa.c \
$(LAPACKSRCDIR)/SRC/zlahef.c \
$(LAPACKSRCDIR)/SRC/zlahef_rk.c \
$(LAPACKSRCDIR)/SRC/zlahef_rook.c \
$(LAPACKSRCDIR)/SRC/zla_hercond_c.c \
$(LAPACKSRCDIR)/SRC/zla_hercond_x.c \
$(LAPACKSRCDIR)/SRC/zla_herfsx_extended.c \
$(LAPACKSRCDIR)/SRC/zla_herpvgrw.c \
$(LAPACKSRCDIR)/SRC/zlahqr.c \
$(LAPACKSRCDIR)/SRC/zlahr2.c \
$(LAPACKSRCDIR)/SRC/zlaic1.c \
$(LAPACKSRCDIR)/SRC/zla_lin_berr.c \
$(LAPACKSRCDIR)/SRC/zlals0.c \
$(LAPACKSRCDIR)/SRC/zlalsa.c \
$(LAPACKSRCDIR)/SRC/zlalsd.c \
$(LAPACKSRCDIR)/SRC/zlamswlq.c \
$(LAPACKSRCDIR)/SRC/zlamtsqr.c \
$(LAPACKSRCDIR)/SRC/zlangb.c \
$(LAPACKSRCDIR)/SRC/zlange.c \
$(LAPACKSRCDIR)/SRC/zlangt.c \
$(LAPACKSRCDIR)/SRC/zlanhb.c \
$(LAPACKSRCDIR)/SRC/zlanhe.c \
$(LAPACKSRCDIR)/SRC/zlanhf.c \
$(LAPACKSRCDIR)/SRC/zlanhp.c \
$(LAPACKSRCDIR)/SRC/zlanhs.c \
$(LAPACKSRCDIR)/SRC/zlanht.c \
$(LAPACKSRCDIR)/SRC/zlansb.c \
$(LAPACKSRCDIR)/SRC/zlansp.c \
$(LAPACKSRCDIR)/SRC/zlansy.c \
$(LAPACKSRCDIR)/SRC/zlantb.c \
$(LAPACKSRCDIR)/SRC/zlantp.c \
$(LAPACKSRCDIR)/SRC/zlantr.c \
$(LAPACKSRCDIR)/SRC/zlapll.c \
$(LAPACKSRCDIR)/SRC/zlapmr.c \
$(LAPACKSRCDIR)/SRC/zlapmt.c \
$(LAPACKSRCDIR)/SRC/zla_porcond_c.c \
$(LAPACKSRCDIR)/SRC/zla_porcond_x.c \
$(LAPACKSRCDIR)/SRC/zla_porfsx_extended.c \
$(LAPACKSRCDIR)/SRC/zla_porpvgrw.c \
$(LAPACKSRCDIR)/SRC/zlaqgb.c \
$(LAPACKSRCDIR)/SRC/zlaqge.c \
$(LAPACKSRCDIR)/SRC/zlaqhb.c \
$(LAPACKSRCDIR)/SRC/zlaqhe.c \
$(LAPACKSRCDIR)/SRC/zlaqhp.c \
$(LAPACKSRCDIR)/SRC/zlaqp2.c \
$(LAPACKSRCDIR)/SRC/zlaqps.c \
$(LAPACKSRCDIR)/SRC/zlaqr0.c \
$(LAPACKSRCDIR)/SRC/zlaqr1.c \
$(LAPACKSRCDIR)/SRC/zlaqr2.c \
$(LAPACKSRCDIR)/SRC/zlaqr3.c \
$(LAPACKSRCDIR)/SRC/zlaqr4.c \
$(LAPACKSRCDIR)/SRC/zlaqr5.c \
$(LAPACKSRCDIR)/SRC/zlaqsb.c \
$(LAPACKSRCDIR)/SRC/zlaqsp.c \
$(LAPACKSRCDIR)/SRC/zlaqsy.c \
$(LAPACKSRCDIR)/SRC/zlar1v.c \
$(LAPACKSRCDIR)/SRC/zlar2v.c \
$(LAPACKSRCDIR)/SRC/zlarcm.c \
$(LAPACKSRCDIR)/SRC/zlarfb.c \
$(LAPACKSRCDIR)/SRC/zlarf.c \
$(LAPACKSRCDIR)/SRC/zlarfg.c \
$(LAPACKSRCDIR)/SRC/zlarfgp.c \
$(LAPACKSRCDIR)/SRC/zlarft.c \
$(LAPACKSRCDIR)/SRC/zlarfx.c \
$(LAPACKSRCDIR)/SRC/zlarfy.c \
$(LAPACKSRCDIR)/SRC/zlargv.c \
$(LAPACKSRCDIR)/SRC/zlarnv.c \
$(LAPACKSRCDIR)/SRC/zlarrv.c \
$(LAPACKSRCDIR)/SRC/zlarscl2.c \
$(LAPACKSRCDIR)/SRC/zlartg.c \
$(LAPACKSRCDIR)/SRC/zlartv.c \
$(LAPACKSRCDIR)/SRC/zlarzb.c \
$(LAPACKSRCDIR)/SRC/zlarz.c \
$(LAPACKSRCDIR)/SRC/zlarzt.c \
$(LAPACKSRCDIR)/SRC/zlascl2.c \
$(LAPACKSRCDIR)/SRC/zlascl.c \
$(LAPACKSRCDIR)/SRC/zlaset.c \
$(LAPACKSRCDIR)/SRC/zlasr.c \
$(LAPACKSRCDIR)/SRC/zlassq.c \
$(LAPACKSRCDIR)/SRC/zlaswlq.c \
$(LAPACKSRCDIR)/SRC/zlaswp.c \
$(LAPACKSRCDIR)/SRC/zla_syamv.c \
$(LAPACKSRCDIR)/SRC/zlasyf_aa.c \
$(LAPACKSRCDIR)/SRC/zlasyf.c \
$(LAPACKSRCDIR)/SRC/zlasyf_rk.c \
$(LAPACKSRCDIR)/SRC/zlasyf_rook.c \
$(LAPACKSRCDIR)/SRC/zla_syrcond_c.c \
$(LAPACKSRCDIR)/SRC/zla_syrcond_x.c \
$(LAPACKSRCDIR)/SRC/zla_syrfsx_extended.c \
$(LAPACKSRCDIR)/SRC/zla_syrpvgrw.c \
$(LAPACKSRCDIR)/SRC/zlat2c.c \
$(LAPACKSRCDIR)/SRC/zlatbs.c \
$(LAPACKSRCDIR)/SRC/zlatdf.c \
$(LAPACKSRCDIR)/SRC/zlatps.c \
$(LAPACKSRCDIR)/SRC/zlatrd.c \
$(LAPACKSRCDIR)/SRC/zlatrs.c \
$(LAPACKSRCDIR)/SRC/zlatrz.c \
$(LAPACKSRCDIR)/SRC/zlatsqr.c \
$(LAPACKSRCDIR)/SRC/zlauu2.c \
$(LAPACKSRCDIR)/SRC/zlauum.c \
$(LAPACKSRCDIR)/SRC/zla_wwaddw.c \
$(LAPACKSRCDIR)/SRC/zpbcon.c \
$(LAPACKSRCDIR)/SRC/zpbequ.c \
$(LAPACKSRCDIR)/SRC/zpbrfs.c \
$(LAPACKSRCDIR)/SRC/zpbstf.c \
$(LAPACKSRCDIR)/SRC/zpbsv.c \
$(LAPACKSRCDIR)/SRC/zpbsvx.c \
$(LAPACKSRCDIR)/SRC/zpbtf2.c \
$(LAPACKSRCDIR)/SRC/zpbtrf.c \
$(LAPACKSRCDIR)/SRC/zpbtrs.c \
$(LAPACKSRCDIR)/SRC/zpftrf.c \
$(LAPACKSRCDIR)/SRC/zpftri.c \
$(LAPACKSRCDIR)/SRC/zpftrs.c \
$(LAPACKSRCDIR)/SRC/zpocon.c \
$(LAPACKSRCDIR)/SRC/zpoequb.c \
$(LAPACKSRCDIR)/SRC/zpoequ.c \
$(LAPACKSRCDIR)/SRC/zporfs.c \
$(LAPACKSRCDIR)/SRC/zposv.c \
$(LAPACKSRCDIR)/SRC/zposvx.c \
$(LAPACKSRCDIR)/SRC/zposvxx.c \
$(LAPACKSRCDIR)/SRC/zpotf2.c \
$(LAPACKSRCDIR)/SRC/zpotrf.c \
$(LAPACKSRCDIR)/SRC/zpotri.c \
$(LAPACKSRCDIR)/SRC/zpotrs.c \
$(LAPACKSRCDIR)/SRC/zppcon.c \
$(LAPACKSRCDIR)/SRC/zppequ.c \
$(LAPACKSRCDIR)/SRC/zpprfs.c \
$(LAPACKSRCDIR)/SRC/zppsv.c \
$(LAPACKSRCDIR)/SRC/zppsvx.c \
$(LAPACKSRCDIR)/SRC/zpptrf.c \
$(LAPACKSRCDIR)/SRC/zpptri.c \
$(LAPACKSRCDIR)/SRC/zpptrs.c \
$(LAPACKSRCDIR)/SRC/zpstf2.c \
$(LAPACKSRCDIR)/SRC/zpstrf.c \
$(LAPACKSRCDIR)/SRC/zptcon.c \
$(LAPACKSRCDIR)/SRC/zpteqr.c \
$(LAPACKSRCDIR)/SRC/zptrfs.c \
$(LAPACKSRCDIR)/SRC/zptsv.c \
$(LAPACKSRCDIR)/SRC/zptsvx.c \
$(LAPACKSRCDIR)/SRC/zpttrf.c \
$(LAPACKSRCDIR)/SRC/zpttrs.c \
$(LAPACKSRCDIR)/SRC/zptts2.c \
$(LAPACKSRCDIR)/SRC/zrot.c \
$(LAPACKSRCDIR)/SRC/zspcon.c \
$(LAPACKSRCDIR)/SRC/zspmv.c \
$(LAPACKSRCDIR)/SRC/zspr.c \
$(LAPACKSRCDIR)/SRC/zsprfs.c \
$(LAPACKSRCDIR)/SRC/zspsv.c \
$(LAPACKSRCDIR)/SRC/zspsvx.c \
$(LAPACKSRCDIR)/SRC/zsptrf.c \
$(LAPACKSRCDIR)/SRC/zsptri.c \
$(LAPACKSRCDIR)/SRC/zsptrs.c \
$(LAPACKSRCDIR)/SRC/zstedc.c \
$(LAPACKSRCDIR)/SRC/zstegr.c \
$(LAPACKSRCDIR)/SRC/zstein.c \
$(LAPACKSRCDIR)/SRC/zstemr.c \
$(LAPACKSRCDIR)/SRC/zsteqr.c \
$(LAPACKSRCDIR)/SRC/zsycon_3.c \
$(LAPACKSRCDIR)/SRC/zsycon.c \
$(LAPACKSRCDIR)/SRC/zsycon_rook.c \
$(LAPACKSRCDIR)/SRC/zsyconv.c \
$(LAPACKSRCDIR)/SRC/zsyconvf.c \
$(LAPACKSRCDIR)/SRC/zsyconvf_rook.c \
$(LAPACKSRCDIR)/SRC/zsyequb.c \
$(LAPACKSRCDIR)/SRC/zsymv.c \
$(LAPACKSRCDIR)/SRC/zsyr.c \
$(LAPACKSRCDIR)/SRC/zsyrfs.c \
$(LAPACKSRCDIR)/SRC/zsysv_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/zsysv_aa.c \
$(LAPACKSRCDIR)/SRC/zsysv.c \
$(LAPACKSRCDIR)/SRC/zsysv_rk.c \
$(LAPACKSRCDIR)/SRC/zsysv_rook.c \
$(LAPACKSRCDIR)/SRC/zsysvx.c \
$(LAPACKSRCDIR)/SRC/zsysvxx.c \
$(LAPACKSRCDIR)/SRC/zsyswapr.c \
$(LAPACKSRCDIR)/SRC/zsytf2.c \
$(LAPACKSRCDIR)/SRC/zsytf2_rk.c \
$(LAPACKSRCDIR)/SRC/zsytf2_rook.c \
$(LAPACKSRCDIR)/SRC/zsytrf_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/zsytrf_aa.c \
$(LAPACKSRCDIR)/SRC/zsytrf.c \
$(LAPACKSRCDIR)/SRC/zsytrf_rk.c \
$(LAPACKSRCDIR)/SRC/zsytrf_rook.c \
$(LAPACKSRCDIR)/SRC/zsytri2.c \
$(LAPACKSRCDIR)/SRC/zsytri2x.c \
$(LAPACKSRCDIR)/SRC/zsytri_3.c \
$(LAPACKSRCDIR)/SRC/zsytri_3x.c \
$(LAPACKSRCDIR)/SRC/zsytri.c \
$(LAPACKSRCDIR)/SRC/zsytri_rook.c \
$(LAPACKSRCDIR)/SRC/zsytrs2.c \
$(LAPACKSRCDIR)/SRC/zsytrs_3.c \
$(LAPACKSRCDIR)/SRC/zsytrs_aa_2stage.c \
$(LAPACKSRCDIR)/SRC/zsytrs_aa.c \
$(LAPACKSRCDIR)/SRC/zsytrs.c \
$(LAPACKSRCDIR)/SRC/zsytrs_rook.c \
$(LAPACKSRCDIR)/SRC/ztbcon.c \
$(LAPACKSRCDIR)/SRC/ztbrfs.c \
$(LAPACKSRCDIR)/SRC/ztbtrs.c \
$(LAPACKSRCDIR)/SRC/ztfsm.c \
$(LAPACKSRCDIR)/SRC/ztftri.c \
$(LAPACKSRCDIR)/SRC/ztfttp.c \
$(LAPACKSRCDIR)/SRC/ztfttr.c \
$(LAPACKSRCDIR)/SRC/ztgevc.c \
$(LAPACKSRCDIR)/SRC/ztgex2.c \
$(LAPACKSRCDIR)/SRC/ztgexc.c \
$(LAPACKSRCDIR)/SRC/ztgsen.c \
$(LAPACKSRCDIR)/SRC/ztgsja.c \
$(LAPACKSRCDIR)/SRC/ztgsna.c \
$(LAPACKSRCDIR)/SRC/ztgsy2.c \
$(LAPACKSRCDIR)/SRC/ztgsyl.c \
$(LAPACKSRCDIR)/SRC/ztpcon.c \
$(LAPACKSRCDIR)/SRC/ztplqt2.c \
$(LAPACKSRCDIR)/SRC/ztplqt.c \
$(LAPACKSRCDIR)/SRC/ztpmlqt.c \
$(LAPACKSRCDIR)/SRC/ztpmqrt.c \
$(LAPACKSRCDIR)/SRC/ztpqrt2.c \
$(LAPACKSRCDIR)/SRC/ztpqrt.c \
$(LAPACKSRCDIR)/SRC/ztprfb.c \
$(LAPACKSRCDIR)/SRC/ztprfs.c \
$(LAPACKSRCDIR)/SRC/ztptri.c \
$(LAPACKSRCDIR)/SRC/ztptrs.c \
$(LAPACKSRCDIR)/SRC/ztpttf.c \
$(LAPACKSRCDIR)/SRC/ztpttr.c \
$(LAPACKSRCDIR)/SRC/ztrcon.c \
$(LAPACKSRCDIR)/SRC/ztrevc.c \
$(LAPACKSRCDIR)/SRC/ztrexc.c \
$(LAPACKSRCDIR)/SRC/ztrrfs.c \
$(LAPACKSRCDIR)/SRC/ztrsen.c \
$(LAPACKSRCDIR)/SRC/ztrsna.c \
$(LAPACKSRCDIR)/SRC/ztrsyl.c \
$(LAPACKSRCDIR)/SRC/ztrti2.c \
$(LAPACKSRCDIR)/SRC/ztrtri.c \
$(LAPACKSRCDIR)/SRC/ztrtrs.c \
$(LAPACKSRCDIR)/SRC/ztrttf.c \
$(LAPACKSRCDIR)/SRC/ztrttp.c \
$(LAPACKSRCDIR)/SRC/ztzrzf.c \
$(LAPACKSRCDIR)/SRC/zunbdb1.c \
$(LAPACKSRCDIR)/SRC/zunbdb2.c \
$(LAPACKSRCDIR)/SRC/zunbdb3.c \
$(LAPACKSRCDIR)/SRC/zunbdb4.c \
$(LAPACKSRCDIR)/SRC/zunbdb5.c \
$(LAPACKSRCDIR)/SRC/zunbdb6.c \
$(LAPACKSRCDIR)/SRC/zunbdb.c \
$(LAPACKSRCDIR)/SRC/zuncsd2by1.c \
$(LAPACKSRCDIR)/SRC/zuncsd.c \
$(LAPACKSRCDIR)/SRC/zung2l.c \
$(LAPACKSRCDIR)/SRC/zung2r.c \
$(LAPACKSRCDIR)/SRC/zungbr.c \
$(LAPACKSRCDIR)/SRC/zunghr.c \
$(LAPACKSRCDIR)/SRC/zungl2.c \
$(LAPACKSRCDIR)/SRC/zunglq.c \
$(LAPACKSRCDIR)/SRC/zungql.c \
$(LAPACKSRCDIR)/SRC/zungqr.c \
$(LAPACKSRCDIR)/SRC/zungr2.c \
$(LAPACKSRCDIR)/SRC/zungrq.c \
$(LAPACKSRCDIR)/SRC/zungtr.c \
$(LAPACKSRCDIR)/SRC/zunm22.c \
$(LAPACKSRCDIR)/SRC/zunm2l.c \
$(LAPACKSRCDIR)/SRC/zunm2r.c \
$(LAPACKSRCDIR)/SRC/zunmbr.c \
$(LAPACKSRCDIR)/SRC/zunmhr.c \
$(LAPACKSRCDIR)/SRC/zunml2.c \
$(LAPACKSRCDIR)/SRC/zunmlq.c \
$(LAPACKSRCDIR)/SRC/zunmql.c \
$(LAPACKSRCDIR)/SRC/zunmqr.c \
$(LAPACKSRCDIR)/SRC/zunmr2.c \
$(LAPACKSRCDIR)/SRC/zunmr3.c \
$(LAPACKSRCDIR)/SRC/zunmrq.c \
$(LAPACKSRCDIR)/SRC/zunmrz.c \
$(LAPACKSRCDIR)/SRC/zunmtr.c \
$(LAPACKSRCDIR)/SRC/zupgtr.c \
$(LAPACKSRCDIR)/SRC/zupmtr.c \
$(LAPACKSRCDIR)/BLAS/caxpy.c \
$(LAPACKSRCDIR)/BLAS/ccopy.c \
$(LAPACKSRCDIR)/BLAS/cdotc.c \
$(LAPACKSRCDIR)/BLAS/cdotu.c \
$(LAPACKSRCDIR)/BLAS/cgbmv.c \
$(LAPACKSRCDIR)/BLAS/cgemm.c \
$(LAPACKSRCDIR)/BLAS/cgemv.c \
$(LAPACKSRCDIR)/BLAS/cgerc.c \
$(LAPACKSRCDIR)/BLAS/cgeru.c \
$(LAPACKSRCDIR)/BLAS/chbmv.c \
$(LAPACKSRCDIR)/BLAS/chemm.c \
$(LAPACKSRCDIR)/BLAS/chemv.c \
$(LAPACKSRCDIR)/BLAS/cher2.c \
$(LAPACKSRCDIR)/BLAS/cher2k.c \
$(LAPACKSRCDIR)/BLAS/cher.c \
$(LAPACKSRCDIR)/BLAS/cherk.c \
$(LAPACKSRCDIR)/BLAS/chpmv.c \
$(LAPACKSRCDIR)/BLAS/chpr2.c \
$(LAPACKSRCDIR)/BLAS/chpr.c \
$(LAPACKSRCDIR)/BLAS/crotg.c \
$(LAPACKSRCDIR)/BLAS/cscal.c \
$(LAPACKSRCDIR)/BLAS/csrot.c \
$(LAPACKSRCDIR)/BLAS/csscal.c \
$(LAPACKSRCDIR)/BLAS/cswap.c \
$(LAPACKSRCDIR)/BLAS/csymm.c \
$(LAPACKSRCDIR)/BLAS/csyr2k.c \
$(LAPACKSRCDIR)/BLAS/csyrk.c \
$(LAPACKSRCDIR)/BLAS/ctbmv.c \
$(LAPACKSRCDIR)/BLAS/ctbsv.c \
$(LAPACKSRCDIR)/BLAS/ctpmv.c \
$(LAPACKSRCDIR)/BLAS/ctpsv.c \
$(LAPACKSRCDIR)/BLAS/ctrmm.c \
$(LAPACKSRCDIR)/BLAS/ctrmv.c \
$(LAPACKSRCDIR)/BLAS/ctrsm.c \
$(LAPACKSRCDIR)/BLAS/ctrsv.c \
$(LAPACKSRCDIR)/BLAS/dasum.c \
$(LAPACKSRCDIR)/BLAS/daxpy.c \
$(LAPACKSRCDIR)/BLAS/dcabs1.c \
$(LAPACKSRCDIR)/BLAS/dcopy.c \
$(LAPACKSRCDIR)/BLAS/ddot.c \
$(LAPACKSRCDIR)/BLAS/dgbmv.c \
$(LAPACKSRCDIR)/BLAS/dgemm.c \
$(LAPACKSRCDIR)/BLAS/dgemv.c \
$(LAPACKSRCDIR)/BLAS/dger.c \
$(LAPACKSRCDIR)/BLAS/dnrm2.c \
$(LAPACKSRCDIR)/BLAS/drot.c \
$(LAPACKSRCDIR)/BLAS/drotg.c \
$(LAPACKSRCDIR)/BLAS/drotm.c \
$(LAPACKSRCDIR)/BLAS/drotmg.c \
$(LAPACKSRCDIR)/BLAS/dsbmv.c \
$(LAPACKSRCDIR)/BLAS/dscal.c \
$(LAPACKSRCDIR)/BLAS/dsdot.c \
$(LAPACKSRCDIR)/BLAS/dspmv.c \
$(LAPACKSRCDIR)/BLAS/dspr2.c \
$(LAPACKSRCDIR)/BLAS/dspr.c \
$(LAPACKSRCDIR)/BLAS/dswap.c \
$(LAPACKSRCDIR)/BLAS/dsymm.c \
$(LAPACKSRCDIR)/BLAS/dsymv.c \
$(LAPACKSRCDIR)/BLAS/dsyr2.c \
$(LAPACKSRCDIR)/BLAS/dsyr2k.c \
$(LAPACKSRCDIR)/BLAS/dsyr.c \
$(LAPACKSRCDIR)/BLAS/dsyrk.c \
$(LAPACKSRCDIR)/BLAS/dtbmv.c \
$(LAPACKSRCDIR)/BLAS/dtbsv.c \
$(LAPACKSRCDIR)/BLAS/dtpmv.c \
$(LAPACKSRCDIR)/BLAS/dtpsv.c \
$(LAPACKSRCDIR)/BLAS/dtrmm.c \
$(LAPACKSRCDIR)/BLAS/dtrmv.c \
$(LAPACKSRCDIR)/BLAS/dtrsm.c \
$(LAPACKSRCDIR)/BLAS/dtrsv.c \
$(LAPACKSRCDIR)/BLAS/dzasum.c \
$(LAPACKSRCDIR)/BLAS/dznrm2.c \
$(LAPACKSRCDIR)/BLAS/icamax.c \
$(LAPACKSRCDIR)/BLAS/idamax.c \
$(LAPACKSRCDIR)/BLAS/isamax.c \
$(LAPACKSRCDIR)/BLAS/izamax.c \
$(LAPACKSRCDIR)/BLAS/lsame.c \
$(LAPACKSRCDIR)/BLAS/sasum.c \
$(LAPACKSRCDIR)/BLAS/saxpy.c \
$(LAPACKSRCDIR)/BLAS/scabs1.c \
$(LAPACKSRCDIR)/BLAS/scasum.c \
$(LAPACKSRCDIR)/BLAS/scnrm2.c \
$(LAPACKSRCDIR)/BLAS/scopy.c \
$(LAPACKSRCDIR)/BLAS/sdot.c \
$(LAPACKSRCDIR)/BLAS/sdsdot.c \
$(LAPACKSRCDIR)/BLAS/sgbmv.c \
$(LAPACKSRCDIR)/BLAS/sgemm.c \
$(LAPACKSRCDIR)/BLAS/sgemv.c \
$(LAPACKSRCDIR)/BLAS/sger.c \
$(LAPACKSRCDIR)/BLAS/snrm2.c \
$(LAPACKSRCDIR)/BLAS/srot.c \
$(LAPACKSRCDIR)/BLAS/srotg.c \
$(LAPACKSRCDIR)/BLAS/srotm.c \
$(LAPACKSRCDIR)/BLAS/srotmg.c \
$(LAPACKSRCDIR)/BLAS/ssbmv.c \
$(LAPACKSRCDIR)/BLAS/sscal.c \
$(LAPACKSRCDIR)/BLAS/sspmv.c \
$(LAPACKSRCDIR)/BLAS/sspr2.c \
$(LAPACKSRCDIR)/BLAS/sspr.c \
$(LAPACKSRCDIR)/BLAS/sswap.c \
$(LAPACKSRCDIR)/BLAS/ssymm.c \
$(LAPACKSRCDIR)/BLAS/ssymv.c \
$(LAPACKSRCDIR)/BLAS/ssyr2.c \
$(LAPACKSRCDIR)/BLAS/ssyr2k.c \
$(LAPACKSRCDIR)/BLAS/ssyr.c \
$(LAPACKSRCDIR)/BLAS/ssyrk.c \
$(LAPACKSRCDIR)/BLAS/stbmv.c \
$(LAPACKSRCDIR)/BLAS/stbsv.c \
$(LAPACKSRCDIR)/BLAS/stpmv.c \
$(LAPACKSRCDIR)/BLAS/stpsv.c \
$(LAPACKSRCDIR)/BLAS/strmm.c \
$(LAPACKSRCDIR)/BLAS/strmv.c \
$(LAPACKSRCDIR)/BLAS/strsm.c \
$(LAPACKSRCDIR)/BLAS/strsv.c \
$(LAPACKSRCDIR)/BLAS/zaxpy.c \
$(LAPACKSRCDIR)/BLAS/zcopy.c \
$(LAPACKSRCDIR)/BLAS/zdotc.c \
$(LAPACKSRCDIR)/BLAS/zdotu.c \
$(LAPACKSRCDIR)/BLAS/zdrot.c \
$(LAPACKSRCDIR)/BLAS/zdscal.c \
$(LAPACKSRCDIR)/BLAS/zgbmv.c \
$(LAPACKSRCDIR)/BLAS/zgemm.c \
$(LAPACKSRCDIR)/BLAS/zgemv.c \
$(LAPACKSRCDIR)/BLAS/zgerc.c \
$(LAPACKSRCDIR)/BLAS/zgeru.c \
$(LAPACKSRCDIR)/BLAS/zhbmv.c \
$(LAPACKSRCDIR)/BLAS/zhemm.c \
$(LAPACKSRCDIR)/BLAS/zhemv.c \
$(LAPACKSRCDIR)/BLAS/zher2.c \
$(LAPACKSRCDIR)/BLAS/zher2k.c \
$(LAPACKSRCDIR)/BLAS/zher.c \
$(LAPACKSRCDIR)/BLAS/zherk.c \
$(LAPACKSRCDIR)/BLAS/zhpmv.c \
$(LAPACKSRCDIR)/BLAS/zhpr2.c \
$(LAPACKSRCDIR)/BLAS/zhpr.c \
$(LAPACKSRCDIR)/BLAS/zrotg.c \
$(LAPACKSRCDIR)/BLAS/zscal.c \
$(LAPACKSRCDIR)/BLAS/zswap.c \
$(LAPACKSRCDIR)/BLAS/zsymm.c \
$(LAPACKSRCDIR)/BLAS/zsyr2k.c \
$(LAPACKSRCDIR)/BLAS/zsyrk.c \
$(LAPACKSRCDIR)/BLAS/ztbmv.c \
$(LAPACKSRCDIR)/BLAS/ztbsv.c \
$(LAPACKSRCDIR)/BLAS/ztpmv.c \
$(LAPACKSRCDIR)/BLAS/ztpsv.c \
$(LAPACKSRCDIR)/BLAS/ztrmm.c \
$(LAPACKSRCDIR)/BLAS/ztrmv.c \
$(LAPACKSRCDIR)/BLAS/ztrsm.c \
$(LAPACKSRCDIR)/BLAS/ztrsv.c \
$(LAPACKSRCDIR)/f2c.c \
$(LAPACKSRCDIR)/f2c_config.c \
$(LAPACKSRCDIR)/xerbla.c
