SOURCES_STATS_C:=$(STATSRCDIR)/ansari.c \
$(STATSRCDIR)/approx.c \
$(STATSRCDIR)/arima.c \
$(STATSRCDIR)/bandwidths.c \
$(STATSRCDIR)/bsplvd.c \
$(STATSRCDIR)/burg.c \
$(STATSRCDIR)/bvalue.c \
$(STATSRCDIR)/bvalus.c \
$(STATSRCDIR)/chisqsim.c \
$(STATSRCDIR)/complete_cases.c \
$(STATSRCDIR)/cov.c \
$(STATSRCDIR)/d2x2xk.c \
$(STATSRCDIR)/dblcen.c \
$(STATSRCDIR)/deriv.c \
$(STATSRCDIR)/distance.c \
$(STATSRCDIR)/distn.c \
$(STATSRCDIR)/eureka.c \
$(STATSRCDIR)/family.c \
$(STATSRCDIR)/fexact.c \
$(STATSRCDIR)/fft.c \
$(STATSRCDIR)/filters.c \
$(STATSRCDIR)/fourier.c \
$(STATSRCDIR)/hclust.c \
$(STATSRCDIR)/hclust-utils.c \
$(STATSRCDIR)/HoltWinters.c \
$(STATSRCDIR)/influence.c \
$(STATSRCDIR)/init.c \
$(STATSRCDIR)/integrate.c \
$(STATSRCDIR)/isoreg.c \
$(STATSRCDIR)/kendall.c \
$(STATSRCDIR)/kmeans.c \
$(STATSRCDIR)/kmns.c \
$(STATSRCDIR)/ks.c \
$(STATSRCDIR)/ksmooth.c \
$(STATSRCDIR)/line.c \
$(STATSRCDIR)/lm.c \
$(STATSRCDIR)/lminfl.c \
$(STATSRCDIR)/loessc.c \
$(STATSRCDIR)/loessf.c \
$(STATSRCDIR)/loglin.c \
$(STATSRCDIR)/lowess.c \
$(STATSRCDIR)/mAR.c \
$(STATSRCDIR)/massdist.c \
$(STATSRCDIR)/model.c \
$(STATSRCDIR)/monoSpl.c \
$(STATSRCDIR)/nls.c \
$(STATSRCDIR)/nscor.c \
$(STATSRCDIR)/optim.c \
$(STATSRCDIR)/optimize.c \
$(STATSRCDIR)/pacf.c \
$(STATSRCDIR)/port.c \
$(STATSRCDIR)/portsrc.c \
$(STATSRCDIR)/ppr.c \
$(STATSRCDIR)/PPsum.c \
$(STATSRCDIR)/prho.c \
$(STATSRCDIR)/qsbart.c \
$(STATSRCDIR)/random.c \
$(STATSRCDIR)/rcont.c \
$(STATSRCDIR)/rWishart.c \
$(STATSRCDIR)/sbart.c \
$(STATSRCDIR)/sgram.c \
$(STATSRCDIR)/sinerp.c \
$(STATSRCDIR)/smooth.c \
$(STATSRCDIR)/splines.c \
$(STATSRCDIR)/Srunmed.c \
$(STATSRCDIR)/sslvrg.c \
$(STATSRCDIR)/starma.c \
$(STATSRCDIR)/stl.c \
$(STATSRCDIR)/stxwx.c \
$(STATSRCDIR)/swilk.c \
$(STATSRCDIR)/Trunmed.c \
$(STATSRCDIR)/zeroin.c
