SOURCES_FT2_C:=$(FT2SRCDIR)/base/ftadvanc.c \
$(FT2SRCDIR)/base/ftbbox.c \
$(FT2SRCDIR)/base/ftbdf.c \
$(FT2SRCDIR)/base/ftbitmap.c \
$(FT2SRCDIR)/base/ftcalc.c \
$(FT2SRCDIR)/base/ftcid.c \
$(FT2SRCDIR)/base/ftcolor.c \
$(FT2SRCDIR)/base/ftdbgmem.c \
$(FT2SRCDIR)/base/ftdebug.c \
$(FT2SRCDIR)/base/fterrors.c \
$(FT2SRCDIR)/base/ftfntfmt.c \
$(FT2SRCDIR)/base/ftfstype.c \
$(FT2SRCDIR)/base/ftgasp.c \
$(FT2SRCDIR)/base/ftgloadr.c \
$(FT2SRCDIR)/base/ftglyph.c \
$(FT2SRCDIR)/base/ftgxval.c \
$(FT2SRCDIR)/base/fthash.c \
$(FT2SRCDIR)/base/ftinit.c \
$(FT2SRCDIR)/base/ftlcdfil.c \
$(FT2SRCDIR)/base/ftmm.c \
$(FT2SRCDIR)/base/ftobjs.c \
$(FT2SRCDIR)/base/ftotval.c \
$(FT2SRCDIR)/base/ftoutln.c \
$(FT2SRCDIR)/base/ftpatent.c \
$(FT2SRCDIR)/base/ftpfr.c \
$(FT2SRCDIR)/base/ftpsprop.c \
$(FT2SRCDIR)/base/ftrfork.c \
$(FT2SRCDIR)/base/ftsnames.c \
$(FT2SRCDIR)/base/ftstream.c \
$(FT2SRCDIR)/base/ftstroke.c \
$(FT2SRCDIR)/base/ftsynth.c \
$(FT2SRCDIR)/base/ftsystem.c \
$(FT2SRCDIR)/base/fttrigon.c \
$(FT2SRCDIR)/base/fttype1.c \
$(FT2SRCDIR)/base/ftutil.c \
$(FT2SRCDIR)/base/md5.c \
$(FT2SRCDIR)/type1/type1.c \
$(FT2SRCDIR)/sfnt/sfnt.c \
$(FT2SRCDIR)/truetype/truetype.c \
$(FT2SRCDIR)/gzip/ftgzip.c \
$(FT2SRCDIR)/raster/raster.c \
$(FT2SRCDIR)/smooth/smooth.c
#$(FT2SRCDIR)/base/ftbase.c \
