$(MODULESRCDIR)/xgboost/dmlc-core/src/io/azure_filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/hdfs_filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/indexed_recordio_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/input_split_base.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/line_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/local_filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/recordio_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/s3_filesys.cc \
