$(MODULESRCDIR)/pandas/_lib/algos.c \
$(MODULESRCDIR)/pandas/_lib/groupby.c \
$(MODULESRCDIR)/pandas/_lib/hashing.c \
$(MODULESRCDIR)/pandas/_lib/hashtable.c \
$(MODULESRCDIR)/pandas/_lib/index.c \
$(MODULESRCDIR)/pandas/_lib/indexing.c \
$(MODULESRCDIR)/pandas/_lib/internals.c \
$(MODULESRCDIR)/pandas/_lib/interval.c \
$(MODULESRCDIR)/pandas/_lib/join.c \
$(MODULESRCDIR)/pandas/_lib/lib.c \
$(MODULESRCDIR)/pandas/_lib/missing.c \
$(MODULESRCDIR)/pandas/_lib/ops.c \
$(MODULESRCDIR)/pandas/_lib/parsers.c \
$(MODULESRCDIR)/pandas/_lib/properties.c \
$(MODULESRCDIR)/pandas/_lib/reduction.c \
$(MODULESRCDIR)/pandas/_lib/reshape.c \
$(MODULESRCDIR)/pandas/_lib/skiplist.c \
$(MODULESRCDIR)/pandas/_lib/sparse.c \
$(MODULESRCDIR)/pandas/_lib/testing.c \
$(MODULESRCDIR)/pandas/_lib/tslib.c \
$(MODULESRCDIR)/pandas/_lib/writers.c \
