$(MODULESRCDIR)/xgboost/dmlc-core/src/io/filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/indexed_recordio_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/input_split_base.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/line_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/local_filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/recordio_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/config.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/data.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/recordio.cc \
$(MODULESRCDIR)/xgboost/src/linear/linear_updater.cc \
$(MODULESRCDIR)/xgboost/src/linear/updater_coordinate.cc \
$(MODULESRCDIR)/xgboost/src/linear/updater_shotgun.cc \
$(MODULESRCDIR)/xgboost/src/data/data.cc \
$(MODULESRCDIR)/xgboost/src/data/simple_csr_source.cc \
$(MODULESRCDIR)/xgboost/src/data/simple_dmatrix.cc \
$(MODULESRCDIR)/xgboost/src/data/sparse_page_dmatrix.cc \
$(MODULESRCDIR)/xgboost/src/data/sparse_page_raw_format.cc \
$(MODULESRCDIR)/xgboost/src/data/sparse_page_source.cc \
$(MODULESRCDIR)/xgboost/src/data/sparse_page_writer.cc \
$(MODULESRCDIR)/xgboost/src/predictor/cpu_predictor.cc \
$(MODULESRCDIR)/xgboost/src/predictor/predictor.cc \
$(MODULESRCDIR)/xgboost/src/cli_main.cc \
$(MODULESRCDIR)/xgboost/src/learner.cc \
$(MODULESRCDIR)/xgboost/src/logging.cc \
$(MODULESRCDIR)/xgboost/src/tree/split_evaluator.cc \
$(MODULESRCDIR)/xgboost/src/tree/tree_model.cc \
$(MODULESRCDIR)/xgboost/src/tree/tree_updater.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_colmaker.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_fast_hist.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_histmaker.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_prune.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_refresh.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_skmaker.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_sync.cc \
$(MODULESRCDIR)/xgboost/src/common/common.cc \
$(MODULESRCDIR)/xgboost/src/common/hist_util.cc \
$(MODULESRCDIR)/xgboost/src/common/host_device_vector.cc \
$(MODULESRCDIR)/xgboost/src/linear/elementwise_metric.cc \
$(MODULESRCDIR)/xgboost/src/linear/metric.cc \
$(MODULESRCDIR)/xgboost/src/linear/multiclass_metric.cc \
$(MODULESRCDIR)/xgboost/src/linear/rank_metric.cc \
$(MODULESRCDIR)/xgboost/src/c_api/c_api.cc \
$(MODULESRCDIR)/xgboost/src/c_api/c_api_error.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gblinear.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gbm.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gbtree.cc \
$(MODULESRCDIR)/xgboost/src/objective/hinge.cc \
$(MODULESRCDIR)/xgboost/src/objective/multiclass_obj.cc \
$(MODULESRCDIR)/xgboost/src/objective/objective.cc \
$(MODULESRCDIR)/xgboost/src/objective/rank_obj.cc \
$(MODULESRCDIR)/xgboost/src/objective/regression_obj.cc \
$(MODULESRCDIR)/xgboost/rabit/src/allreduce_base.cc \
$(MODULESRCDIR)/xgboost/rabit/src/allreduce_robust.cc \
$(MODULESRCDIR)/xgboost/rabit/src/c_api.cc \
$(MODULESRCDIR)/xgboost/rabit/src/engine.cc \
#$(MODULESRCDIR)/xgboost/rabit/src/engine_base.cc \
#$(MODULESRCDIR)/xgboost/rabit/src/engine_empty.cc \
#$(MODULESRCDIR)/xgboost/rabit/src/engine_mock.cc \
#$(MODULESRCDIR)/xgboost/rabit/src/engine_mpi.cc \
