$(MODULESRCDIR)/numpy/core/src/multiarray/alloc.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/array_assign_array.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/array_assign_scalar.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/arrayfunction_override.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/arrayobject.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/arraytypes.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/buffer.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/calculation.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/common.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/compiled_base.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/conversion_utils.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/convert.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/convert_datatype.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/ctors.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/datetime_busday.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/datetime_busdaycal.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/datetime.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/datetime_strings.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/descriptor.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/dragon4.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/dtype_transfer.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/einsum.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/flagsobject.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/getset.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/hashdescr.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/item_selection.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/iterators.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/lowlevel_strided_loops.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/mapping.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/methods.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/multiarraymodule.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/_multiarray_tests.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/nditer_api.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/nditer_constr.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/nditer_pywrap.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/nditer_templ.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/number.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/refcount.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/scalarapi.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/scalartypes.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/sequence.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/shape.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/strfuncs.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/temp_elide.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/typeinfo.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/usertypes.c \
$(MODULESRCDIR)/numpy/core/src/multiarray/vdot.c \
