/*
 * eth_def.h
 *
 *  Created on: Jul 9, 2018
 *      Author: accuser
 */

#ifndef GT_APP_INCLUDE_MSG_DEF_H_
#define GT_APP_INCLUDE_MSG_DEF_H_

#include <stdint.h>

#define ETH_ADDR_LEN 20
typedef struct _ethereum_addr_t {
	uint8_t addr[ETH_ADDR_LEN];
}eth_addr_t;


#define HOST_STAKEHOLDER_ID 1

typedef enum _enclave_status_t{
	NEW_SESSION_SUCCESS=1,
	NEW_SESSION_CREATING_ENCLAVE,
}enclave_status_t;

typedef enum _dapp_result_t
{
	RESULT_SUCCESS,
	RESULT_NO_ENCLAVE,
	RESULT_NO_MATCH, //no match enclave configured
	RESULT_NO_USER,
	RESULT_NO_CFG
}dapp_result_t;

typedef enum _dapp_msg_type_t
{
	TYPE_DAPP_REG,
	TYPE_DAPP_REG_RSP,
	TYPE_DAPP_ATT,
	SESSION_INIT=100,
	SESSION_INIT_RSP,
	SESSION_CONFIRM,
	SESSION_CONFIRM_RSP,
	SESSION_UNCONFIRMED,
	SESSION_INIT_CREATING_ENCLAVE,
	//SESSION_KEY_RSP,
	ATTESTATION=200,
	ATTESTATION_RSP_SUCCESS,
	ATTESTATION_RSP_FAIL,

	INSTALL_MODEL=300,
	INSTALL_MODEL_RSP_SUCCESS,
	INSTALL_MODEL_RSP_FAIL,

	START_TRAINING=400,
	START_TRAINING_RSP_SUCCESS,
	START_TRAINING_RSP_FAIL,
	STOP_TRAINING,
	STOP_TRAINING_RSP_SUCCESS,
	STOP_TRAINING_RSP_FAIL,

	GET_PREDICTION=500,
	GET_PREDICTION_RSP_SUCCESS,
	GET_PREDICTION_RSP_FAIL,

	CLONE_SEND=600,
	CLONE_SEND_RSP_SUCCESS,
	CLONE_SEND_RSP_FAIL,

	CLONE_RECEIVE=700,
	CLONE_RECEIVE_RSP_SUCCESS,
	CLONE_RECEIVE_RSP_FAIL,

	DI_GET_FILES=800,
	DI_GET_FILES_RSP_SUCCESS,
	DI_GET_FILES_RSP_FAIL,
	DI_GET_TABS,
	DI_GET_TABS_RSP_SUCCESS,
	DI_GET_TABS_RSP_FAIL,
	DI_GET_ATTRS,
	DI_GET_ATTRS_RSP_SUCCESS,
	DI_GET_ATTRS_RSP_FAIL,
	DI_GET_DATA=820,
	DI_GET_DATA_RSP_SUCCESS,
	DI_GET_DATA_RSP_FAIL,
	DV_GET_DATA=830,
	DV_GET_DATA_RSP_SUCCESS,
	DV_GET_DATA_RSP_FAIL,
	DV_GET_ALL_DATA=841,
	DV_GET_ALL_DATA_RSP_SUCCESS,
	DV_GET_ALL_DATA_RSP_FAIL,

	UPLOAD_MODEL=900,
	UPLOAD_MODEL_RSP_SUCCESS,
	UPLOAD_MODEL_RSP_FAIL,
	DNLOAD_MODEL,
	DNLOAD_MODEL_RSP_SUCCESS,
	DNLOAD_MODEL_RSP_FAIL,
	RUN_MODEL,
	RUN_MODEL_RSP_SUCCESS,
	RUN_MODEL_RSP_FAIL,
	DELETE_MODEL,
	DELETE_MODEL_RSP_SUCCESS,
	DELETE_MODEL_RSP_FAIL,
	RUN_MODEL_FILE,
	RUN_MODEL_FILE_RSP_SUCCESS,
	RUN_MODEL_FILE_RSP_FAIL,

	UPLOAD_DATA = 1000,
	UPLOAD_DATA_RSP_SUCCESS,
	UPLOAD_DATA_RSP_FAIL,
	DELETE_DATA,
	DELETE_DATA_RSP_SUCCESS,
	DELETE_DATA_RSP_FAIL,

	UPLOAD_DATA_E2E = 1010,
	UPLOAD_DATA_E2E_RSP_SUCCESS,
	UPLOAD_DATA_E2E_RSP_FAIL,

	GET_INFO = 1100,
	GET_INFO_RSP_SUCCESS,
	GET_INFO_RSP_FAIL,

	DIR_OP = 1110,
	DIR_OP_RSP_SUCCESS,
	DIR_OP_RSP_FAIL,

	SAVE_FILE = 1120,
	SAVE_FILE_RSP_SUCCESS,
	SAVE_FILE_RSP_FAIL,

	GET_TASK_STATUS = 1200,
	GET_TASK_STATUS_SUCCESS,
	GET_TASK_STATUS_FAIL,

	START_TASK_SUCCESS = 1205,
	START_TASK_FAIL,

	CLEAR_TASK_LIST = 1210,
	CLEAR_TASK_LIST_SUCCESS,
	CLEAR_TASK_LIST_FAIL,

	KILL_TASK = 1220,
	KILL_TASK_SUCCESS,
	KILL_TASK_FAIL,

	SHARE_DATA_TO_HOST = 1230,
	SHARE_DATA_TO_HOST_SUCCESS,
	SHARE_DATA_TO_HOST_FAIL,
	STOP_SHARE_DATA_TO_HOST,
	STOP_SHARE_DATA_TO_HOST_SUCCESS,
	STOP_SHARE_DATA_TO_HOST_FAIL,

	SHARE_DATA_TO_GUEST = 1240,
	SHARE_DATA_TO_GUEST_SUCCESS,
	SHARE_DATA_TO_GUEST_FAIL,
	STOP_SHARE_DATA_TO_GUEST,
	STOP_SHARE_DATA_TO_GUEST_SUCCESS,
	STOP_SHARE_DATA_TO_GUEST_FAIL,

	ADD_SUB_ENCLAVE = 1250,
	ADD_SUB_ENCLAVE_SUCCESS,
	ADD_SUB_ENCLAVE_FAIL,
	DEL_SUB_ENCLAVE,
	DEL_SUB_ENCLAVE_SUCCESS,
	DEL_SUB_ENCLAVE_FAIL,
	SEND_TO_SUB,
	SEND_TO_SUB_SUCCESS,
	SEND_TO_SUB_FAIL,

	ADD_GUEST_USER = 1260,
	ADD_GUEST_USER_SUCCESS,
	ADD_GUEST_USER_FAIL,
	GUEST_GET_PUB_DATA_INFO,
	GUEST_GET_PUB_DATA_INFO_SUCCESS,
	GUEST_GET_PUB_DATA_INFO_FAIL,

	RUN_FEDERATED_MODEL = 1270,
	RUN_FED_MODEL_RSP_SUCCESS,
	RUN_FED_MODEL_RSP_FAIL,

	RECEIVE_SUB_CODE = 1280,
    RECEIVE_SUB_CODE_SUCCESS,
    RECEIVE_SUB_CODE_FAIL,

	RUN_SUB_CODE_CYCLE = 1290,
	RUN_SUB_CODE_CYCLE_SUCCESS,
	RUN_SUB_CODE_CYCLE_FAIL,
	HOST_RUN_SUB_CODE_CYCLE,
	HOST_RUN_SUB_CODE_CYCLE_SUCCESS,
	HOST_RUN_SUB_CODE_CYCLE_FAIL,

	RUN_FED_MODEL_INIT = 1300,
	RUN_FED_MODEL_INIT_SUCCESS,
	RUN_FED_MODEL_INIT_FAIL,

	RUN_SUB_MODEL_INIT = 1310,
	RUN_SUB_MODEL_INIT_SUCCESS,
	RUN_SUB_MODEL_INIT_FAIL,

	SEND_TO_A_SUB = 1320,
	SEND_TO_A_SUB_SUCCESS,
	SEND_TO_A_SUB_FAIL,

	RUN_SUB_MDOEL = 1400,
	RUN_SUB_MDOEL_RSP_SUCCESS,
	RUN_SUB_MODEL_RSP_FAIL,

	RUN_SUB_OPAL = 1410,
	RUN_SUB_OPAL_RSP_SUCCESS,
	RUN_SUB_OPAL_RSP_FAIL,

	STREAM_PUSH = 1500,
	STREAM_PUSH_RSP_SUCCESS,
	STREAM_PUSH_RSP_FAIL,
/*
	REC_SUB_CODE_RSP_SUCCESS,
	REC_SUB_CODE_RSP_FAIL,
*/
	GET_TASK_RESULT,
	GET_TASK_RESULT_FAIL,
	GET_TASK_READY,
	GET_TASK_STILL_RUNNING,

	CREATE_ENCLAVE = 1600,
	CREATE_ENCLAVE_RSP_SUCCESS,
	CREATE_ENCLAVE_RSP_FAIL,

	RUN_MODEL_SANDBOX = 1700,
	RUN_MODEL_SANDBOX_SUCCESS,
	RUN_MODEL_SANDBOX_FAIL,

	UNKNOWN_MSG=10000,
	MSG_PREOCESS_ERR
}dapp_msg_type_t;

typedef enum _role_type_t {
	ROLE_RUNNER,
	ROLE_TRAINER,
	ROLE_DONOR,
	ROLE_DATA_SCIENTIST,
	ROLE_USER,
	ROLE_HOST = 1,
	ROLE_GUEST = 4
}role_type_t;

enum MyEnum
{
	GET_ACCESS_CODE = 0,
	GET_PREDICTIONx = 1
};

typedef enum _training_action_t {
	ACT_START_TRAINING,
	ACT_STOP_TRAINING,
	ACT_EXIT_TRAINING
}training_action_t;

#endif /* GT_APP_INCLUDE_MSG_DEF_H_ */
