$(ZLIBSRCDIR)/base/ftadvanc.c \
$(ZLIBSRCDIR)/base/ftbase.c \
$(ZLIBSRCDIR)/base/ftbbox.c \
$(ZLIBSRCDIR)/base/ftbdf.c \
$(ZLIBSRCDIR)/base/ftbitmap.c \
$(ZLIBSRCDIR)/base/ftcalc.c \
$(ZLIBSRCDIR)/base/ftcid.c \
$(ZLIBSRCDIR)/base/ftcolor.c \
$(ZLIBSRCDIR)/base/ftdbgmem.c \
$(ZLIBSRCDIR)/base/ftdebug.c \
$(ZLIBSRCDIR)/base/fterrors.c \
$(ZLIBSRCDIR)/base/ftfntfmt.c \
$(ZLIBSRCDIR)/base/ftfstype.c \
$(ZLIBSRCDIR)/base/ftgasp.c \
$(ZLIBSRCDIR)/base/ftgloadr.c \
$(ZLIBSRCDIR)/base/ftglyph.c \
$(ZLIBSRCDIR)/base/ftgxval.c \
$(ZLIBSRCDIR)/base/fthash.c \
$(ZLIBSRCDIR)/base/ftinit.c \
$(ZLIBSRCDIR)/base/ftlcdfil.c \
$(ZLIBSRCDIR)/base/ftmm.c \
$(ZLIBSRCDIR)/base/ftobjs.c \
$(ZLIBSRCDIR)/base/ftotval.c \
$(ZLIBSRCDIR)/base/ftoutln.c \
$(ZLIBSRCDIR)/base/ftpatent.c \
$(ZLIBSRCDIR)/base/ftpfr.c \
$(ZLIBSRCDIR)/base/ftpsprop.c \
$(ZLIBSRCDIR)/base/ftrfork.c \
$(ZLIBSRCDIR)/base/ftsnames.c \
$(ZLIBSRCDIR)/base/ftstream.c \
$(ZLIBSRCDIR)/base/ftstroke.c \
$(ZLIBSRCDIR)/base/ftsynth.c \
$(ZLIBSRCDIR)/base/ftsystem.c \
$(ZLIBSRCDIR)/base/fttrigon.c \
$(ZLIBSRCDIR)/base/fttype1.c \
$(ZLIBSRCDIR)/base/ftutil.c \
$(ZLIBSRCDIR)/base/md5.c \
