$(MODULESRCDIR)/numpy/core/src/umath/cpuid.c \
$(MODULESRCDIR)/numpy/core/src/umath/extobj.c \
$(MODULESRCDIR)/numpy/core/src/umath/loops.c \
$(MODULESRCDIR)/numpy/core/src/umath/matmul.c \
$(MODULESRCDIR)/numpy/core/src/umath/_operand_flag_tests.c \
$(MODULESRCDIR)/numpy/core/src/umath/override.c \
$(MODULESRCDIR)/numpy/core/src/umath/_rational_tests.c \
$(MODULESRCDIR)/numpy/core/src/umath/reduction.c \
$(MODULESRCDIR)/numpy/core/src/umath/scalarmath.c \
$(MODULESRCDIR)/numpy/core/src/umath/_struct_ufunc_tests.c \
$(MODULESRCDIR)/numpy/core/src/umath/ufunc_object.c \
$(MODULESRCDIR)/numpy/core/src/umath/ufunc_type_resolution.c \
$(MODULESRCDIR)/numpy/core/src/umath/umathmodule.c \
$(MODULESRCDIR)/numpy/core/src/umath/_umath_tests.c \
