$(MODULESRCDIR)/sklearn/decomposition/cdnmf_fast.c \
$(MODULESRCDIR)/sklearn/decomposition/_online_lda.c \
$(MODULESRCDIR)/sklearn/neighbors/ball_tree.c \
$(MODULESRCDIR)/sklearn/neighbors/dist_metrics.c \
$(MODULESRCDIR)/sklearn/neighbors/kd_tree.c \
$(MODULESRCDIR)/sklearn/neighbors/quad_tree.c \
$(MODULESRCDIR)/sklearn/neighbors/typedefs.c \
$(MODULESRCDIR)/sklearn/_isotonic.c \
$(MODULESRCDIR)/sklearn/__check_build/_k_means.c \
$(MODULESRCDIR)/sklearn/__check_build/_k_means_elkan.c \
$(MODULESRCDIR)/sklearn/feature_extraction/_hashing.c \
$(MODULESRCDIR)/sklearn/tree/_criterion.c \
$(MODULESRCDIR)/sklearn/tree/_splitter.c \
$(MODULESRCDIR)/sklearn/tree/_tree.c \
$(MODULESRCDIR)/sklearn/tree/_utils.c \
$(MODULESRCDIR)/sklearn/svm/liblinear.c \
$(MODULESRCDIR)/sklearn/svm/libsvm.c \
$(MODULESRCDIR)/sklearn/svm/libsvm_sparse.c \
$(MODULESRCDIR)/sklearn/svm/src/libsvm/libsvm_helper.c \
$(MODULESRCDIR)/sklearn/svm/src/libsvm/libsvm_sparse_helper.c \
$(MODULESRCDIR)/sklearn/manifold/_barnes_hut_tsne.c \
$(MODULESRCDIR)/sklearn/manifold/_utils.c \
$(MODULESRCDIR)/sklearn/datasets/_svmlight_format.c \
$(MODULESRCDIR)/sklearn/ensemble/_gradient_boosting.c \
$(MODULESRCDIR)/sklearn/metrics/pairwise_fast.c \
$(MODULESRCDIR)/sklearn/metrics/cluster/expected_mutual_info_fast.c \
$(MODULESRCDIR)/sklearn/utils/arrayfuncs.c \
$(MODULESRCDIR)/sklearn/utils/graph_shortest_path.c \
$(MODULESRCDIR)/sklearn/utils/lgamma.c \
$(MODULESRCDIR)/sklearn/utils/_logistic_sigmoid.c \
$(MODULESRCDIR)/sklearn/utils/murmurhash.c \
$(MODULESRCDIR)/sklearn/utils/_random.c \
$(MODULESRCDIR)/sklearn/utils/seq_dataset.c \
$(MODULESRCDIR)/sklearn/utils/sparsefuncs_fast.c \
$(MODULESRCDIR)/sklearn/utils/weight_vector.c \
$(MODULESRCDIR)/sklearn/utils/src/gamma.c \
$(MODULESRCDIR)/sklearn/__check_build/_check_build.c \
$(MODULESRCDIR)/sklearn/linear_model/cd_fast.c \
$(MODULESRCDIR)/sklearn/linear_model/sag_fast.c \
$(MODULESRCDIR)/sklearn/linear_model/sgd_fast.c \
