SOURCES_MODULES_CC:=$(MODULESRCDIR)/xgboost/dmlc-core/src/io/line_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/recordio_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/input_split_base.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/local_filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/filesys.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io/indexed_recordio_split.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/data.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/io.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/recordio.cc \
$(MODULESRCDIR)/xgboost/src/metric/metric.cc \
$(MODULESRCDIR)/xgboost/src/metric/elementwise_metric.cc \
$(MODULESRCDIR)/xgboost/src/metric/multiclass_metric.cc \
$(MODULESRCDIR)/xgboost/src/metric/rank_metric.cc \
$(MODULESRCDIR)/xgboost/src/metric/survival_metric.cc \
$(MODULESRCDIR)/xgboost/src/objective/objective.cc \
$(MODULESRCDIR)/xgboost/src/objective/regression_obj.cc \
$(MODULESRCDIR)/xgboost/src/objective/multiclass_obj.cc \
$(MODULESRCDIR)/xgboost/src/objective/rank_obj.cc \
$(MODULESRCDIR)/xgboost/src/objective/hinge.cc \
$(MODULESRCDIR)/xgboost/src/objective/aft_obj.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gbm.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gbtree.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gbtree_model.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gblinear.cc \
$(MODULESRCDIR)/xgboost/src/gbm/gblinear_model.cc \
$(MODULESRCDIR)/xgboost/src/data/data.cc \
$(MODULESRCDIR)/xgboost/src/data/simple_dmatrix.cc \
$(MODULESRCDIR)/xgboost/src/data/sparse_page_raw_format.cc \
$(MODULESRCDIR)/xgboost/src/data/ellpack_page.cc \
$(MODULESRCDIR)/xgboost/src/data/ellpack_page_source.cc \
$(MODULESRCDIR)/xgboost/src/predictor/predictor.cc \
$(MODULESRCDIR)/xgboost/src/predictor/cpu_predictor.cc \
$(MODULESRCDIR)/xgboost/src/tree/param.cc \
$(MODULESRCDIR)/xgboost/src/tree/split_evaluator.cc \
$(MODULESRCDIR)/xgboost/src/tree/tree_model.cc \
$(MODULESRCDIR)/xgboost/src/tree/tree_updater.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_colmaker.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_quantile_hist.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_prune.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_refresh.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_sync.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_histmaker.cc \
$(MODULESRCDIR)/xgboost/src/tree/updater_skmaker.cc \
$(MODULESRCDIR)/xgboost/src/tree/constraints.cc \
$(MODULESRCDIR)/xgboost/src/linear/linear_updater.cc \
$(MODULESRCDIR)/xgboost/src/linear/updater_coordinate.cc \
$(MODULESRCDIR)/xgboost/src/linear/updater_shotgun.cc \
$(MODULESRCDIR)/xgboost/src/learner.cc \
$(MODULESRCDIR)/xgboost/src/logging.cc \
$(MODULESRCDIR)/xgboost/src/common/common.cc \
$(MODULESRCDIR)/xgboost/src/common/timer.cc \
$(MODULESRCDIR)/xgboost/src/common/host_device_vector.cc \
$(MODULESRCDIR)/xgboost/src/common/hist_util.cc \
$(MODULESRCDIR)/xgboost/src/common/json.cc \
$(MODULESRCDIR)/xgboost/src/common/io.cc \
$(MODULESRCDIR)/xgboost/src/common/survival_util.cc \
$(MODULESRCDIR)/xgboost/src/common/probability_distribution.cc \
$(MODULESRCDIR)/xgboost/src/common/version.cc \
$(MODULESRCDIR)/xgboost/src/c_api/c_api.cc \
$(MODULESRCDIR)/xgboost/src/c_api/c_api_error.cc \
$(MODULESRCDIR)/xgboost/dmlc-core/src/std_thread_substitute.cc