SOURCES_MODULES_CPP:=$(MODULESRCDIR)/sklearn/cluster/_dbscan_inner.cpp \
$(MODULESRCDIR)/sklearn/cluster/_hierarchical.cpp \
$(MODULESRCDIR)/sklearn/svm/src/libsvm/libsvm_template.cpp \
$(MODULESRCDIR)/sklearn/svm/src/liblinear/linear.cpp \
$(MODULESRCDIR)/sklearn/svm/src/liblinear/tron.cpp \
$(MODULESRCDIR)/sklearn/utils/fast_dict.cpp \
$(MODULESRCDIR)/sklearn/utils/src/MurmurHash3.cpp \
$(MODULESRCDIR)/pandas/_libs/window.cpp \
$(MODULESRCDIR)/matplotlib/_backend_agg.cpp \
$(MODULESRCDIR)/matplotlib/_backend_agg_wrapper.cpp \
$(MODULESRCDIR)/matplotlib/_contour.cpp \
$(MODULESRCDIR)/matplotlib/_contour_wrapper.cpp \
$(MODULESRCDIR)/matplotlib/_image.cpp \
$(MODULESRCDIR)/matplotlib/_image_wrapper.cpp \
$(MODULESRCDIR)/matplotlib/mplutils.cpp \
$(MODULESRCDIR)/matplotlib/_path_wrapper.cpp \
$(MODULESRCDIR)/matplotlib/py_converters.cpp \
$(MODULESRCDIR)/matplotlib/_ttconv.cpp \
$(MODULESRCDIR)/matplotlib/path_cleanup.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_arc.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_arrowhead.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_bezier_arc.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_bspline.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_color_rgba.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_curves.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_embedded_raster_fonts.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_gsv_text.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_image_filters.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_line_aa_basics.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_line_profile_aa.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_rounded_rect.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_sqrt_tables.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_trans_affine.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_trans_double_path.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_trans_single_path.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_trans_warp_magnifier.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vcgen_bspline.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vcgen_contour.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vcgen_dash.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vcgen_markers_term.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vcgen_smooth_poly1.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vcgen_stroke.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vpgen_clip_polygon.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vpgen_clip_polyline.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/agg_vpgen_segmentator.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_bezier_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_cbox_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_gamma_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_gamma_spline.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_polygon_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_rbox_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_scale_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_slider_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/agg24-svn/src/ctrl/agg_spline_ctrl.cpp \
$(MODULESRCDIR)/matplotlib/extern/ttconv/pprdrv_tt2.cpp \
$(MODULESRCDIR)/matplotlib/extern/ttconv/pprdrv_tt.cpp \
$(MODULESRCDIR)/matplotlib/extern/ttconv/ttutil.cpp \
$(MODULESRCDIR)/matplotlib/_png.cpp \
$(MODULESRCDIR)/matplotlib/ft2font.cpp \
$(MODULESRCDIR)/matplotlib/ft2font_wrapper.cpp \
$(MODULESRCDIR)/kiwisolver/py/constraint.cpp \
$(MODULESRCDIR)/kiwisolver/py/expression.cpp \
$(MODULESRCDIR)/kiwisolver/py/kiwisolver.cpp \
$(MODULESRCDIR)/kiwisolver/py/solver.cpp \
$(MODULESRCDIR)/kiwisolver/py/strength.cpp \
$(MODULESRCDIR)/kiwisolver/py/term.cpp \
$(MODULESRCDIR)/kiwisolver/py/variable.cpp

