$(PY_BUILD)/$(MODULESRCDIR)/_federatedmodule.o: _federatedmodule.c \
 $(MODULESRCDIR)/../Include/Python.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/io.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(MODULESRCDIR)/../Include/patchlevel.h \
 $(MODULESRCDIR)/../Include/pyconfig.h \
 $(MODULESRCDIR)/../Include/pymacconfig.h \
 $(MODULESRCDIR)/../Include/pyport.h \
 $(MODULESRCDIR)/../Include/pymath.h \
 $(MODULESRCDIR)/../Include/pymem.h \
 $(MODULESRCDIR)/../Include/object.h \
 $(MODULESRCDIR)/../Include/objimpl.h \
 $(MODULESRCDIR)/../Include/pydebug.h \
 $(MODULESRCDIR)/../Include/unicodeobject.h \
 $(MODULESRCDIR)/../Include/intobject.h \
 $(MODULESRCDIR)/../Include/boolobject.h \
 $(MODULESRCDIR)/../Include/longobject.h \
 $(MODULESRCDIR)/../Include/floatobject.h \
 $(MODULESRCDIR)/../Include/complexobject.h \
 $(MODULESRCDIR)/../Include/rangeobject.h \
 $(MODULESRCDIR)/../Include/stringobject.h \
 $(MODULESRCDIR)/../Include/memoryobject.h \
 $(MODULESRCDIR)/../Include/bufferobject.h \
 $(MODULESRCDIR)/../Include/bytesobject.h \
 $(MODULESRCDIR)/../Include/bytearrayobject.h \
 $(MODULESRCDIR)/../Include/tupleobject.h \
 $(MODULESRCDIR)/../Include/listobject.h \
 $(MODULESRCDIR)/../Include/dictobject.h \
 $(MODULESRCDIR)/../Include/enumobject.h \
 $(MODULESRCDIR)/../Include/setobject.h \
 $(MODULESRCDIR)/../Include/methodobject.h \
 $(MODULESRCDIR)/../Include/moduleobject.h \
 $(MODULESRCDIR)/../Include/funcobject.h \
 $(MODULESRCDIR)/../Include/classobject.h \
 $(MODULESRCDIR)/../Include/fileobject.h \
 $(MODULESRCDIR)/../Include/cobject.h \
 $(MODULESRCDIR)/../Include/pycapsule.h \
 $(MODULESRCDIR)/../Include/traceback.h \
 $(MODULESRCDIR)/../Include/sliceobject.h \
 $(MODULESRCDIR)/../Include/cellobject.h \
 $(MODULESRCDIR)/../Include/iterobject.h \
 $(MODULESRCDIR)/../Include/genobject.h \
 $(MODULESRCDIR)/../Include/descrobject.h \
 $(MODULESRCDIR)/../Include/warnings.h \
 $(MODULESRCDIR)/../Include/weakrefobject.h \
 $(MODULESRCDIR)/../Include/codecs.h \
 $(MODULESRCDIR)/../Include/pyerrors.h \
 $(MODULESRCDIR)/../Include/pystate.h \
 $(MODULESRCDIR)/../Include/pyarena.h \
 $(MODULESRCDIR)/../Include/modsupport.h \
 $(MODULESRCDIR)/../Include/pythonrun.h \
 $(MODULESRCDIR)/../Include/ceval.h \
 $(MODULESRCDIR)/../Include/sysmodule.h \
 $(MODULESRCDIR)/../Include/intrcheck.h \
 $(MODULESRCDIR)/../Include/import.h \
 $(MODULESRCDIR)/../Include/abstract.h \
 $(MODULESRCDIR)/../Include/compile.h \
 $(MODULESRCDIR)/../Include/code.h \
 $(MODULESRCDIR)/../Include/eval.h \
 $(MODULESRCDIR)/../Include/pyctype.h \
 $(MODULESRCDIR)/../Include/pystrtod.h \
 $(MODULESRCDIR)/../Include/pystrcmp.h \
 $(MODULESRCDIR)/../Include/dtoa.h \
 $(MODULESRCDIR)/../Include/pyfpe.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/task_manager_enclave.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/../gt_enclave_t.h \
  $(MODULESRCDIR)/../../../gt_app/include/msg_def.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/cjson.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/session.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/cluster.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/enclave_def.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/data_management.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/vmoutput.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/../pyvm/Include/enclave_wrapper/io.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/../pyvm/Include/enclave_wrapper/sys.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/queue.h \
 $(MODULESRCDIR)/../../../gt_enclave/include/../../gt_enclave/gt_enclave_t.h
$(PY_BUILD)/$(MODULESRCDIR)/_httpsendmodule.o: _httpsendmodule.c \
 $(MODULESRCDIR)/../Include/Python.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/io.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/string_sgx.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/signal.h \
 $(MODULESRCDIR)/../Include/./enclave_wrapper/sys.h \
 $(MODULESRCDIR)/../Include/patchlevel.h \
 $(MODULESRCDIR)/../Include/pyconfig.h \
 $(MODULESRCDIR)/../Include/pymacconfig.h \
 $(MODULESRCDIR)/../Include/pyport.h \
 $(MODULESRCDIR)/../Include/pymath.h \
 $(MODULESRCDIR)/../Include/pymem.h \
 $(MODULESRCDIR)/../Include/object.h \
 $(MODULESRCDIR)/../Include/objimpl.h \
 $(MODULESRCDIR)/../Include/pydebug.h \
 $(MODULESRCDIR)/../Include/unicodeobject.h \
 $(MODULESRCDIR)/../Include/intobject.h \
 $(MODULESRCDIR)/../Include/boolobject.h \
 $(MODULESRCDIR)/../Include/longobject.h \
 $(MODULESRCDIR)/../Include/floatobject.h \
 $(MODULESRCDIR)/../Include/complexobject.h \
 $(MODULESRCDIR)/../Include/rangeobject.h \
 $(MODULESRCDIR)/../Include/stringobject.h \
 $(MODULESRCDIR)/../Include/memoryobject.h \
 $(MODULESRCDIR)/../Include/bufferobject.h \
 $(MODULESRCDIR)/../Include/bytesobject.h \
 $(MODULESRCDIR)/../Include/bytearrayobject.h \
 $(MODULESRCDIR)/../Include/tupleobject.h \
 $(MODULESRCDIR)/../Include/listobject.h \
 $(MODULESRCDIR)/../Include/dictobject.h \
 $(MODULESRCDIR)/../Include/enumobject.h \
 $(MODULESRCDIR)/../Include/setobject.h \
 $(MODULESRCDIR)/../Include/methodobject.h \
 $(MODULESRCDIR)/../Include/moduleobject.h \
 $(MODULESRCDIR)/../Include/funcobject.h \
 $(MODULESRCDIR)/../Include/classobject.h \
 $(MODULESRCDIR)/../Include/fileobject.h \
 $(MODULESRCDIR)/../Include/cobject.h \
 $(MODULESRCDIR)/../Include/pycapsule.h \
 $(MODULESRCDIR)/../Include/traceback.h \
 $(MODULESRCDIR)/../Include/sliceobject.h \
 $(MODULESRCDIR)/../Include/cellobject.h \
 $(MODULESRCDIR)/../Include/iterobject.h \
 $(MODULESRCDIR)/../Include/genobject.h \
 $(MODULESRCDIR)/../Include/descrobject.h \
 $(MODULESRCDIR)/../Include/warnings.h \
 $(MODULESRCDIR)/../Include/weakrefobject.h \
 $(MODULESRCDIR)/../Include/codecs.h \
 $(MODULESRCDIR)/../Include/pyerrors.h \
 $(MODULESRCDIR)/../Include/pystate.h \
 $(MODULESRCDIR)/../Include/pyarena.h \
 $(MODULESRCDIR)/../Include/modsupport.h \
 $(MODULESRCDIR)/../Include/pythonrun.h \
 $(MODULESRCDIR)/../Include/ceval.h \
 $(MODULESRCDIR)/../Include/sysmodule.h \
 $(MODULESRCDIR)/../Include/intrcheck.h \
 $(MODULESRCDIR)/../Include/import.h \
 $(MODULESRCDIR)/../Include/abstract.h \
 $(MODULESRCDIR)/../Include/compile.h \
 $(MODULESRCDIR)/../Include/code.h \
 $(MODULESRCDIR)/../Include/eval.h \
 $(MODULESRCDIR)/../Include/pyctype.h \
 $(MODULESRCDIR)/../Include/pystrtod.h \
 $(MODULESRCDIR)/../Include/pystrcmp.h \
 $(MODULESRCDIR)/../Include/dtoa.h \
 $(MODULESRCDIR)/../Include/pyfpe.h \
 $(MODULESRCDIR)/../../include/session.h  \
  $(MODULESRCDIR)/../../include/../gt_enclave_t.h \
 $(MODULESRCDIR)/../../../gt_app/include/msg_def.h  \
 $(MODULESRCDIR)/../../include/cluster.h $(MODULESRCDIR)/../../include/cjson.h \
 $(MODULESRCDIR)/../../include/enclave_def.h
