SOURCES_MODULES_CCX:=$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_house.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_qrpiv.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_sfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_snorm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_house.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_qrpiv.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_sfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_snorm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/prini.c \
$(MODULESRCDIR)/scipy/linalg/src/det.c \
$(MODULESRCDIR)/scipy/linalg/src/lu.c 