SOURCES_MODULES_CXX:=$(MODULESRCDIR)/scipy/sparse/sparsetools/bsr.cxx \
$(MODULESRCDIR)/scipy/sparse/sparsetools/csc.cxx \
$(MODULESRCDIR)/scipy/sparse/sparsetools/csr.cxx \
$(MODULESRCDIR)/scipy/sparse/sparsetools/other.cxx \
$(MODULESRCDIR)/scipy/sparse/sparsetools/sparsetools.cxx \
$(MODULESRCDIR)/scipy/special/_faddeeva.cxx \
$(MODULESRCDIR)/scipy/special/Faddeeva.cxx \
$(MODULESRCDIR)/scipy/special/_ufuncs_cxx.cxx \
$(MODULESRCDIR)/scipy/special/_wright.cxx \
$(MODULESRCDIR)/scipy/special/wright.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/build.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/count_neighbors.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/cpp_exc.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/globals.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/query_ball_point.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/query_ball_tree.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/query.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/query_pairs.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/sparse_distances.cxx \
$(MODULESRCDIR)/scipy/interpolate/src/_interpolate.cxx \
$(MODULESRCDIR)/scipy/spatial/ckdtree/src/ckdtree.cxx \
