$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cffti.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cosqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cosqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cosqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cost.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/costi.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rffti.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sint1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sint.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinti.c \
