$(MODULESRCDIR)/scipy/special/cephes/airy.c \
$(MODULESRCDIR)/scipy/special/cephes/bdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/beta.c \
$(MODULESRCDIR)/scipy/special/cephes/btdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/cbrt.c \
$(MODULESRCDIR)/scipy/special/cephes/chbevl.c \
$(MODULESRCDIR)/scipy/special/cephes/chdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/const.c \
$(MODULESRCDIR)/scipy/special/cephes/dawsn.c \
$(MODULESRCDIR)/scipy/special/cephes/dd_real.c \
$(MODULESRCDIR)/scipy/special/cephes/ellie.c \
$(MODULESRCDIR)/scipy/special/cephes/ellik.c \
$(MODULESRCDIR)/scipy/special/cephes/ellpe.c \
$(MODULESRCDIR)/scipy/special/cephes/ellpj.c \
$(MODULESRCDIR)/scipy/special/cephes/ellpk.c \
$(MODULESRCDIR)/scipy/special/cephes/exp10.c \
$(MODULESRCDIR)/scipy/special/cephes/exp2.c \
$(MODULESRCDIR)/scipy/special/cephes/expn.c \
$(MODULESRCDIR)/scipy/special/cephes/fdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/fresnl.c \
$(MODULESRCDIR)/scipy/special/cephes/gamma.c \
$(MODULESRCDIR)/scipy/special/cephes/gdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/hyp2f1.c \
$(MODULESRCDIR)/scipy/special/cephes/hyperg.c \
$(MODULESRCDIR)/scipy/special/cephes/i0.c \
$(MODULESRCDIR)/scipy/special/cephes/i1.c \
$(MODULESRCDIR)/scipy/special/cephes/igam.c \
$(MODULESRCDIR)/scipy/special/cephes/igami.c \
$(MODULESRCDIR)/scipy/special/cephes/incbet.c \
$(MODULESRCDIR)/scipy/special/cephes/incbi.c \
$(MODULESRCDIR)/scipy/special/cephes/j0.c \
$(MODULESRCDIR)/scipy/special/cephes/j1.c \
$(MODULESRCDIR)/scipy/special/cephes/jv.c \
$(MODULESRCDIR)/scipy/special/cephes/k0.c \
$(MODULESRCDIR)/scipy/special/cephes/k1.c \
$(MODULESRCDIR)/scipy/special/cephes/kn.c \
$(MODULESRCDIR)/scipy/special/cephes/kolmogorov.c \
$(MODULESRCDIR)/scipy/special/cephes/lanczos.c \
$(MODULESRCDIR)/scipy/special/cephes/mtherr.c \
$(MODULESRCDIR)/scipy/special/cephes/nbdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/ndtr.c \
$(MODULESRCDIR)/scipy/special/cephes/ndtri.c \
$(MODULESRCDIR)/scipy/special/cephes/owens_t.c \
$(MODULESRCDIR)/scipy/special/cephes/pdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/psi.c \
$(MODULESRCDIR)/scipy/special/cephes/rgamma.c \
$(MODULESRCDIR)/scipy/special/cephes/round.c \
$(MODULESRCDIR)/scipy/special/cephes/scipy_iv.c \
$(MODULESRCDIR)/scipy/special/cephes/shichi.c \
$(MODULESRCDIR)/scipy/special/cephes/sici.c \
$(MODULESRCDIR)/scipy/special/cephes/sindg.c \
$(MODULESRCDIR)/scipy/special/cephes/spence.c \
$(MODULESRCDIR)/scipy/special/cephes/stdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/tandg.c \
$(MODULESRCDIR)/scipy/special/cephes/tukey.c \
$(MODULESRCDIR)/scipy/special/cephes/unity.c \
$(MODULESRCDIR)/scipy/special/cephes/yn.c \
$(MODULESRCDIR)/scipy/special/cephes/yv.c \
$(MODULESRCDIR)/scipy/special/cephes/zeta.c \
$(MODULESRCDIR)/scipy/special/cephes/zetac.c \
