$(MODULESRCDIR)/pandas/io/sas/sas.c \
$(MODULESRCDIR)/pandas/_lib/algos.c \
$(MODULESRCDIR)/pandas/_lib/groupby.c \
$(MODULESRCDIR)/pandas/_lib/hashing.c \
$(MODULESRCDIR)/pandas/_lib/hashtable.c \
$(MODULESRCDIR)/pandas/_lib/index.c \
$(MODULESRCDIR)/pandas/_lib/indexing.c \
$(MODULESRCDIR)/pandas/_lib/internals.c \
$(MODULESRCDIR)/pandas/_lib/interval.c \
$(MODULESRCDIR)/pandas/_lib/join.c \
$(MODULESRCDIR)/pandas/_lib/lib.c \
$(MODULESRCDIR)/pandas/_lib/missing.c \
$(MODULESRCDIR)/pandas/_lib/ops.c \
$(MODULESRCDIR)/pandas/_lib/parsers.c \
$(MODULESRCDIR)/pandas/_lib/properties.c \
$(MODULESRCDIR)/pandas/_lib/reduction.c \
$(MODULESRCDIR)/pandas/_lib/reshape.c \
$(MODULESRCDIR)/pandas/_lib/skiplist.c \
$(MODULESRCDIR)/pandas/_lib/sparse.c \
$(MODULESRCDIR)/pandas/_lib/testing.c \
$(MODULESRCDIR)/pandas/_lib/tslib.c \
$(MODULESRCDIR)/pandas/_lib/writers.c \
$(MODULESRCDIR)/pandas/_lib/src/ujson/python/JSONtoObj.c \
$(MODULESRCDIR)/pandas/_lib/src/ujson/python/objToJSON.c \
$(MODULESRCDIR)/pandas/_lib/src/ujson/python/ujson.c \
$(MODULESRCDIR)/pandas/_lib/src/ujson/lib/ultrajsondec.c \
$(MODULESRCDIR)/pandas/_lib/src/ujson/lib/ultrajsonenc.c \
$(MODULESRCDIR)/pandas/_lib/src/parser/io.c \
$(MODULESRCDIR)/pandas/_lib/src/parser/tokenizer.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/ccalendar.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/conversion.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/fields.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/frequencies.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/nattype.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/np_datetime.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/offsets.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/parsing.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/period.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/resolution.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/strptime.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/timedeltas.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/timestamps.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/timezones.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/src/datetime/np_datetime.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/src/datetime/np_datetime_strings.c \
$(MODULESRCDIR)/pandas/util/move.c \
