$(MODULESRCDIR)/scipy/spatial/_hausdorff.c \
$(MODULESRCDIR)/scipy/spatial/qhull.c \
$(MODULESRCDIR)/scipy/spatial/_voronoi.c \
$(MODULESRCDIR)/scipy/spatial/src/distance_wrap.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/geom2_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/geom_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/global_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/io_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/libqhull_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/mem_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/merge_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/poly2_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/poly_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/qset_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/random_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/rboxlib_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/stat_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/usermem_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/userprintf_rbox_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/userprintf_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/user_r.c \
$(MODULESRCDIR)/scipy/io/matlab/mio5_utils.c \
$(MODULESRCDIR)/scipy/io/matlab/mio_utils.c \
$(MODULESRCDIR)/scipy/io/matlab/streams.c \
$(MODULESRCDIR)/scipy/fftpack/convolvemodule.c \
$(MODULESRCDIR)/scipy/fftpack/_fftpackmodule.c \
$(MODULESRCDIR)/scipy/fftpack/fortranobject.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cffti.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cosqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cosqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cosqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/cost.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/costi.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/rffti.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sint1.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sint.c \
$(MODULESRCDIR)/scipy/fftpack/src/fftpack/sinti.c \
$(MODULESRCDIR)/scipy/fftpack/src/convolve.c \
$(MODULESRCDIR)/scipy/fftpack/src/dct.c \
$(MODULESRCDIR)/scipy/fftpack/src/drfft.c \
$(MODULESRCDIR)/scipy/fftpack/src/dst.c \
$(MODULESRCDIR)/scipy/fftpack/src/zfft.c \
$(MODULESRCDIR)/scipy/fftpack/src/zfftnd.c \
$(MODULESRCDIR)/scipy/fftpack/src/zrfft.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcost.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosti.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dffti.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsint1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsint.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinti.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zffti.c \
$(MODULESRCDIR)/scipy/integrate/dop/dop853.c \
$(MODULESRCDIR)/scipy/integrate/dop/dopri5.c \
$(MODULESRCDIR)/scipy/integrate/_dopmodule.c \
$(MODULESRCDIR)/scipy/integrate/fortranobject.c \
$(MODULESRCDIR)/scipy/integrate/lsodamodule.c \
$(MODULESRCDIR)/scipy/integrate/_odepackmodule.c \
$(MODULESRCDIR)/scipy/integrate/_quadpackmodule.c \
$(MODULESRCDIR)/scipy/integrate/vodemodule.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqag.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqage.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagi.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagie.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagp.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagpe.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqags.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagse.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawc.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawce.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawf.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawfe.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawo.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawoe.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqaws.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawse.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqc25c.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqc25f.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqc25s.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqcheb.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqelg.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk15.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk15i.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk15w.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk21.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk31.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk41.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk51.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk61.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqmomo.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqng.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqpsrt.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqwgtc.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqwgtf.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqwgts.c \
$(MODULESRCDIR)/scipy/integrate/mach/d1mach.c \
$(MODULESRCDIR)/scipy/integrate/mach/xerror.c \
$(MODULESRCDIR)/scipy/integrate/odepack/blkdta000.c \
$(MODULESRCDIR)/scipy/integrate/odepack/bnorm.c \
$(MODULESRCDIR)/scipy/integrate/odepack/cfode.c \
$(MODULESRCDIR)/scipy/integrate/odepack/ewset.c \
$(MODULESRCDIR)/scipy/integrate/odepack/fnorm.c \
$(MODULESRCDIR)/scipy/integrate/odepack/intdy.c \
$(MODULESRCDIR)/scipy/integrate/odepack/lsoda.c \
$(MODULESRCDIR)/scipy/integrate/odepack/prja.c \
$(MODULESRCDIR)/scipy/integrate/odepack/solsy.c \
$(MODULESRCDIR)/scipy/integrate/odepack/srcma.c \
$(MODULESRCDIR)/scipy/integrate/odepack/stoda.c \
$(MODULESRCDIR)/scipy/integrate/odepack/vmnorm.c \
$(MODULESRCDIR)/scipy/integrate/odepack/vode.c \
$(MODULESRCDIR)/scipy/integrate/odepack/xerrwv.c \
$(MODULESRCDIR)/scipy/integrate/odepack/xsetf.c \
$(MODULESRCDIR)/scipy/integrate/odepack/xsetun.c \
$(MODULESRCDIR)/scipy/integrate/odepack/zvode.c \
$(MODULESRCDIR)/scipy/cluster/_hierarchy.c \
$(MODULESRCDIR)/scipy/cluster/_optimal_leaf_ordering.c \
$(MODULESRCDIR)/scipy/cluster/_vq.c \
$(MODULESRCDIR)/scipy/linalg/_blas_subroutine_wrappers.c \
$(MODULESRCDIR)/scipy/linalg/cython_blas.c \
$(MODULESRCDIR)/scipy/linalg/cython_lapack.c \
$(MODULESRCDIR)/scipy/linalg/_decomp_update.c \
$(MODULESRCDIR)/scipy/linalg/_fblas-f2pywrappers.c \
$(MODULESRCDIR)/scipy/linalg/_fblasmodule.c \
$(MODULESRCDIR)/scipy/linalg/_flapack-f2pywrappers.c \
$(MODULESRCDIR)/scipy/linalg/_flapackmodule.c \
$(MODULESRCDIR)/scipy/linalg/fortranobject.c \
$(MODULESRCDIR)/scipy/linalg/_interpolativemodule.c \
$(MODULESRCDIR)/scipy/linalg/_lapack_subroutine_wrappers.c \
$(MODULESRCDIR)/scipy/linalg/_solve_toeplitz.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_10.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_11.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_12.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_13.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_14.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_15.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_6.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_7.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_8.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_9.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_6.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_house.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_qrpiv.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_sfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_snorm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_10.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_11.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_6.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_7.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_8.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_9.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_house.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_qrpiv.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_sfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_snorm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/prini.c \
$(MODULESRCDIR)/scipy/linalg/src/det.c \
$(MODULESRCDIR)/scipy/linalg/src/lu.c \
$(MODULESRCDIR)/scipy/odr/__odrpack.c \
$(MODULESRCDIR)/scipy/odr/odrpack/d_lpkbls.c \
$(MODULESRCDIR)/scipy/odr/odrpack/d_lpk.c \
$(MODULESRCDIR)/scipy/odr/odrpack/dlunoc.c \
$(MODULESRCDIR)/scipy/odr/odrpack/d_mprec.c \
$(MODULESRCDIR)/scipy/odr/odrpack/d_odr.c \
$(MODULESRCDIR)/scipy/odr/odrpack/d_test.c \
$(MODULESRCDIR)/scipy/signal/bspline_util.c \
$(MODULESRCDIR)/scipy/signal/C_bspline_util.c \
$(MODULESRCDIR)/scipy/signal/correlate_nd.c \
$(MODULESRCDIR)/scipy/signal/D_bspline_util.c \
$(MODULESRCDIR)/scipy/signal/firfilter.c \
$(MODULESRCDIR)/scipy/signal/lfilter.c \
$(MODULESRCDIR)/scipy/signal/_max_len_seq_inner.c \
$(MODULESRCDIR)/scipy/signal/medianfilter.c \
$(MODULESRCDIR)/scipy/signal/_peak_finding_utils.c \
$(MODULESRCDIR)/scipy/signal/S_bspline_util.c \
$(MODULESRCDIR)/scipy/signal/sigtoolsmodule.c \
$(MODULESRCDIR)/scipy/signal/_spectral.c \
$(MODULESRCDIR)/scipy/signal/splinemodule.c \
$(MODULESRCDIR)/scipy/signal/_upfirdn_apply.c \
$(MODULESRCDIR)/scipy/signal/Z_bspline_util.c \
$(MODULESRCDIR)/scipy/stats/fortranobject.c \
$(MODULESRCDIR)/scipy/stats/mvndst.c \
$(MODULESRCDIR)/scipy/stats/mvn-f2pywrappers.c \
$(MODULESRCDIR)/scipy/stats/mvnmodule.c \
$(MODULESRCDIR)/scipy/stats/statlibmodule.c \
$(MODULESRCDIR)/scipy/stats/_stats.c \
$(MODULESRCDIR)/scipy/stats/statlib/ansari.c \
$(MODULESRCDIR)/scipy/stats/statlib/spearman.c \
$(MODULESRCDIR)/scipy/stats/statlib/swilk.c \
$(MODULESRCDIR)/scipy/ndimage/src/_ctest.c \
$(MODULESRCDIR)/scipy/ndimage/src/_cytest.c \
$(MODULESRCDIR)/scipy/ndimage/src/nd_image.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_filters.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_fourier.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_interpolation.c \
$(MODULESRCDIR)/scipy/ndimage/src/_ni_label.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_measure.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_morphology.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_splines.c \
$(MODULESRCDIR)/scipy/ndimage/src/ni_support.c \
$(MODULESRCDIR)/scipy/optimize/slsqp/fortranobject.c \
$(MODULESRCDIR)/scipy/optimize/slsqp/_slsqpmodule.c \
$(MODULESRCDIR)/scipy/optimize/slsqp/slsqp_optmz.c \
$(MODULESRCDIR)/scipy/optimize/cobyla/cobyla2.c \
$(MODULESRCDIR)/scipy/optimize/cobyla/_cobylamodule.c \
$(MODULESRCDIR)/scipy/optimize/cobyla/fortranobject.c \
$(MODULESRCDIR)/scipy/optimize/cobyla/trstlp.c \
$(MODULESRCDIR)/scipy/optimize/_trlib/_trlib.c \
$(MODULESRCDIR)/scipy/optimize/_trlib/trlib_eigen_inverse.c \
$(MODULESRCDIR)/scipy/optimize/_trlib/trlib_krylov.c \
$(MODULESRCDIR)/scipy/optimize/_trlib/trlib_leftmost.c \
$(MODULESRCDIR)/scipy/optimize/_trlib/trlib_quadratic_zero.c \
$(MODULESRCDIR)/scipy/optimize/_trlib/trlib_tri_factor.c \
$(MODULESRCDIR)/scipy/optimize/_group_columns.c \
$(MODULESRCDIR)/scipy/optimize/_minpackmodule.c \
$(MODULESRCDIR)/scipy/optimize/zeros.c \
$(MODULESRCDIR)/scipy/optimize/minpack2/dcsrch.c \
$(MODULESRCDIR)/scipy/optimize/minpack2/dcstep.c \
$(MODULESRCDIR)/scipy/optimize/minpack2/fortranobject.c \
$(MODULESRCDIR)/scipy/optimize/minpack2/minpack2module.c \
$(MODULESRCDIR)/scipy/optimize/nnls/fortranobject.c \
$(MODULESRCDIR)/scipy/optimize/nnls/nnls.c \
$(MODULESRCDIR)/scipy/optimize/nnls/_nnlsmodule.c \
$(MODULESRCDIR)/scipy/optimize/_lsq/givens_elimination.c \
$(MODULESRCDIR)/scipy/optimize/minpack/chkder.c \
$(MODULESRCDIR)/scipy/optimize/minpack/dogleg.c \
$(MODULESRCDIR)/scipy/optimize/minpack/dpmpar.c \
$(MODULESRCDIR)/scipy/optimize/minpack/enorm.c \
$(MODULESRCDIR)/scipy/optimize/minpack/fdjac1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/fdjac2.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrd1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrd.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrj1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrj.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmder1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmder.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmdif1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmdif.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmpar.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmstr1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmstr.c \
$(MODULESRCDIR)/scipy/optimize/minpack/qform.c \
$(MODULESRCDIR)/scipy/optimize/minpack/qrfac.c \
$(MODULESRCDIR)/scipy/optimize/minpack/qrsolv.c \
$(MODULESRCDIR)/scipy/optimize/minpack/r1mpyq.c \
$(MODULESRCDIR)/scipy/optimize/minpack/r1updt.c \
$(MODULESRCDIR)/scipy/optimize/minpack/rwupdt.c \
$(MODULESRCDIR)/scipy/optimize/tnc/example.c \
$(MODULESRCDIR)/scipy/optimize/tnc/moduleTNC.c \
$(MODULESRCDIR)/scipy/optimize/tnc/tnc.c \
$(MODULESRCDIR)/scipy/optimize/Zeros/bisect.c \
$(MODULESRCDIR)/scipy/optimize/Zeros/brenth.c \
$(MODULESRCDIR)/scipy/optimize/Zeros/brentq.c \
$(MODULESRCDIR)/scipy/optimize/Zeros/ridder.c \
$(MODULESRCDIR)/scipy/optimize/lbfgsb_src/fortranobject.c \
$(MODULESRCDIR)/scipy/optimize/lbfgsb_src/lbfgsb.c \
$(MODULESRCDIR)/scipy/optimize/lbfgsb_src/_lbfgsbmodule.c \
$(MODULESRCDIR)/scipy/optimize/lbfgsb_src/linpack.c \
$(MODULESRCDIR)/scipy/optimize/lbfgsb_src/timer.c \
$(MODULESRCDIR)/scipy/special/cdflib/algdiv.c \
$(MODULESRCDIR)/scipy/special/cdflib/alngam.c \
$(MODULESRCDIR)/scipy/special/cdflib/alnrel.c \
$(MODULESRCDIR)/scipy/special/cdflib/apser.c \
$(MODULESRCDIR)/scipy/special/cdflib/basym.c \
$(MODULESRCDIR)/scipy/special/cdflib/bcorr.c \
$(MODULESRCDIR)/scipy/special/cdflib/betaln.c \
$(MODULESRCDIR)/scipy/special/cdflib/bfrac.c \
$(MODULESRCDIR)/scipy/special/cdflib/bgrat.c \
$(MODULESRCDIR)/scipy/special/cdflib/bpser.c \
$(MODULESRCDIR)/scipy/special/cdflib/bratio.c \
$(MODULESRCDIR)/scipy/special/cdflib/brcmp1.c \
$(MODULESRCDIR)/scipy/special/cdflib/brcomp.c \
$(MODULESRCDIR)/scipy/special/cdflib/bup.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfbet.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfbin.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfchi.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfchn.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdff.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdffnc.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfgam.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfnbn.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfnor.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdfpoi.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdft.c \
$(MODULESRCDIR)/scipy/special/cdflib/cdftnc.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumbet.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumbin.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumchi.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumchn.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumf.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumfnc.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumgam.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumnbn.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumnor.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumpoi.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumt.c \
$(MODULESRCDIR)/scipy/special/cdflib/cumtnc.c \
$(MODULESRCDIR)/scipy/special/cdflib/devlpl.c \
$(MODULESRCDIR)/scipy/special/cdflib/dinvnr.c \
$(MODULESRCDIR)/scipy/special/cdflib/dinvr.c \
$(MODULESRCDIR)/scipy/special/cdflib/dt1.c \
$(MODULESRCDIR)/scipy/special/cdflib/dzror.c \
$(MODULESRCDIR)/scipy/special/cdflib/erf.c \
$(MODULESRCDIR)/scipy/special/cdflib/erfc1.c \
$(MODULESRCDIR)/scipy/special/cdflib/esum.c \
$(MODULESRCDIR)/scipy/special/cdflib/exparg.c \
$(MODULESRCDIR)/scipy/special/cdflib/fpser.c \
$(MODULESRCDIR)/scipy/special/cdflib/gam1.c \
$(MODULESRCDIR)/scipy/special/cdflib/gaminv.c \
$(MODULESRCDIR)/scipy/special/cdflib/gamln1.c \
$(MODULESRCDIR)/scipy/special/cdflib/gamln.c \
$(MODULESRCDIR)/scipy/special/cdflib/gamma_fort.c \
$(MODULESRCDIR)/scipy/special/cdflib/grat1.c \
$(MODULESRCDIR)/scipy/special/cdflib/gratio.c \
$(MODULESRCDIR)/scipy/special/cdflib/gsumln.c \
$(MODULESRCDIR)/scipy/special/cdflib/ipmpar.c \
$(MODULESRCDIR)/scipy/special/cdflib/psi_fort.c \
$(MODULESRCDIR)/scipy/special/cdflib/rcomp.c \
$(MODULESRCDIR)/scipy/special/cdflib/rexp.c \
$(MODULESRCDIR)/scipy/special/cdflib/rlog1.c \
$(MODULESRCDIR)/scipy/special/cdflib/rlog.c \
$(MODULESRCDIR)/scipy/special/cdflib/spmpar.c \
$(MODULESRCDIR)/scipy/special/cdflib/stvaln.c \
$(MODULESRCDIR)/scipy/special/c_misc/besselpoly.c \
$(MODULESRCDIR)/scipy/special/c_misc/gammasgn.c \
$(MODULESRCDIR)/scipy/special/c_misc/poch.c \
$(MODULESRCDIR)/scipy/special/c_misc/struve.c \
$(MODULESRCDIR)/scipy/special/specfun/specfun.c \
$(MODULESRCDIR)/scipy/spatial/amos_wrappers.c \
$(MODULESRCDIR)/scipy/spatial/cdf_wrappers.c \
$(MODULESRCDIR)/scipy/spatial/_comb.c \
$(MODULESRCDIR)/scipy/spatial/cython_special.c \
$(MODULESRCDIR)/scipy/spatial/_ellip_harm_2.c \
$(MODULESRCDIR)/scipy/spatial/fortranobject.c \
$(MODULESRCDIR)/scipy/spatial/_logit.c \
$(MODULESRCDIR)/scipy/spatial/sf_error.c \
$(MODULESRCDIR)/scipy/spatial/specfunmodule.c \
$(MODULESRCDIR)/scipy/spatial/specfun_wrappers.c \
$(MODULESRCDIR)/scipy/spatial/_test_round.c \
$(MODULESRCDIR)/scipy/spatial/_ufuncs.c \
$(MODULESRCDIR)/scipy/special/cephes/airy.c \
$(MODULESRCDIR)/scipy/special/cephes/bdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/beta.c \
$(MODULESRCDIR)/scipy/special/cephes/btdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/cbrt.c \
$(MODULESRCDIR)/scipy/special/cephes/chbevl.c \
$(MODULESRCDIR)/scipy/special/cephes/chdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/const.c \
$(MODULESRCDIR)/scipy/special/cephes/dawsn.c \
$(MODULESRCDIR)/scipy/special/cephes/dd_real.c \
$(MODULESRCDIR)/scipy/special/cephes/ellie.c \
$(MODULESRCDIR)/scipy/special/cephes/ellik.c \
$(MODULESRCDIR)/scipy/special/cephes/ellpe.c \
$(MODULESRCDIR)/scipy/special/cephes/ellpj.c \
$(MODULESRCDIR)/scipy/special/cephes/ellpk.c \
$(MODULESRCDIR)/scipy/special/cephes/exp10.c \
$(MODULESRCDIR)/scipy/special/cephes/exp2.c \
$(MODULESRCDIR)/scipy/special/cephes/expn.c \
$(MODULESRCDIR)/scipy/special/cephes/fdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/fresnl.c \
$(MODULESRCDIR)/scipy/special/cephes/gamma.c \
$(MODULESRCDIR)/scipy/special/cephes/gdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/hyp2f1.c \
$(MODULESRCDIR)/scipy/special/cephes/hyperg.c \
$(MODULESRCDIR)/scipy/special/cephes/i0.c \
$(MODULESRCDIR)/scipy/special/cephes/i1.c \
$(MODULESRCDIR)/scipy/special/cephes/igam.c \
$(MODULESRCDIR)/scipy/special/cephes/igami.c \
$(MODULESRCDIR)/scipy/special/cephes/incbet.c \
$(MODULESRCDIR)/scipy/special/cephes/incbi.c \
$(MODULESRCDIR)/scipy/special/cephes/j0.c \
$(MODULESRCDIR)/scipy/special/cephes/j1.c \
$(MODULESRCDIR)/scipy/special/cephes/jv.c \
$(MODULESRCDIR)/scipy/special/cephes/k0.c \
$(MODULESRCDIR)/scipy/special/cephes/k1.c \
$(MODULESRCDIR)/scipy/special/cephes/kn.c \
$(MODULESRCDIR)/scipy/special/cephes/kolmogorov.c \
$(MODULESRCDIR)/scipy/special/cephes/lanczos.c \
$(MODULESRCDIR)/scipy/special/cephes/mtherr.c \
$(MODULESRCDIR)/scipy/special/cephes/nbdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/ndtr.c \
$(MODULESRCDIR)/scipy/special/cephes/ndtri.c \
$(MODULESRCDIR)/scipy/special/cephes/owens_t.c \
$(MODULESRCDIR)/scipy/special/cephes/pdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/psi.c \
$(MODULESRCDIR)/scipy/special/cephes/rgamma.c \
$(MODULESRCDIR)/scipy/special/cephes/round.c \
$(MODULESRCDIR)/scipy/special/cephes/scipy_iv.c \
$(MODULESRCDIR)/scipy/special/cephes/shichi.c \
$(MODULESRCDIR)/scipy/special/cephes/sici.c \
$(MODULESRCDIR)/scipy/special/cephes/sindg.c \
$(MODULESRCDIR)/scipy/special/cephes/spence.c \
$(MODULESRCDIR)/scipy/special/cephes/stdtr.c \
$(MODULESRCDIR)/scipy/special/cephes/tandg.c \
$(MODULESRCDIR)/scipy/special/cephes/tukey.c \
$(MODULESRCDIR)/scipy/special/cephes/unity.c \
$(MODULESRCDIR)/scipy/special/cephes/yn.c \
$(MODULESRCDIR)/scipy/special/cephes/yv.c \
$(MODULESRCDIR)/scipy/special/cephes/zeta.c \
$(MODULESRCDIR)/scipy/special/cephes/zetac.c \
$(MODULESRCDIR)/scipy/special/amos/dgamln.c \
$(MODULESRCDIR)/scipy/special/amos/zabs.c \
$(MODULESRCDIR)/scipy/special/amos/zacai.c \
$(MODULESRCDIR)/scipy/special/amos/zacon.c \
$(MODULESRCDIR)/scipy/special/amos/zairy.c \
$(MODULESRCDIR)/scipy/special/amos/zasyi.c \
$(MODULESRCDIR)/scipy/special/amos/zbesh.c \
$(MODULESRCDIR)/scipy/special/amos/zbesi.c \
$(MODULESRCDIR)/scipy/special/amos/zbesj.c \
$(MODULESRCDIR)/scipy/special/amos/zbesk.c \
$(MODULESRCDIR)/scipy/special/amos/zbesy.c \
$(MODULESRCDIR)/scipy/special/amos/zbinu.c \
$(MODULESRCDIR)/scipy/special/amos/zbiry.c \
$(MODULESRCDIR)/scipy/special/amos/zbknu.c \
$(MODULESRCDIR)/scipy/special/amos/zbuni.c \
$(MODULESRCDIR)/scipy/special/amos/zbunk.c \
$(MODULESRCDIR)/scipy/special/amos/zdiv.c \
$(MODULESRCDIR)/scipy/special/amos/zexp.c \
$(MODULESRCDIR)/scipy/special/amos/zkscl.c \
$(MODULESRCDIR)/scipy/special/amos/zlog.c \
$(MODULESRCDIR)/scipy/special/amos/zmlri.c \
$(MODULESRCDIR)/scipy/special/amos/zmlt.c \
$(MODULESRCDIR)/scipy/special/amos/zrati.c \
$(MODULESRCDIR)/scipy/special/amos/zs1s2.c \
$(MODULESRCDIR)/scipy/special/amos/zseri.c \
$(MODULESRCDIR)/scipy/special/amos/zshch.c \
$(MODULESRCDIR)/scipy/special/amos/zsqrt.c \
$(MODULESRCDIR)/scipy/special/amos/zuchk.c \
$(MODULESRCDIR)/scipy/special/amos/zunhj.c \
$(MODULESRCDIR)/scipy/special/amos/zuni1.c \
$(MODULESRCDIR)/scipy/special/amos/zuni2.c \
$(MODULESRCDIR)/scipy/special/amos/zunik.c \
$(MODULESRCDIR)/scipy/special/amos/zunk1.c \
$(MODULESRCDIR)/scipy/special/amos/zunk2.c \
$(MODULESRCDIR)/scipy/special/amos/zuoik.c \
$(MODULESRCDIR)/scipy/special/amos/zwrsk.c \
$(MODULESRCDIR)/scipy/special/mach/d1mach.c \
$(MODULESRCDIR)/scipy/special/mach/i1mach.c \
$(MODULESRCDIR)/scipy/special/mach/xerror.c \
$(MODULESRCDIR)/scipy/_lib/_ccallback_c.c \
$(MODULESRCDIR)/scipy/_lib/_fpumode.c \
$(MODULESRCDIR)/scipy/_lib/messagestream.c \
$(MODULESRCDIR)/scipy/sparse/_csparsetools.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/_arpackmodule.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/fortranobject.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cgetv0.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaitr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnapps.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaup2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cnaupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cneigh.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cneupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cngets.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/csortc.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/cstatn.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dgetv0.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dnaitr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dnapps.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dnaup2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dnaupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dnconv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dneigh.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dneupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dngets.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsaitr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsapps.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsaup2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsaupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsconv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dseigt.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsesrt.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dseupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsgets.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsortc.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dsortr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dstatn.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dstats.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/dstqrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sgetv0.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/snaitr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/snapps.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/snaup2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/snaupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/snconv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sneigh.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sneupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sngets.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssaitr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssapps.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssaup2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssaupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssconv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sseigt.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssesrt.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sseupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssgets.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssortc.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/ssortr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sstatn.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sstats.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/sstqrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zgetv0.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/znaitr.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/znapps.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/znaup2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/znaupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zneigh.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zneupd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zngets.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zsortc.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/SRC/zstatn.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/cmout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/cvout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/dmout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/dvout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/icnteq.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/icopy.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/iset.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/iswap.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/ivout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/second_NONE.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/smout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/svout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/zmout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/eigen/arpack/ARPACK/UTIL/zvout.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/BiCGREVCOM.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/BiCGSTABREVCOM.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/CGREVCOM.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/CGSREVCOM.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/fortranobject.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/getbreak.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/GMRESREVCOM.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/_iterativemodule.c \
$(MODULESRCDIR)/scipy/sparse/linalg/isolve/iterative/QMRREVCOM.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/_superlumodule.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/_superluobject.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/_superlu_utils.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ccolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ccolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ccopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cdiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/clangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/claqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cmemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cmyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/colamd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/creadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/creadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/creadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cutil.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcomplex.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ddiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dlacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dlangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dlaqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dmach.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dmemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dmyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dreadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dreadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dreadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dutil.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dzsum1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/get_perm_c.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/heap_relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/icmax1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ccolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ccopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cdrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_csnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ddrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_heap_relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_scolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_scopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_sdrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_spanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_spivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ssnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zdrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/izmax1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/mark_relax.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/memory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/mmd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/qselect.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scomplex.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scsum1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sdiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/slacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/slangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/slaqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/smach.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/smemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/smyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sp_coletree.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sp_ienv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sp_preorder.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/superlu_timer.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sutil.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/util.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zcolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zdiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zlacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zlangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zlaqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zmemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zmyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zreadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zreadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zreadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zutil.c \
$(MODULESRCDIR)/scipy/sparse/csgraph/_min_spanning_tree.c \
$(MODULESRCDIR)/scipy/sparse/csgraph/_reordering.c \
$(MODULESRCDIR)/scipy/sparse/csgraph/_shortest_path.c \
$(MODULESRCDIR)/scipy/sparse/csgraph/_tools.c \
$(MODULESRCDIR)/scipy/sparse/csgraph/_traversal.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/bispeu.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/bispev.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/clocur.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/cocosp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/concon.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/concur.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/cualde.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/curev.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/curfit.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/dblint.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/evapol.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fourco.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpader.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpadno.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpadpo.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpback.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpbacp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpbfout.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpbisp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpbspl.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpchec.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpched.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpchep.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpclos.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcoco.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcons.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcosp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcsin.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcurf.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcuro.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcyt1.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpcyt2.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpdeno.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpdisc.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpfrno.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpgivs.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpgrdi.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpgrpa.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpgrre.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpgrsp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpinst.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpintb.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpknot.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpopdi.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpopsp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fporde.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fppara.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fppasu.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpperi.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fppocu.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fppogr.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fppola.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fprank.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fprati.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpregr.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fprota.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fprppo.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fprpsp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpseno.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpspgr.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpsphe.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpsuev.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpsurf.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fpsysy.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fptrnp.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fptrpe.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/insert.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/parcur.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/parder.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/pardeu.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/parsur.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/percur.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/pogrid.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/polar.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/profil.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/regrid.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/spalde.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/spgrid.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/sphere.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/splder.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/splev.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/splint.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/sproot.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/surev.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/surfit.c \
$(MODULESRCDIR)/scipy/interpolate/_bspl.c \
$(MODULESRCDIR)/scipy/interpolate/interpnd.c \
$(MODULESRCDIR)/scipy/interpolate/_ppoly.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/dfitpack-f2pywrappers.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/dfitpackmodule.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/_fitpackmodule.c \
$(MODULESRCDIR)/scipy/interpolate/fitpack/fortranobject.c \
