$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefasum.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefcopy.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefgemv.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefgemvN.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefgemvT.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefger.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefrot.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_drefrotg.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_dsrefdot.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefasum.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefcopy.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefgemv.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefgemvN.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefgemvT.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefger.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefnrm2.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefrot.c \
$(MODULESRCDIR)/sklearn/src/cblas/ATL_srefrotg.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_dasum.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_daxpy.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_dcopy.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_ddot.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_dgemv.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_dger.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_dnrm2.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_drot.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_drotg.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_dscal.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_errprn.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_sasum.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_saxpy.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_scopy.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_sdot.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_sgemv.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_sger.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_snrm2.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_srot.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_srotg.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_sscal.c \
$(MODULESRCDIR)/sklearn/src/cblas/cblas_xerbla.c \
