$(LAPACKSRCDIR)/BLAS/caxpy.o:$(LAPACKSRCDIR)/BLAS/caxpy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ccopy.o:$(LAPACKSRCDIR)/BLAS/ccopy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cdotc.o:$(LAPACKSRCDIR)/BLAS/cdotc.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cdotu.o:$(LAPACKSRCDIR)/BLAS/cdotu.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cgbmv.o:$(LAPACKSRCDIR)/BLAS/cgbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cgemm.o:$(LAPACKSRCDIR)/BLAS/cgemm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cgemv.o:$(LAPACKSRCDIR)/BLAS/cgemv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cgerc.o:$(LAPACKSRCDIR)/BLAS/cgerc.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cgeru.o:$(LAPACKSRCDIR)/BLAS/cgeru.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/chbmv.o:$(LAPACKSRCDIR)/BLAS/chbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/chemm.o:$(LAPACKSRCDIR)/BLAS/chemm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/chemv.o:$(LAPACKSRCDIR)/BLAS/chemv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cher2.o:$(LAPACKSRCDIR)/BLAS/cher2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cher2k.o:$(LAPACKSRCDIR)/BLAS/cher2k.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cher.o:$(LAPACKSRCDIR)/BLAS/cher.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cherk.o:$(LAPACKSRCDIR)/BLAS/cherk.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/chpmv.o:$(LAPACKSRCDIR)/BLAS/chpmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/chpr2.o:$(LAPACKSRCDIR)/BLAS/chpr2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/chpr.o:$(LAPACKSRCDIR)/BLAS/chpr.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/crotg.o:$(LAPACKSRCDIR)/BLAS/crotg.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cscal.o:$(LAPACKSRCDIR)/BLAS/cscal.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/csrot.o:$(LAPACKSRCDIR)/BLAS/csrot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/csscal.o:$(LAPACKSRCDIR)/BLAS/csscal.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/cswap.o:$(LAPACKSRCDIR)/BLAS/cswap.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/csymm.o:$(LAPACKSRCDIR)/BLAS/csymm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/csyr2k.o:$(LAPACKSRCDIR)/BLAS/csyr2k.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/csyrk.o:$(LAPACKSRCDIR)/BLAS/csyrk.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctbmv.o:$(LAPACKSRCDIR)/BLAS/ctbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctbsv.o:$(LAPACKSRCDIR)/BLAS/ctbsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctpmv.o:$(LAPACKSRCDIR)/BLAS/ctpmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctpsv.o:$(LAPACKSRCDIR)/BLAS/ctpsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctrmm.o:$(LAPACKSRCDIR)/BLAS/ctrmm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctrmv.o:$(LAPACKSRCDIR)/BLAS/ctrmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctrsm.o:$(LAPACKSRCDIR)/BLAS/ctrsm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ctrsv.o:$(LAPACKSRCDIR)/BLAS/ctrsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dasum.o:$(LAPACKSRCDIR)/BLAS/dasum.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/daxpy.o:$(LAPACKSRCDIR)/BLAS/daxpy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dcabs1.o:$(LAPACKSRCDIR)/BLAS/dcabs1.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dcopy.o:$(LAPACKSRCDIR)/BLAS/dcopy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ddot.o:$(LAPACKSRCDIR)/BLAS/ddot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dgbmv.o:$(LAPACKSRCDIR)/BLAS/dgbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dgemm.o:$(LAPACKSRCDIR)/BLAS/dgemm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dgemv.o:$(LAPACKSRCDIR)/BLAS/dgemv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dger.o:$(LAPACKSRCDIR)/BLAS/dger.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dnrm2.o:$(LAPACKSRCDIR)/BLAS/dnrm2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/drot.o:$(LAPACKSRCDIR)/BLAS/drot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/drotg.o:$(LAPACKSRCDIR)/BLAS/drotg.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/drotm.o:$(LAPACKSRCDIR)/BLAS/drotm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/drotmg.o:$(LAPACKSRCDIR)/BLAS/drotmg.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsbmv.o:$(LAPACKSRCDIR)/BLAS/dsbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dscal.o:$(LAPACKSRCDIR)/BLAS/dscal.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsdot.o:$(LAPACKSRCDIR)/BLAS/dsdot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dspmv.o:$(LAPACKSRCDIR)/BLAS/dspmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dspr2.o:$(LAPACKSRCDIR)/BLAS/dspr2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dspr.o:$(LAPACKSRCDIR)/BLAS/dspr.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dswap.o:$(LAPACKSRCDIR)/BLAS/dswap.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsymm.o:$(LAPACKSRCDIR)/BLAS/dsymm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsymv.o:$(LAPACKSRCDIR)/BLAS/dsymv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsyr2.o:$(LAPACKSRCDIR)/BLAS/dsyr2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsyr2k.o:$(LAPACKSRCDIR)/BLAS/dsyr2k.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsyr.o:$(LAPACKSRCDIR)/BLAS/dsyr.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dsyrk.o:$(LAPACKSRCDIR)/BLAS/dsyrk.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtbmv.o:$(LAPACKSRCDIR)/BLAS/dtbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtbsv.o:$(LAPACKSRCDIR)/BLAS/dtbsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtpmv.o:$(LAPACKSRCDIR)/BLAS/dtpmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtpsv.o:$(LAPACKSRCDIR)/BLAS/dtpsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtrmm.o:$(LAPACKSRCDIR)/BLAS/dtrmm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtrmv.o:$(LAPACKSRCDIR)/BLAS/dtrmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtrsm.o:$(LAPACKSRCDIR)/BLAS/dtrsm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dtrsv.o:$(LAPACKSRCDIR)/BLAS/dtrsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dzasum.o:$(LAPACKSRCDIR)/BLAS/dzasum.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/dznrm2.o:$(LAPACKSRCDIR)/BLAS/dznrm2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/icamax.o:$(LAPACKSRCDIR)/BLAS/icamax.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/idamax.o:$(LAPACKSRCDIR)/BLAS/idamax.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/isamax.o:$(LAPACKSRCDIR)/BLAS/isamax.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/izamax.o:$(LAPACKSRCDIR)/BLAS/izamax.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/lsame.o:$(LAPACKSRCDIR)/BLAS/lsame.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sasum.o:$(LAPACKSRCDIR)/BLAS/sasum.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/saxpy.o:$(LAPACKSRCDIR)/BLAS/saxpy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/scabs1.o:$(LAPACKSRCDIR)/BLAS/scabs1.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/scasum.o:$(LAPACKSRCDIR)/BLAS/scasum.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/scnrm2.o:$(LAPACKSRCDIR)/BLAS/scnrm2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/scopy.o:$(LAPACKSRCDIR)/BLAS/scopy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sdot.o:$(LAPACKSRCDIR)/BLAS/sdot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sdsdot.o:$(LAPACKSRCDIR)/BLAS/sdsdot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sgbmv.o:$(LAPACKSRCDIR)/BLAS/sgbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sgemm.o:$(LAPACKSRCDIR)/BLAS/sgemm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sgemv.o:$(LAPACKSRCDIR)/BLAS/sgemv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sger.o:$(LAPACKSRCDIR)/BLAS/sger.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/snrm2.o:$(LAPACKSRCDIR)/BLAS/snrm2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/srot.o:$(LAPACKSRCDIR)/BLAS/srot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/srotg.o:$(LAPACKSRCDIR)/BLAS/srotg.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/srotm.o:$(LAPACKSRCDIR)/BLAS/srotm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/srotmg.o:$(LAPACKSRCDIR)/BLAS/srotmg.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssbmv.o:$(LAPACKSRCDIR)/BLAS/ssbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sscal.o:$(LAPACKSRCDIR)/BLAS/sscal.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sspmv.o:$(LAPACKSRCDIR)/BLAS/sspmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sspr2.o:$(LAPACKSRCDIR)/BLAS/sspr2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sspr.o:$(LAPACKSRCDIR)/BLAS/sspr.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/sswap.o:$(LAPACKSRCDIR)/BLAS/sswap.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssymm.o:$(LAPACKSRCDIR)/BLAS/ssymm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssymv.o:$(LAPACKSRCDIR)/BLAS/ssymv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssyr2.o:$(LAPACKSRCDIR)/BLAS/ssyr2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssyr2k.o:$(LAPACKSRCDIR)/BLAS/ssyr2k.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssyr.o:$(LAPACKSRCDIR)/BLAS/ssyr.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ssyrk.o:$(LAPACKSRCDIR)/BLAS/ssyrk.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/stbmv.o:$(LAPACKSRCDIR)/BLAS/stbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/stbsv.o:$(LAPACKSRCDIR)/BLAS/stbsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/stpmv.o:$(LAPACKSRCDIR)/BLAS/stpmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/stpsv.o:$(LAPACKSRCDIR)/BLAS/stpsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/strmm.o:$(LAPACKSRCDIR)/BLAS/strmm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/strmv.o:$(LAPACKSRCDIR)/BLAS/strmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/strsm.o:$(LAPACKSRCDIR)/BLAS/strsm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/strsv.o:$(LAPACKSRCDIR)/BLAS/strsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zaxpy.o:$(LAPACKSRCDIR)/BLAS/zaxpy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zcopy.o:$(LAPACKSRCDIR)/BLAS/zcopy.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zdotc.o:$(LAPACKSRCDIR)/BLAS/zdotc.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zdotu.o:$(LAPACKSRCDIR)/BLAS/zdotu.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zdrot.o:$(LAPACKSRCDIR)/BLAS/zdrot.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zdscal.o:$(LAPACKSRCDIR)/BLAS/zdscal.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zgbmv.o:$(LAPACKSRCDIR)/BLAS/zgbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zgemm.o:$(LAPACKSRCDIR)/BLAS/zgemm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zgemv.o:$(LAPACKSRCDIR)/BLAS/zgemv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zgerc.o:$(LAPACKSRCDIR)/BLAS/zgerc.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zgeru.o:$(LAPACKSRCDIR)/BLAS/zgeru.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zhbmv.o:$(LAPACKSRCDIR)/BLAS/zhbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zhemm.o:$(LAPACKSRCDIR)/BLAS/zhemm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zhemv.o:$(LAPACKSRCDIR)/BLAS/zhemv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zher2.o:$(LAPACKSRCDIR)/BLAS/zher2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zher2k.o:$(LAPACKSRCDIR)/BLAS/zher2k.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zher.o:$(LAPACKSRCDIR)/BLAS/zher.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zherk.o:$(LAPACKSRCDIR)/BLAS/zherk.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zhpmv.o:$(LAPACKSRCDIR)/BLAS/zhpmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zhpr2.o:$(LAPACKSRCDIR)/BLAS/zhpr2.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zhpr.o:$(LAPACKSRCDIR)/BLAS/zhpr.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zrotg.o:$(LAPACKSRCDIR)/BLAS/zrotg.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zscal.o:$(LAPACKSRCDIR)/BLAS/zscal.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zswap.o:$(LAPACKSRCDIR)/BLAS/zswap.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zsymm.o:$(LAPACKSRCDIR)/BLAS/zsymm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zsyr2k.o:$(LAPACKSRCDIR)/BLAS/zsyr2k.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/zsyrk.o:$(LAPACKSRCDIR)/BLAS/zsyrk.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztbmv.o:$(LAPACKSRCDIR)/BLAS/ztbmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztbsv.o:$(LAPACKSRCDIR)/BLAS/ztbsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztpmv.o:$(LAPACKSRCDIR)/BLAS/ztpmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztpsv.o:$(LAPACKSRCDIR)/BLAS/ztpsv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztrmm.o:$(LAPACKSRCDIR)/BLAS/ztrmm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztrmv.o:$(LAPACKSRCDIR)/BLAS/ztrmv.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztrsm.o:$(LAPACKSRCDIR)/BLAS/ztrsm.c $(LAPACKSRCDIR)/../include/f2c.h 
$(LAPACKSRCDIR)/BLAS/ztrsv.o:$(LAPACKSRCDIR)/BLAS/ztrsv.c $(LAPACKSRCDIR)/../include/f2c.h 
