$(MODULESRCDIR)/pandas/_libs/tslibs/ccalendar.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/conversion.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/fields.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/frequencies.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/nattype.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/np_datetime.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/offsets.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/parsing.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/period.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/resolution.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/strptime.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/timedeltas.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/timestamps.c \
$(MODULESRCDIR)/pandas/_libs/tslibs/timezones.c \
