$(MODULESRCDIR)/scipy/optimize/minpack/chkder.c \
$(MODULESRCDIR)/scipy/optimize/minpack/dogleg.c \
$(MODULESRCDIR)/scipy/optimize/minpack/dpmpar.c \
$(MODULESRCDIR)/scipy/optimize/minpack/enorm.c \
$(MODULESRCDIR)/scipy/optimize/minpack/fdjac1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/fdjac2.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrd1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrd.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrj1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/hybrj.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmder1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmder.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmdif1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmdif.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmpar.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmstr1.c \
$(MODULESRCDIR)/scipy/optimize/minpack/lmstr.c \
$(MODULESRCDIR)/scipy/optimize/minpack/qform.c \
$(MODULESRCDIR)/scipy/optimize/minpack/qrfac.c \
$(MODULESRCDIR)/scipy/optimize/minpack/qrsolv.c \
$(MODULESRCDIR)/scipy/optimize/minpack/r1mpyq.c \
$(MODULESRCDIR)/scipy/optimize/minpack/r1updt.c \
$(MODULESRCDIR)/scipy/optimize/minpack/rwupdt.c \
