$(R_BUILD)/$(MAINSRCDIR)/deparse.o: deparse.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 RBufferUtils.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h 
$(R_BUILD)/$(MAINSRCDIR)/myconnections.o: myconnections.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
  $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
  $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rconnections.h $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h \
  $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h  \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Riconv.h $(MAINSRCDIR)/../include/R_ext/Print.h $(MAINSRCDIR)/../../gt_enclave_t.h \
 $(MAINSRCDIR)/../../../gt_app/include/msg_def.h \
  $(MAINSRCDIR)/../../include/data_management.h \
 $(MAINSRCDIR)/../../include/enclave_def.h $(MAINSRCDIR)/../../include/../gt_enclave_t.h 
$(R_BUILD)/$(MAINSRCDIR)/mysysutils.o: mysysutils.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Riconv.h \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h 
$(R_BUILD)/$(MAINSRCDIR)/RNG.o: RNG.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Random.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h \
 $(MAINSRCDIR)/../nmath/nmath2.h
$(R_BUILD)/$(MAINSRCDIR)/apply.o: apply.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/arithmetic.o: arithmetic.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 arithmetic.h 
$(R_BUILD)/$(MAINSRCDIR)/array.o: array.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Applic.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 duplicate.h complex.h  \
  Rcomplex.h complex.h \
 $(MAINSRCDIR)/../include/R_ext/Arith.h \
 $(MAINSRCDIR)/../include/R_ext/Random.h
$(R_BUILD)/$(MAINSRCDIR)/attrib.o: attrib.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h
$(R_BUILD)/$(MAINSRCDIR)/bind.o: bind.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 RBufferUtils.h duplicate.h
$(R_BUILD)/$(MAINSRCDIR)/builtin.o: builtin.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(MAINSRCDIR)/character.o: character.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 $(MAINSRCDIR)/../include/rlocale.h \
  RBufferUtils.h
$(R_BUILD)/$(MAINSRCDIR)/coerce.o: coerce.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h
$(R_BUILD)/$(MAINSRCDIR)/context.o: context.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/cum.o: cum.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/debug.o: debug.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/dstruct.o: dstruct.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(MAINSRCDIR)/duplicate.o: duplicate.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 duplicate.h
$(R_BUILD)/$(MAINSRCDIR)/envir.o: envir.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Callbacks.h \
 $(MAINSRCDIR)/../include/Rinternals.h
$(R_BUILD)/$(MAINSRCDIR)/errors.o: errors.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Startup.h \
 $(MAINSRCDIR)/../include/R_ext/RStartup.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/rlocale.h 
$(R_BUILD)/$(MAINSRCDIR)/eval.o: eval.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/Parse.h \
 $(MAINSRCDIR)/../include/R_ext/Parse.h \
 $(MAINSRCDIR)/../include/IOStuff.h
$(R_BUILD)/$(MAINSRCDIR)/format.o: format.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h
$(R_BUILD)/$(MAINSRCDIR)/gram.o: gram.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/IOStuff.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Parse.h \
 $(MAINSRCDIR)/../include/R_ext/Parse.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/rlocale.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h 
$(R_BUILD)/$(MAINSRCDIR)/identical.o: identical.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(MAINSRCDIR)/inlined.o: inlined.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(MAINSRCDIR)/inspect.o: inspect.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h
$(R_BUILD)/$(MAINSRCDIR)/iosupport.o: iosupport.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/IOStuff.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(MAINSRCDIR)/lapack.o: lapack.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Rdynpriv.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/Rmodules/Rlapack.h \
 $(MAINSRCDIR)/../include/Rinternals.h
$(R_BUILD)/$(MAINSRCDIR)/list.o: list.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/localecharset.o: localecharset.c \
 $(MAINSRCDIR)/../include/config.h 
$(R_BUILD)/$(MAINSRCDIR)/logic.o: logic.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h
$(R_BUILD)/$(MAINSRCDIR)/gtmain.o: gtmain.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/IOStuff.h \
 $(MAINSRCDIR)/../include/Parse.h \
 $(MAINSRCDIR)/../include/R_ext/Parse.h \
 $(MAINSRCDIR)/../include/Startup.h \
 $(MAINSRCDIR)/../include/R_ext/RStartup.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/rvm.h \
 $(MAINSRCDIR)/../include/../../include/vmoutput.h \
 $(MAINSRCDIR)/../../include/vmoutput.h $(MAINSRCDIR)/../../gt_enclave_t.h \
 $(MAINSRCDIR)/../../../gt_app/include/msg_def.h \
 $(MAINSRCDIR)/../include/initpkg.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/Rdynpriv.h \
 $(MAINSRCDIR)/../include/Lapack.h $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../randomForest/rf.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 testR.h
$(R_BUILD)/$(MAINSRCDIR)/mapply.o: mapply.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(MAINSRCDIR)/match.o: match.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(MAINSRCDIR)/memory.o: memory.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/R_ext/Rallocators.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 RBufferUtils.h
$(R_BUILD)/$(MAINSRCDIR)/Lapack.o: Lapack.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
  $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
  $(MAINSRCDIR)/../include/Lapack.h \
 $(MAINSRCDIR)/../include/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../../include/f2c.h $(MAINSRCDIR)/../../include/clapack.h $(MAINSRCDIR)/../../include/./f2c.h \
 $(MAINSRCDIR)/../include/Rmodules/Rlapack.h \
 $(MAINSRCDIR)/../include/Rinternals.h
$(R_BUILD)/$(MAINSRCDIR)/names.o: names.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 arithmetic.h \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h
$(R_BUILD)/$(MAINSRCDIR)/objects.o: objects.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(MAINSRCDIR)/options.o: options.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h
$(R_BUILD)/$(MAINSRCDIR)/paste.o: paste.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 RBufferUtils.h
$(R_BUILD)/$(MAINSRCDIR)/qsort.o: qsort.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Utils.h \
 qsort-body.c
$(R_BUILD)/$(MAINSRCDIR)/radixsort.o: radixsort.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/random.o: random.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 $(MAINSRCDIR)/../include/R_ext/Random.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/raw.o: raw.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(MAINSRCDIR)/registration.o: registration.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/R_ext/Applic.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Linpack.h \
 $(MAINSRCDIR)/../include/R_ext/BLAS.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Callbacks.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/Rdynpriv.h \
 basedecl.h
$(R_BUILD)/$(MAINSRCDIR)/relop.o: relop.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h
$(R_BUILD)/$(MAINSRCDIR)/scan.o: scan.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/rlocale.h \
  RBufferUtils.h
$(R_BUILD)/$(MAINSRCDIR)/seq.o: seq.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 RBufferUtils.h
$(R_BUILD)/$(MAINSRCDIR)/sort.o: sort.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(MAINSRCDIR)/source.o: source.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/IOStuff.h \
 $(MAINSRCDIR)/../include/Parse.h \
 $(MAINSRCDIR)/../include/R_ext/Parse.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h 
$(R_BUILD)/$(MAINSRCDIR)/split.o: split.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 split-incl.c
$(R_BUILD)/$(MAINSRCDIR)/sprintf.o: sprintf.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 RBufferUtils.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(MAINSRCDIR)/startup.o: startup.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Startup.h \
 $(MAINSRCDIR)/../include/R_ext/RStartup.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h
$(R_BUILD)/$(MAINSRCDIR)/subassign.o: subassign.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h
$(R_BUILD)/$(MAINSRCDIR)/subscript.o: subscript.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h
$(R_BUILD)/$(MAINSRCDIR)/subset.o: subset.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h
$(R_BUILD)/$(MAINSRCDIR)/summary.o: summary.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 duplicate.h
$(R_BUILD)/$(MAINSRCDIR)/times.o: times.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
  $(MAINSRCDIR)/../../gt_enclave_t.h \
 $(MAINSRCDIR)/../../../gt_app/include/msg_def.h 
$(R_BUILD)/$(MAINSRCDIR)/unique.o: unique.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/R_ext/Random.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h
$(R_BUILD)/$(MAINSRCDIR)/version.o: version.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rversion.h
$(R_BUILD)/$(MAINSRCDIR)/rlocale.o: rlocale.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/rlocale.h \
  rlocale_data.h \
 $(MAINSRCDIR)/../include/R_ext/Riconv.h
$(R_BUILD)/$(MAINSRCDIR)/printarray.o: printarray.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h
$(R_BUILD)/$(MAINSRCDIR)/printvector.o: printvector.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h
$(R_BUILD)/$(MAINSRCDIR)/Rmain.o: Rmain.c \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h 
$(R_BUILD)/$(MAINSRCDIR)/alloca.o: alloca.c \
 $(MAINSRCDIR)/../include/config.h
$(R_BUILD)/$(MAINSRCDIR)/strdup.o: strdup.c \
 $(MAINSRCDIR)/../include/config.h 
$(R_BUILD)/$(MAINSRCDIR)/strncasecmp.o: strncasecmp.c \
 $(MAINSRCDIR)/../include/config.h 
$(R_BUILD)/$(MAINSRCDIR)/util.o: util.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Riconv.h \
  valid_utf8.h \
 $(MAINSRCDIR)/../include/R_ext/Applic.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/Rmath.h 
$(R_BUILD)/$(MAINSRCDIR)/print.o: print.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(MAINSRCDIR)/printutils.o: printutils.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Print.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/R_ext/PrtUtil.h \
 $(MAINSRCDIR)/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/R_ext/Print.h \
 $(MAINSRCDIR)/../include/R_ext/RS.h \
 $(MAINSRCDIR)/../include/Rconfig.h \
 $(MAINSRCDIR)/../include/R_ext/Error.h \
 $(MAINSRCDIR)/../include/Rconnections.h \
 $(MAINSRCDIR)/../include/./R_ext/Connections.h \
 $(MAINSRCDIR)/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/./R_ext/../Rinternals.h \
  RBufferUtils.h \
 $(MAINSRCDIR)/../include/rvm.h $(MAINSRCDIR)/../include/../../include/vmoutput.h \
 $(MAINSRCDIR)/../include/rlocale.h 
$(R_BUILD)/$(MAINSRCDIR)/platform.o: platform.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rinterface.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h 
$(R_BUILD)/$(MAINSRCDIR)/Rdynload.o: Rdynload.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Rdynpriv.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h
$(R_BUILD)/$(MAINSRCDIR)/complex.o: complex.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 arithmetic.h complex.h  \
  Rcomplex.h \
 $(MAINSRCDIR)/../include/R_ext/Itermacros.h \
 $(MAINSRCDIR)/../include/R_ext/Arith.h \
 $(MAINSRCDIR)/../include/R_ext/Memory.h
$(R_BUILD)/$(MAINSRCDIR)/complexfun.o: complexfun.c complex.h 
$(R_BUILD)/$(MAINSRCDIR)/dotcode.o: dotcode.c \
 $(MAINSRCDIR)/../include/config.h \
 $(MAINSRCDIR)/../include/Defn.h \
 $(MAINSRCDIR)/../include/../include/R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/Rinternals.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Error.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Print.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(MAINSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(MAINSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(MAINSRCDIR)/../include/Errormsg.h \
 $(MAINSRCDIR)/../include/../include/R_ext/libextern.h \
 $(MAINSRCDIR)/../include/Internal.h \
 $(MAINSRCDIR)/../include/Rmath.h \
 $(MAINSRCDIR)/../include/R_ext/Boolean.h \
 $(MAINSRCDIR)/../include/Rdynpriv.h \
 $(MAINSRCDIR)/../include/R_ext/Rdynload.h
