$(MODULESRCDIR)/scipy/spatial/qhull_src/src/geom2_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/geom_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/global_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/io_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/libqhull_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/mem_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/merge_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/poly2_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/poly_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/qset_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/random_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/rboxlib_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/stat_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/usermem_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/userprintf_rbox_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/userprintf_r.c \
$(MODULESRCDIR)/scipy/spatial/qhull_src/src/user_r.c \
