$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcost.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dcosti.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dffti.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinqb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinqf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinqi.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsint1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsint.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/dsinti.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftb1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftb.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftf1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zfftf.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zffti1.c \
$(MODULESRCDIR)/scipy/fftpack/src/dfftpack/zffti.c \
