$(MODULESRCDIR)/scipy/integrate/quadpack/dqag.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqage.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagi.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagie.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagp.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagpe.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqags.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqagse.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawc.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawce.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawf.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawfe.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawo.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawoe.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqaws.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqawse.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqc25c.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqc25f.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqc25s.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqcheb.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqelg.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk15.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk15i.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk15w.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk21.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk31.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk41.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk51.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqk61.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqmomo.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqng.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqpsrt.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqwgtc.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqwgtf.c \
$(MODULESRCDIR)/scipy/integrate/quadpack/dqwgts.c \
