$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_10.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_11.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_12.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_13.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_14.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_15.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_6.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_7.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_8.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/dfft_subr_9.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_frm_subr_6.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_house.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id2svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_id.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddp_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_qrpiv.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/iddr_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_sfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_snorm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idd_svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rand_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_10.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_11.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_6.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_7.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_8.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/id_rtrans_subr_9.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_frm_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_house.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id2svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_id.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_4.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_aid_subr_5.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_asvd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzp_rsvd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_qrpiv.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_aid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_asvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rid.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idzr_rsvd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_sfft.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_snorm.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_0.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_1.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_2.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/idz_svd_subr_3.c \
$(MODULESRCDIR)/scipy/linalg/src/id_dist/src/prini.c \
