/* _blas_subroutine_wrappers.f -- translated by f2c (version 20160102).
   You must link the resulting object file with libf2c:
	on Microsoft Windows system, link with libf2c.lib;
	on Linux or Unix systems, link with .../path/to/libf2c.a -lm
	or, if you install libf2c.a in a standard place, with -lf2c -lm
	-- in that order, at the end of the command line, as in
		cc *.o -lf2c -lm
	Source for libf2c is in /netlib/f2c/libf2c.zip, e.g.,

		http://www.netlib.org/f2c/libf2c.zip
*/

#include "f2c.h"

/*     This file was generated by _generate_pyx.py. */
/*     Do not edit this file directly. */
/* Subroutine */ int cdotcwrp_(complex *ret, integer *n, complex *cx, integer 
	*incx, complex *cy, integer *incy)
{
    /* System generated locals */
    complex q__1;

    /* Local variables */
    extern /* Complex */ VOID cdotc_(complex *, integer *, complex *,
	    integer *, complex *, integer *);

    /* Parameter adjustments */
    --cy;
    --cx;

    /* Function Body */
    cdotc_(&q__1, n, &cx[1], incx, &cy[1], incy);
    ret->r = q__1.r, ret->i = q__1.i;
    return 0;
} /* cdotcwrp_ */

/* Subroutine */ int cdotuwrp_(complex *ret, integer *n, complex *cx, integer 
	*incx, complex *cy, integer *incy)
{
    /* System generated locals */
    complex q__1;

    /* Local variables */
    extern /* Complex */ VOID cdotu_(complex *, integer *, complex *,
	    integer *, complex *, integer *);

    /* Parameter adjustments */
    --cy;
    --cx;

    /* Function Body */
    cdotu_(&q__1, n, &cx[1], incx, &cy[1], incy);
    ret->r = q__1.r, ret->i = q__1.i;
    return 0;
} /* cdotuwrp_ */

/* Subroutine */ int dasumwrp_(doublereal *ret, integer *n, doublereal *dx, 
	integer *incx)
{
    extern doublereal dasum_(integer *, doublereal *, integer *);

    /* Parameter adjustments */
    --dx;

    /* Function Body */
    *ret = dasum_(n, &dx[1], incx);
    return 0;
} /* dasumwrp_ */

/* Subroutine */ int dcabs1wrp_(doublereal *ret, doublecomplex *z__)
{
    extern doublereal dcabs1_(doublecomplex *);

    *ret = dcabs1_(z__);
    return 0;
} /* dcabs1wrp_ */

/* Subroutine */ int ddotwrp_(doublereal *ret, integer *n, doublereal *dx, 
	integer *incx, doublereal *dy, integer *incy)
{
    extern doublereal ddot_(integer *, doublereal *, integer *, doublereal *, 
	    integer *);

    /* Parameter adjustments */
    --dy;
    --dx;

    /* Function Body */
    *ret = ddot_(n, &dx[1], incx, &dy[1], incy);
    return 0;
} /* ddotwrp_ */

/* Subroutine */ int dnrm2wrp_(doublereal *ret, integer *n, doublereal *x, 
	integer *incx)
{
    extern doublereal dnrm2_(integer *, doublereal *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *ret = dnrm2_(n, &x[1], incx);
    return 0;
} /* dnrm2wrp_ */

/* Subroutine */ int dsdotwrp_(doublereal *ret, integer *n, real *sx, integer 
	*incx, real *sy, integer *incy)
{
    extern doublereal dsdot_(integer *, real *, integer *, real *, integer *);

    /* Parameter adjustments */
    --sy;
    --sx;

    /* Function Body */
    *ret = dsdot_(n, &sx[1], incx, &sy[1], incy);
    return 0;
} /* dsdotwrp_ */

/* Subroutine */ int dzasumwrp_(doublereal *ret, integer *n, doublecomplex *
	zx, integer *incx)
{
    extern doublereal dzasum_(integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --zx;

    /* Function Body */
    *ret = dzasum_(n, &zx[1], incx);
    return 0;
} /* dzasumwrp_ */

/* Subroutine */ int dznrm2wrp_(doublereal *ret, integer *n, doublecomplex *x,
	 integer *incx)
{
    extern doublereal dznrm2_(integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *ret = dznrm2_(n, &x[1], incx);
    return 0;
} /* dznrm2wrp_ */

/* Subroutine */ int icamaxwrp_(integer *ret, integer *n, complex *cx, 
	integer *incx)
{
    extern integer icamax_(integer *, complex *, integer *);

    /* Parameter adjustments */
    --cx;

    /* Function Body */
    *ret = icamax_(n, &cx[1], incx);
    return 0;
} /* icamaxwrp_ */

/* Subroutine */ int idamaxwrp_(integer *ret, integer *n, doublereal *dx, 
	integer *incx)
{
    extern integer idamax_(integer *, doublereal *, integer *);

    /* Parameter adjustments */
    --dx;

    /* Function Body */
    *ret = idamax_(n, &dx[1], incx);
    return 0;
} /* idamaxwrp_ */

/* Subroutine */ int isamaxwrp_(integer *ret, integer *n, real *sx, integer *
	incx)
{
    extern integer isamax_(integer *, real *, integer *);

    /* Parameter adjustments */
    --sx;

    /* Function Body */
    *ret = isamax_(n, &sx[1], incx);
    return 0;
} /* isamaxwrp_ */

/* Subroutine */ int izamaxwrp_(integer *ret, integer *n, doublecomplex *zx, 
	integer *incx)
{
    extern integer izamax_(integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --zx;

    /* Function Body */
    *ret = izamax_(n, &zx[1], incx);
    return 0;
} /* izamaxwrp_ */

/* Subroutine */ int lsamewrp_(logical *ret, char *ca, char *cb, ftnlen 
	ca_len, ftnlen cb_len)
{
    extern logical lsame_(char *, char *, ftnlen, ftnlen);

    *ret = lsame_(ca, cb, (ftnlen)1, (ftnlen)1);
    return 0;
} /* lsamewrp_ */

/* Subroutine */ int sasumwrp_(real *ret, integer *n, real *sx, integer *incx)
{
    extern doublereal sasum_(integer *, real *, integer *);

    /* Parameter adjustments */
    --sx;

    /* Function Body */
    *ret = sasum_(n, &sx[1], incx);
    return 0;
} /* sasumwrp_ */

/* Subroutine */ int scasumwrp_(real *ret, integer *n, complex *cx, integer *
	incx)
{
    extern doublereal scasum_(integer *, complex *, integer *);

    /* Parameter adjustments */
    --cx;

    /* Function Body */
    *ret = scasum_(n, &cx[1], incx);
    return 0;
} /* scasumwrp_ */

/* Subroutine */ int scnrm2wrp_(real *ret, integer *n, complex *x, integer *
	incx)
{
    extern doublereal scnrm2_(integer *, complex *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *ret = scnrm2_(n, &x[1], incx);
    return 0;
} /* scnrm2wrp_ */

/* Subroutine */ int sdotwrp_(real *ret, integer *n, real *sx, integer *incx, 
	real *sy, integer *incy)
{
    extern doublereal sdot_(integer *, real *, integer *, real *, integer *);

    /* Parameter adjustments */
    --sy;
    --sx;

    /* Function Body */
    *ret = sdot_(n, &sx[1], incx, &sy[1], incy);
    return 0;
} /* sdotwrp_ */

/* Subroutine */ int sdsdotwrp_(real *ret, integer *n, real *sb, real *sx, 
	integer *incx, real *sy, integer *incy)
{
    extern doublereal sdsdot_(integer *, real *, real *, integer *, real *, 
	    integer *);

    /* Parameter adjustments */
    --sy;
    --sx;

    /* Function Body */
    *ret = sdsdot_(n, sb, &sx[1], incx, &sy[1], incy);
    return 0;
} /* sdsdotwrp_ */

/* Subroutine */ int snrm2wrp_(real *ret, integer *n, real *x, integer *incx)
{
    extern doublereal snrm2_(integer *, real *, integer *);

    /* Parameter adjustments */
    --x;

    /* Function Body */
    *ret = snrm2_(n, &x[1], incx);
    return 0;
} /* snrm2wrp_ */

/* Subroutine */ int zdotcwrp_(doublecomplex *ret, integer *n, doublecomplex *
	zx, integer *incx, doublecomplex *zy, integer *incy)
{
    /* System generated locals */
    doublecomplex z__1;

    /* Local variables */
    extern /* Double Complex */ VOID wzdotc_(doublecomplex *, integer *, 
	    doublecomplex *, integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --zy;
    --zx;

    /* Function Body */
    zdotc_(&z__1, n, &zx[1], incx, &zy[1], incy);
    ret->r = z__1.r, ret->i = z__1.i;
    return 0;
} /* zdotcwrp_ */

/* Subroutine */ int zdotuwrp_(doublecomplex *ret, integer *n, doublecomplex *
	zx, integer *incx, doublecomplex *zy, integer *incy)
{
    /* System generated locals */
    doublecomplex z__1;

    /* Local variables */
    extern /* Double Complex */ VOID wzdotu_(doublecomplex *, integer *, 
	    doublecomplex *, integer *, doublecomplex *, integer *);

    /* Parameter adjustments */
    --zy;
    --zx;

    /* Function Body */
    zdotu_(&z__1, n, &zx[1], incx, &zy[1], incy);
    ret->r = z__1.r, ret->i = z__1.i;
    return 0;
} /* zdotuwrp_ */

