$(R_BUILD)/$(STATSRCDIR)/ansari.o: ansari.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rmath.h \
 stats.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/approx.o: approx.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/arima.o: arima.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  ts.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 stats.h statsR.h
$(R_BUILD)/$(STATSRCDIR)/bandwidths.o: bandwidths.c  \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/bsplvd.o: bsplvd.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/burg.o: burg.c \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/bvalue.o: bvalue.c $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h 
$(R_BUILD)/$(STATSRCDIR)/bvalus.o: bvalus.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/chisqsim.o: chisqsim.c \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rmath.h \
 stats.h
$(R_BUILD)/$(STATSRCDIR)/complete_cases.o: complete_cases.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(STATSRCDIR)/cov.o: cov.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/d2x2xk.o: d2x2xk.c \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/dblcen.o: dblcen.c \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/deriv.o: deriv.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(STATSRCDIR)/distance.o: distance.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rmath.h \
 stats.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h
$(R_BUILD)/$(STATSRCDIR)/distn.o: distn.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/eureka.o: eureka.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/family.o: family.c \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 stats.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/fexact.o: fexact.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  stats.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/fft.o: fft.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(STATSRCDIR)/filters.o: filters.c \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  ts.h stats.h
$(R_BUILD)/$(STATSRCDIR)/fourier.o: fourier.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
  statsR.h
$(R_BUILD)/$(STATSRCDIR)/hclust.o: hclust.c $(STATSRCDIR)/../../include/f2c.h \
  misc.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(STATSRCDIR)/hclust-utils.o: hclust-utils.c \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/HoltWinters.o: HoltWinters.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  ts.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 stats.h
$(R_BUILD)/$(STATSRCDIR)/influence.o: influence.c \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/init.o: init.c $(STATSRCDIR)/../include/initpkg.h \
 $(STATSRCDIR)/../include/R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 modreg.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 nls.h port.h stats.h statsR.h ts.h \
 $(STATSRCDIR)/../include/R_ext/Visibility.h
$(R_BUILD)/$(STATSRCDIR)/integrate.o: integrate.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(STATSRCDIR)/isoreg.o: isoreg.c modreg.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/kendall.o: kendall.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/kmeans.o: kmeans.c modreg.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/kmns.o: kmns.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/ks.o: ks.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rmath.h
$(R_BUILD)/$(STATSRCDIR)/ksmooth.o: ksmooth.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/line.o: line.c \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/lm.o: lm.c \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/lminfl.o: lminfl.c $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../include/R_ext/Linpack.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/BLAS.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h
$(R_BUILD)/$(STATSRCDIR)/loessc.o: loessc.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  misc.h $(STATSRCDIR)/../../include/f2c.h
$(R_BUILD)/$(STATSRCDIR)/loessf.o: loessf.c $(STATSRCDIR)/../nmath/nmath.h \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../../include/f2c.h $(STATSRCDIR)/../../include/blas.h $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Linpack.h \
 $(STATSRCDIR)/../include/R_ext/BLAS.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 misc.h
$(R_BUILD)/$(STATSRCDIR)/loglin.o: loglin.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/lowess.o: lowess.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h
$(R_BUILD)/$(STATSRCDIR)/mAR.o: mAR.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 ts.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 stats.h
$(R_BUILD)/$(STATSRCDIR)/massdist.o: massdist.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h
$(R_BUILD)/$(STATSRCDIR)/model.o: model.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
  statsR.h
$(R_BUILD)/$(STATSRCDIR)/monoSpl.o: monoSpl.c \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 modreg.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/RS.h 
$(R_BUILD)/$(STATSRCDIR)/nls.o: nls.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 nls.h
$(R_BUILD)/$(STATSRCDIR)/nscor.o: nscor.c \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h
$(R_BUILD)/$(STATSRCDIR)/optim.o: optim.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 statsR.h
$(R_BUILD)/$(STATSRCDIR)/optimize.o: optimize.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 statsR.h stats.h \
 $(STATSRCDIR)/../include/Rmath.h 
$(R_BUILD)/$(STATSRCDIR)/pacf.o: pacf.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  ts.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 stats.h
$(R_BUILD)/$(STATSRCDIR)/port.o: port.c \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 port.h  \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/BLAS.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../../include/blas.h $(STATSRCDIR)/../../include/f2c.h misc.h $(STATSRCDIR)/../../include/f2c.h
$(R_BUILD)/$(STATSRCDIR)/portsrc.o: portsrc.c $(STATSRCDIR)/../../include/f2c.h \
  misc.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(STATSRCDIR)/ppr.o: ppr.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/PPsum.o: PPsum.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/prho.o: prho.c  \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/qsbart.o: qsbart.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/random.o: random.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/../include/Rinlinedfuns.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/Rmath.h \
  statsR.h stats.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h
$(R_BUILD)/$(STATSRCDIR)/rcont.o: rcont.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h
$(R_BUILD)/$(STATSRCDIR)/rWishart.o: rWishart.c  \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rmath.h \
 stats.h statsR.h $(STATSRCDIR)/../../include/blas.h $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../../include/clapack.h $(STATSRCDIR)/../../include/./f2c.h
$(R_BUILD)/$(STATSRCDIR)/sbart.o: sbart.c modreg.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/Rmath.h
$(R_BUILD)/$(STATSRCDIR)/sgram.o: sgram.c $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h 
$(R_BUILD)/$(STATSRCDIR)/sinerp.o: sinerp.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/smooth.o: smooth.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h
$(R_BUILD)/$(STATSRCDIR)/splines.o: splines.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 statsR.h \
 $(STATSRCDIR)/../include/Defn.h \
 $(STATSRCDIR)/../include/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/../include/Rinternals.h \
 $(STATSRCDIR)/../include/Errormsg.h \
 $(STATSRCDIR)/../include/../include/R_ext/libextern.h 
$(R_BUILD)/$(STATSRCDIR)/Srunmed.o: Srunmed.c modreg.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 Trunmed.c
$(R_BUILD)/$(STATSRCDIR)/sslvrg.o: sslvrg.c $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Linpack.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/BLAS.h \
 $(STATSRCDIR)/../include/R_ext/RS.h
$(R_BUILD)/$(STATSRCDIR)/starma.o: starma.c \
 $(STATSRCDIR)/../include/config.h \
 $(STATSRCDIR)/../include/R.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Arith.h \
 $(STATSRCDIR)/../include/R_ext/libextern.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/Constants.h \
 $(STATSRCDIR)/../include/R_ext/Error.h \
 $(STATSRCDIR)/../include/R_ext/Memory.h \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/R_ext/Random.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
  ts.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 stats.h
$(R_BUILD)/$(STATSRCDIR)/stl.o: stl.c $(STATSRCDIR)/../../include/f2c.h 
$(R_BUILD)/$(STATSRCDIR)/stxwx.o: stxwx.c $(STATSRCDIR)/../../include/f2c.h \
 $(STATSRCDIR)/../include/R_ext/Utils.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/Complex.h 
$(R_BUILD)/$(STATSRCDIR)/swilk.o: swilk.c  \
 $(STATSRCDIR)/../include/Rmath.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/Trunmed.o: Trunmed.c  \
 $(STATSRCDIR)/../include/R_ext/Print.h \
 $(STATSRCDIR)/../include/Rinternals.h \
 $(STATSRCDIR)/../include/./R_ext/Arith.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Error.h \
 $(STATSRCDIR)/../include/./R_ext/Memory.h \
 $(STATSRCDIR)/../include/./R_ext/Utils.h \
 $(STATSRCDIR)/../include/./R_ext/Boolean.h \
 $(STATSRCDIR)/../include/./R_ext/Complex.h \
 $(STATSRCDIR)/../include/./R_ext/Print.h \
 $(STATSRCDIR)/../include/./R_ext/Rdynload.h \
 $(STATSRCDIR)/../include/./R_ext/libextern.h \
 $(STATSRCDIR)/../include/Rconfig.h
$(R_BUILD)/$(STATSRCDIR)/zeroin.o: zeroin.c  \
 $(STATSRCDIR)/../include/R_ext/Applic.h \
 $(STATSRCDIR)/../include/R_ext/Boolean.h \
 $(STATSRCDIR)/../include/R_ext/RS.h \
 $(STATSRCDIR)/../include/Rconfig.h \
 $(STATSRCDIR)/../include/R_ext/Error.h
