$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ccolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ccolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ccopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cdiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/clacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/clangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/claqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cmemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cmyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/colamd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cpruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/creadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/creadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/creadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/csp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/cutil.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcomplex.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ddiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dlacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dlangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dlaqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dmach.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dmemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dmyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dpruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dreadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dreadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dreadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dsp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dutil.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/dzsum1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/get_perm_c.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/heap_relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/icmax1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ccolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ccopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cdrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_cpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_csnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ddrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_dsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_heap_relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_scolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_scopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_sdrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_spanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_spivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_ssnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zdrop_row.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ilu_zsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/izmax1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/mark_relax.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/memory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/mmd.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/qselect.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/relax_snode.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scomplex.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/scsum1.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sdiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/slacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/slangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/slaqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/smach.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/smemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/smyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sp_coletree.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sp_ienv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sp_preorder.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/spruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sreadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/ssp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/superlu_timer.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/sutil.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/util.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zcolumn_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zcolumn_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zcopy_to_ucol.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zdiagonal.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgscon.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsequ.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsisx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsitrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgsrfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgssv.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgssvx.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgstrf.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zgstrs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zlacon2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zlangs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zlaqgs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zldperm.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zmemory.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zmyblas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpanel_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpanel_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpivotgrowth.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpivotL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zpruneL.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zreadhb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zreadrb.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zreadtriple.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsnode_bmod.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsnode_dfs.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsp_blas2.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zsp_blas3.c \
$(MODULESRCDIR)/scipy/sparse/linalg/dsolve/SuperLU/SRC/zutil.c \
